/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Client-side COM declarations for id3d12commandqueue: per-interface vtable
 * structs, default thunk prototypes, default vtable populators, and default
 * constructors.
 *
 * The thunk bodies, populators, and constructors live in the matching .c
 * file.  This split keeps the headers small and prevents N copies of the
 * thunk code from landing in every TU that pulls in this family.
 */

#ifndef NPT_PROTOCOL_CLIENT_ID3D12COMMANDQUEUE_H
#define NPT_PROTOCOL_CLIENT_ID3D12COMMANDQUEUE_H

#include "npt_protocol_guest_id3d12commandqueue.h"
#include "npt_protocol_client_id3d12pageable.h"

/* Forward-declare struct npt_device so the client_create prototypes don't
 * trigger the "declared inside parameter list" warning.  The full
 * definition lives in the consumer's npt_device.h, which the .c file pulls
 * in via npt_com.h. */
struct npt_device;

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"



/* ================================================================== */
/* ID3D12CommandQueue                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * ID3D12CommandQueueVtbl, by construction.
 */
struct npt_id3d12commandqueue_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: ID3D12Object::GetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *GetPrivateData)(void *self, const GUID * guid, UINT * pDataSize, void * pData);
    /* slot 4: ID3D12Object::SetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateData)(void *self, const GUID * guid, UINT DataSize, const void * pData);
    /* slot 5: ID3D12Object::SetPrivateDataInterface */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateDataInterface)(void *self, const GUID * guid, const IUnknown * pData);
    /* slot 6: ID3D12Object::SetName */
    HRESULT (NPT_STDMETHODCALLTYPE *SetName)(void *self, const WCHAR * Name);
    /* slot 7: ID3D12DeviceChild::GetDevice */
    HRESULT (NPT_STDMETHODCALLTYPE *GetDevice)(void *self, const IID * riid, void ** ppvDevice);
    /* slot 8: ID3D12CommandQueue::UpdateTileMappings */
    void (NPT_STDMETHODCALLTYPE *UpdateTileMappings)(void *self, ID3D12Resource * pResource, UINT NumResourceRegions, const D3D12_TILED_RESOURCE_COORDINATE * pResourceRegionStartCoordinates, const D3D12_TILE_REGION_SIZE * pResourceRegionSizes, ID3D12Heap * pHeap, UINT NumRanges, const D3D12_TILE_RANGE_FLAGS * pRangeFlags, const UINT * pHeapRangeStartOffsets, const UINT * pRangeTileCounts, D3D12_TILE_MAPPING_FLAGS Flags);
    /* slot 9: ID3D12CommandQueue::CopyTileMappings */
    void (NPT_STDMETHODCALLTYPE *CopyTileMappings)(void *self, ID3D12Resource * pDstResource, const D3D12_TILED_RESOURCE_COORDINATE * pDstRegionStartCoordinate, ID3D12Resource * pSrcResource, const D3D12_TILED_RESOURCE_COORDINATE * pSrcRegionStartCoordinate, const D3D12_TILE_REGION_SIZE * pRegionSize, D3D12_TILE_MAPPING_FLAGS Flags);
    /* slot 10: ID3D12CommandQueue::ExecuteCommandLists */
    void (NPT_STDMETHODCALLTYPE *ExecuteCommandLists)(void *self, UINT NumCommandLists, ID3D12CommandList ** ppCommandLists);
    /* slot 11: ID3D12CommandQueue::SetMarker */
    void (NPT_STDMETHODCALLTYPE *SetMarker)(void *self, UINT Metadata, const void * pData, UINT Size);
    /* slot 12: ID3D12CommandQueue::BeginEvent */
    void (NPT_STDMETHODCALLTYPE *BeginEvent)(void *self, UINT Metadata, const void * pData, UINT Size);
    /* slot 13: ID3D12CommandQueue::EndEvent */
    void (NPT_STDMETHODCALLTYPE *EndEvent)(void *self);
    /* slot 14: ID3D12CommandQueue::Signal */
    HRESULT (NPT_STDMETHODCALLTYPE *Signal)(void *self, ID3D12Fence * pFence, UINT64 Value);
    /* slot 15: ID3D12CommandQueue::Wait */
    HRESULT (NPT_STDMETHODCALLTYPE *Wait)(void *self, ID3D12Fence * pFence, UINT64 Value);
    /* slot 16: ID3D12CommandQueue::GetTimestampFrequency */
    HRESULT (NPT_STDMETHODCALLTYPE *GetTimestampFrequency)(void *self, UINT64 * pFrequency);
    /* slot 17: ID3D12CommandQueue::GetClockCalibration */
    HRESULT (NPT_STDMETHODCALLTYPE *GetClockCalibration)(void *self, UINT64 * pGpuTimestamp, UINT64 * pCpuTimestamp);
    /* slot 18: ID3D12CommandQueue::GetDesc */
    D3D12_COMMAND_QUEUE_DESC (NPT_STDMETHODCALLTYPE *GetDesc)(void *self);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern void NPT_STDMETHODCALLTYPE
npt_id3d12commandqueue_default_UpdateTileMappings(void *self, ID3D12Resource * pResource, UINT NumResourceRegions, const D3D12_TILED_RESOURCE_COORDINATE * pResourceRegionStartCoordinates, const D3D12_TILE_REGION_SIZE * pResourceRegionSizes, ID3D12Heap * pHeap, UINT NumRanges, const D3D12_TILE_RANGE_FLAGS * pRangeFlags, const UINT * pHeapRangeStartOffsets, const UINT * pRangeTileCounts, D3D12_TILE_MAPPING_FLAGS Flags);
extern void NPT_STDMETHODCALLTYPE
npt_id3d12commandqueue_default_CopyTileMappings(void *self, ID3D12Resource * pDstResource, const D3D12_TILED_RESOURCE_COORDINATE * pDstRegionStartCoordinate, ID3D12Resource * pSrcResource, const D3D12_TILED_RESOURCE_COORDINATE * pSrcRegionStartCoordinate, const D3D12_TILE_REGION_SIZE * pRegionSize, D3D12_TILE_MAPPING_FLAGS Flags);
extern void NPT_STDMETHODCALLTYPE
npt_id3d12commandqueue_default_ExecuteCommandLists(void *self, UINT NumCommandLists, ID3D12CommandList ** ppCommandLists);
extern void NPT_STDMETHODCALLTYPE
npt_id3d12commandqueue_default_SetMarker(void *self, UINT Metadata, const void * pData, UINT Size);
extern void NPT_STDMETHODCALLTYPE
npt_id3d12commandqueue_default_BeginEvent(void *self, UINT Metadata, const void * pData, UINT Size);
extern void NPT_STDMETHODCALLTYPE
npt_id3d12commandqueue_default_EndEvent(void *self);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d12commandqueue_default_Signal(void *self, ID3D12Fence * pFence, UINT64 Value);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d12commandqueue_default_Wait(void *self, ID3D12Fence * pFence, UINT64 Value);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d12commandqueue_default_GetTimestampFrequency(void *self, UINT64 * pFrequency);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d12commandqueue_default_GetClockCalibration(void *self, UINT64 * pGpuTimestamp, UINT64 * pCpuTimestamp);
extern D3D12_COMMAND_QUEUE_DESC NPT_STDMETHODCALLTYPE
npt_id3d12commandqueue_default_GetDesc(void *self);

/* Default IUnknown thunks for ID3D12CommandQueue.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d12commandqueue_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_id3d12commandqueue_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_id3d12commandqueue_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_id3d12commandqueue_fill_default_vtbl(struct npt_id3d12commandqueue_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_id3d12commandqueue_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_id3d12commandqueue_client_vtbl npt_id3d12commandqueue_default_vtbl_storage;
extern void
npt_id3d12commandqueue_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_id3d12commandqueue_client_create(struct npt_device *dev, uint64_t host_id);


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_CLIENT_ID3D12COMMANDQUEUE_H */
