/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d11devicechild.
 */

#ifndef NPT_PROTOCOL_GUEST_ID3D11DEVICECHILD_H
#define NPT_PROTOCOL_GUEST_ID3D11DEVICECHILD_H

#include "npt_protocol_guest_structs.h"
/* For npt_com_allocate_next_id -- called inline from every output
 * COM handle's encode path. */
#include "npt_protocol_guest_cs.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D11DeviceChild::GetDevice
 */

struct npt_command_ID3D11DeviceChild_GetDevice {
    void *_self;
    ID3D11Device ** ppDevice;
    /* Shadow: the guest-allocated id for ppDevice arrives in the command
     * body (no reply round-trip).  The post-dispatch register pass reads
     * this field and inserts {_guest_id_ppDevice -> *ppDevice} in the
     * context object table. */
    uint64_t _guest_id_ppDevice;
};

static inline size_t
npt_sizeof_ID3D11DeviceChild_GetDevice(ID3D11Device ** ppDevice)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
cmd_size += sizeof(uint64_t);  /* ppDevice: guest id */
    return cmd_size;
}

static inline void
npt_encode_ID3D11DeviceChild_GetDevice(struct npt_cs_encoder *enc,
                                       uint32_t cmd_flags,
                                       npt_object_id object_id,
                                       ID3D11Device ** ppDevice)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D11DeviceChild_GetDevice(ppDevice);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D11DeviceChild,
                                 NPT_METHOD_ID3D11DeviceChild_GetDevice),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
{
    uint64_t _gid_ppDevice = 0;
    if (ppDevice) {
        _gid_ppDevice = npt_com_allocate_next_id();
        *ppDevice = (ID3D11Device *)(uintptr_t)_gid_ppDevice;
    }
    npt_encode_uint64_t(enc, &_gid_ppDevice);
}
}

static inline size_t
npt_sizeof_ID3D11DeviceChild_GetDevice_reply(ID3D11Device ** ppDevice)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip ppDevice (guest-allocated id, registered host-side; not in reply) */
    return cmd_size;
}

static inline void
npt_decode_ID3D11DeviceChild_GetDevice_reply(struct npt_cs_decoder *dec,
                                             ID3D11Device ** ppDevice)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D11DeviceChild,
                                                  NPT_METHOD_ID3D11DeviceChild_GetDevice))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D11DeviceChild_GetDevice reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D11DeviceChild,
                                       NPT_METHOD_ID3D11DeviceChild_GetDevice));
        return;
    }
/* skip ppDevice (guest-allocated id, wrapper built on client thunk; not in reply) */
}

static inline void
npt_submit_ID3D11DeviceChild_GetDevice(struct npt_ring *ring,
                                       uint32_t cmd_flags,
                                       npt_object_id object_id,
                                       ID3D11Device ** ppDevice,
                                       struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D11DeviceChild_GetDevice(ppDevice);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D11DeviceChild_GetDevice_reply(ppDevice)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D11DeviceChild_GetDevice(enc, cmd_flags, object_id, ppDevice);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D11DeviceChild_GetDevice(struct npt_ring *ring,
                                      npt_object_id object_id,
                                      ID3D11Device ** ppDevice)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D11DeviceChild_GetDevice(ring, 0, object_id, ppDevice, &submit);
}

static inline void
npt_call_ID3D11DeviceChild_GetDevice(struct npt_ring *ring,
                                     npt_object_id object_id,
                                     ID3D11Device ** ppDevice)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D11DeviceChild_GetDevice(ring, NPT_CMD_FLAG_REPLY, object_id, ppDevice, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        npt_decode_ID3D11DeviceChild_GetDevice_reply(dec, ppDevice);
        npt_ring_free_command_reply(ring, &submit);
    }
}

/*
 * ID3D11DeviceChild::GetPrivateData
 */

struct npt_command_ID3D11DeviceChild_GetPrivateData {
    void *_self;
    const GUID * guid;
    UINT * pDataSize;
    void * pData;
    HRESULT ret;
};

static inline size_t
npt_sizeof_ID3D11DeviceChild_GetPrivateData(const GUID * guid,const UINT * pDataSize,const void * pData)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_simple_pointer(guid);
    if (guid)
        cmd_size += npt_sizeof_GUID(guid, max_mode);
    cmd_size += npt_sizeof_simple_pointer(pDataSize);
    if (pDataSize)
        cmd_size += npt_sizeof_UINT(pDataSize, max_mode);
/* skip pData (output only) */
    return cmd_size;
}

static inline void
npt_encode_ID3D11DeviceChild_GetPrivateData(struct npt_cs_encoder *enc,
                                            uint32_t cmd_flags,
                                            npt_object_id object_id,
                                            const GUID * guid,
                                            UINT * pDataSize,
                                            void * pData)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D11DeviceChild_GetPrivateData(guid,pDataSize,pData);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D11DeviceChild,
                                 NPT_METHOD_ID3D11DeviceChild_GetPrivateData),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    if (npt_encode_simple_pointer(enc, guid))
        npt_encode_GUID(enc, guid);
    if (npt_encode_simple_pointer(enc, pDataSize))
        npt_encode_UINT(enc, pDataSize);
/* skip pData (output only) */
}

static inline size_t
npt_sizeof_ID3D11DeviceChild_GetPrivateData_reply(const GUID * guid,const UINT * pDataSize,const void * pData)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip guid (input only) */
    cmd_size += npt_sizeof_simple_pointer((const void *)1);
    cmd_size += npt_sizeof_UINT(&(const UINT){0}, 1);
    if (pData) {
        cmd_size += npt_sizeof_array_count(*pDataSize);
        cmd_size += npt_sizeof_blob_array(pData, *pDataSize);
    } else {
        cmd_size += npt_sizeof_array_count(0);
    }
    return cmd_size;
}

static inline void
npt_decode_ID3D11DeviceChild_GetPrivateData_reply(struct npt_cs_decoder *dec,
                                                  UINT * pDataSize,
                                                  void * pData,
                                                  HRESULT *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D11DeviceChild,
                                                  NPT_METHOD_ID3D11DeviceChild_GetPrivateData))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D11DeviceChild_GetPrivateData reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D11DeviceChild,
                                       NPT_METHOD_ID3D11DeviceChild_GetPrivateData));
        if (ret) *ret = (HRESULT)0x887A0005 /* DXGI_ERROR_DEVICE_REMOVED */;
        return;
    }
    if (ret) *ret = (HRESULT)_reply.cmd_return;
    if (npt_decode_simple_pointer(dec)) {
        if (pDataSize)
            npt_decode_UINT(dec, (UINT *)pDataSize);
    }
    {
        const uint64_t _blob_size = npt_decode_array_count_unchecked(dec);
        if (_blob_size && pData)
            npt_decode_blob_array(dec, (void *)pData, _blob_size);
        else if (_blob_size)
            npt_cs_decoder_read(dec, ((_blob_size + 3) & ~3), NULL, 0);
    }
}

static inline void
npt_submit_ID3D11DeviceChild_GetPrivateData(struct npt_ring *ring,
                                            uint32_t cmd_flags,
                                            npt_object_id object_id,
                                            const GUID * guid,
                                            UINT * pDataSize,
                                            void * pData,
                                            struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D11DeviceChild_GetPrivateData(guid,pDataSize,pData);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D11DeviceChild_GetPrivateData_reply(guid,pDataSize,pData)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D11DeviceChild_GetPrivateData(enc, cmd_flags, object_id, guid, pDataSize, pData);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D11DeviceChild_GetPrivateData(struct npt_ring *ring,
                                           npt_object_id object_id,
                                           const GUID * guid,
                                           UINT * pDataSize,
                                           void * pData)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D11DeviceChild_GetPrivateData(ring, 0, object_id, guid, pDataSize, pData, &submit);
}

static inline HRESULT
npt_call_ID3D11DeviceChild_GetPrivateData(struct npt_ring *ring,
                                          npt_object_id object_id,
                                          const GUID * guid,
                                          UINT * pDataSize,
                                          void * pData)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D11DeviceChild_GetPrivateData(ring, NPT_CMD_FLAG_REPLY, object_id, guid, pDataSize, pData, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        HRESULT _ret;
        npt_decode_ID3D11DeviceChild_GetPrivateData_reply(dec, pDataSize, pData, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (HRESULT)0x8007000E /* E_OUTOFMEMORY */;
    }
}

/*
 * ID3D11DeviceChild::SetPrivateData
 */

struct npt_command_ID3D11DeviceChild_SetPrivateData {
    void *_self;
    const GUID * guid;
    UINT DataSize;
    const void * pData;
    HRESULT ret;
};

static inline size_t
npt_sizeof_ID3D11DeviceChild_SetPrivateData(const GUID * guid,const UINT DataSize,const void * pData)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_simple_pointer(guid);
    if (guid)
        cmd_size += npt_sizeof_GUID(guid, max_mode);
    cmd_size += npt_sizeof_UINT(&DataSize, max_mode);
    if (pData) {
        cmd_size += npt_sizeof_array_count(DataSize);
        cmd_size += npt_sizeof_blob_array(pData, DataSize);
    } else {
        cmd_size += npt_sizeof_array_count(0);
    }
    return cmd_size;
}

static inline void
npt_encode_ID3D11DeviceChild_SetPrivateData(struct npt_cs_encoder *enc,
                                            uint32_t cmd_flags,
                                            npt_object_id object_id,
                                            const GUID * guid,
                                            UINT DataSize,
                                            const void * pData)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D11DeviceChild_SetPrivateData(guid,DataSize,pData);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D11DeviceChild,
                                 NPT_METHOD_ID3D11DeviceChild_SetPrivateData),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    if (npt_encode_simple_pointer(enc, guid))
        npt_encode_GUID(enc, guid);
    npt_encode_UINT(enc, &DataSize);
    if (pData) {
        npt_encode_array_count(enc, DataSize);
        npt_encode_blob_array(enc, pData, DataSize);
    } else {
        npt_encode_array_count(enc, 0);
    }
}

static inline size_t
npt_sizeof_ID3D11DeviceChild_SetPrivateData_reply(const GUID * guid,const UINT DataSize,const void * pData)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip guid (input only) */
/* skip DataSize (input only) */
/* skip pData (input only) */
    return cmd_size;
}

static inline void
npt_decode_ID3D11DeviceChild_SetPrivateData_reply(struct npt_cs_decoder *dec,
                                                  HRESULT *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D11DeviceChild,
                                                  NPT_METHOD_ID3D11DeviceChild_SetPrivateData))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D11DeviceChild_SetPrivateData reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D11DeviceChild,
                                       NPT_METHOD_ID3D11DeviceChild_SetPrivateData));
        if (ret) *ret = (HRESULT)0x887A0005 /* DXGI_ERROR_DEVICE_REMOVED */;
        return;
    }
    if (ret) *ret = (HRESULT)_reply.cmd_return;
}

static inline void
npt_submit_ID3D11DeviceChild_SetPrivateData(struct npt_ring *ring,
                                            uint32_t cmd_flags,
                                            npt_object_id object_id,
                                            const GUID * guid,
                                            UINT DataSize,
                                            const void * pData,
                                            struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D11DeviceChild_SetPrivateData(guid,DataSize,pData);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D11DeviceChild_SetPrivateData_reply(guid,DataSize,pData)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D11DeviceChild_SetPrivateData(enc, cmd_flags, object_id, guid, DataSize, pData);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D11DeviceChild_SetPrivateData(struct npt_ring *ring,
                                           npt_object_id object_id,
                                           const GUID * guid,
                                           UINT DataSize,
                                           const void * pData)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D11DeviceChild_SetPrivateData(ring, 0, object_id, guid, DataSize, pData, &submit);
}

static inline HRESULT
npt_call_ID3D11DeviceChild_SetPrivateData(struct npt_ring *ring,
                                          npt_object_id object_id,
                                          const GUID * guid,
                                          UINT DataSize,
                                          const void * pData)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D11DeviceChild_SetPrivateData(ring, NPT_CMD_FLAG_REPLY, object_id, guid, DataSize, pData, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        HRESULT _ret;
        npt_decode_ID3D11DeviceChild_SetPrivateData_reply(dec, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (HRESULT)0x8007000E /* E_OUTOFMEMORY */;
    }
}

/*
 * ID3D11DeviceChild::SetPrivateDataInterface
 */

struct npt_command_ID3D11DeviceChild_SetPrivateDataInterface {
    void *_self;
    const GUID * guid;
    const IUnknown * pData;
    HRESULT ret;
};

static inline size_t
npt_sizeof_ID3D11DeviceChild_SetPrivateDataInterface(const GUID * guid,const IUnknown * pData)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_simple_pointer(guid);
    if (guid)
        cmd_size += npt_sizeof_GUID(guid, max_mode);
    cmd_size += sizeof(uint64_t);
    return cmd_size;
}

static inline void
npt_encode_ID3D11DeviceChild_SetPrivateDataInterface(struct npt_cs_encoder *enc,
                                                     uint32_t cmd_flags,
                                                     npt_object_id object_id,
                                                     const GUID * guid,
                                                     const IUnknown * pData)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D11DeviceChild_SetPrivateDataInterface(guid,pData);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D11DeviceChild,
                                 NPT_METHOD_ID3D11DeviceChild_SetPrivateDataInterface),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    if (npt_encode_simple_pointer(enc, guid))
        npt_encode_GUID(enc, guid);
    npt_encode_com_handle(enc, npt_object_get_id(pData));
}

static inline size_t
npt_sizeof_ID3D11DeviceChild_SetPrivateDataInterface_reply(const GUID * guid,const IUnknown * pData)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip guid (input only) */
/* skip pData (input only) */
    return cmd_size;
}

static inline void
npt_decode_ID3D11DeviceChild_SetPrivateDataInterface_reply(struct npt_cs_decoder *dec,
                                                           HRESULT *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D11DeviceChild,
                                                  NPT_METHOD_ID3D11DeviceChild_SetPrivateDataInterface))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D11DeviceChild_SetPrivateDataInterface reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D11DeviceChild,
                                       NPT_METHOD_ID3D11DeviceChild_SetPrivateDataInterface));
        if (ret) *ret = (HRESULT)0x887A0005 /* DXGI_ERROR_DEVICE_REMOVED */;
        return;
    }
    if (ret) *ret = (HRESULT)_reply.cmd_return;
}

static inline void
npt_submit_ID3D11DeviceChild_SetPrivateDataInterface(struct npt_ring *ring,
                                                     uint32_t cmd_flags,
                                                     npt_object_id object_id,
                                                     const GUID * guid,
                                                     const IUnknown * pData,
                                                     struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D11DeviceChild_SetPrivateDataInterface(guid,pData);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D11DeviceChild_SetPrivateDataInterface_reply(guid,pData)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D11DeviceChild_SetPrivateDataInterface(enc, cmd_flags, object_id, guid, pData);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D11DeviceChild_SetPrivateDataInterface(struct npt_ring *ring,
                                                    npt_object_id object_id,
                                                    const GUID * guid,
                                                    const IUnknown * pData)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D11DeviceChild_SetPrivateDataInterface(ring, 0, object_id, guid, pData, &submit);
}

static inline HRESULT
npt_call_ID3D11DeviceChild_SetPrivateDataInterface(struct npt_ring *ring,
                                                   npt_object_id object_id,
                                                   const GUID * guid,
                                                   const IUnknown * pData)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D11DeviceChild_SetPrivateDataInterface(ring, NPT_CMD_FLAG_REPLY, object_id, guid, pData, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        HRESULT _ret;
        npt_decode_ID3D11DeviceChild_SetPrivateDataInterface_reply(dec, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (HRESULT)0x8007000E /* E_OUTOFMEMORY */;
    }
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_GUEST_ID3D11DEVICECHILD_H */
