/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for idxgidevicesubobject.
 */

#ifndef NPT_PROTOCOL_GUEST_IDXGIDEVICESUBOBJECT_H
#define NPT_PROTOCOL_GUEST_IDXGIDEVICESUBOBJECT_H

#include "npt_protocol_guest_structs.h"
/* For npt_com_allocate_next_id -- called inline from every output
 * COM handle's encode path. */
#include "npt_protocol_guest_cs.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * IDXGIDeviceSubObject::GetDevice
 */

struct npt_command_IDXGIDeviceSubObject_GetDevice {
    void *_self;
    const IID * riid;
    void ** ppDevice;
    /* Shadow: the guest-allocated id for ppDevice arrives in the command
     * body (no reply round-trip).  The post-dispatch register pass reads
     * this field and inserts {_guest_id_ppDevice -> *ppDevice} in the
     * context object table. */
    uint64_t _guest_id_ppDevice;
    HRESULT ret;
};

static inline size_t
npt_sizeof_IDXGIDeviceSubObject_GetDevice(const IID * riid,void ** ppDevice)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_simple_pointer(riid);
    if (riid)
        cmd_size += npt_sizeof_IID(riid, max_mode);
cmd_size += sizeof(uint64_t);  /* ppDevice: guest id */
    return cmd_size;
}

static inline void
npt_encode_IDXGIDeviceSubObject_GetDevice(struct npt_cs_encoder *enc,
                                          uint32_t cmd_flags,
                                          npt_object_id object_id,
                                          const IID * riid,
                                          void ** ppDevice)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_IDXGIDeviceSubObject_GetDevice(riid,ppDevice);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIDeviceSubObject,
                                 NPT_METHOD_IDXGIDeviceSubObject_GetDevice),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    if (npt_encode_simple_pointer(enc, riid))
        npt_encode_IID(enc, riid);
{
    uint64_t _gid_ppDevice = 0;
    if (ppDevice) {
        _gid_ppDevice = npt_com_allocate_next_id();
        *ppDevice = (void *)(uintptr_t)_gid_ppDevice;
    }
    npt_encode_uint64_t(enc, &_gid_ppDevice);
}
}

static inline size_t
npt_sizeof_IDXGIDeviceSubObject_GetDevice_reply(const IID * riid,void ** ppDevice)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip riid (input only) */
/* skip ppDevice (guest-allocated id, registered host-side; not in reply) */
    return cmd_size;
}

static inline void
npt_decode_IDXGIDeviceSubObject_GetDevice_reply(struct npt_cs_decoder *dec,
                                                void ** ppDevice,
                                                HRESULT *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIDeviceSubObject,
                                                  NPT_METHOD_IDXGIDeviceSubObject_GetDevice))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("IDXGIDeviceSubObject_GetDevice reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIDeviceSubObject,
                                       NPT_METHOD_IDXGIDeviceSubObject_GetDevice));
        if (ret) *ret = (HRESULT)0x887A0005 /* DXGI_ERROR_DEVICE_REMOVED */;
        return;
    }
    if (ret) *ret = (HRESULT)_reply.cmd_return;
/* skip ppDevice (guest-allocated id, wrapper built on client thunk; not in reply) */
}

static inline void
npt_submit_IDXGIDeviceSubObject_GetDevice(struct npt_ring *ring,
                                          uint32_t cmd_flags,
                                          npt_object_id object_id,
                                          const IID * riid,
                                          void ** ppDevice,
                                          struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_IDXGIDeviceSubObject_GetDevice(riid,ppDevice);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_IDXGIDeviceSubObject_GetDevice_reply(riid,ppDevice)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_IDXGIDeviceSubObject_GetDevice(enc, cmd_flags, object_id, riid, ppDevice);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_IDXGIDeviceSubObject_GetDevice(struct npt_ring *ring,
                                         npt_object_id object_id,
                                         const IID * riid,
                                         void ** ppDevice)
{
    struct npt_ring_submit_command submit;
    npt_submit_IDXGIDeviceSubObject_GetDevice(ring, 0, object_id, riid, ppDevice, &submit);
}

static inline HRESULT
npt_call_IDXGIDeviceSubObject_GetDevice(struct npt_ring *ring,
                                        npt_object_id object_id,
                                        const IID * riid,
                                        void ** ppDevice)
{
    struct npt_ring_submit_command submit;
    npt_submit_IDXGIDeviceSubObject_GetDevice(ring, NPT_CMD_FLAG_REPLY, object_id, riid, ppDevice, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        HRESULT _ret;
        npt_decode_IDXGIDeviceSubObject_GetDevice_reply(dec, ppDevice, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (HRESULT)0x8007000E /* E_OUTOFMEMORY */;
    }
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_GUEST_IDXGIDEVICESUBOBJECT_H */
