/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Client-side COM implementation for id3d12protectedresourcesession: out-of-line default
 * thunks, default vtable populators, and default constructors for every
 * interface in this family.
 */

#include "npt_protocol_client_id3d12protectedresourcesession.h"
#include "npt_com.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-variable"



/* ================================================================== */
/* ID3D12ProtectedResourceSession                                                       */
/* ================================================================== */

/* Parent IID chain for QueryInterface fast-path.  NULL-terminated list of
 * IID pointers; QI returns self for any IID in this list. */
static const GUID *const npt_id3d12protectedresourcesession_parent_iids[] = {
    &NPT_IID_IUnknown,
    &NPT_IID_ID3D12Object,
    &NPT_IID_ID3D12DeviceChild,
    &NPT_IID_ID3D12ProtectedSession,
    &NPT_IID_ID3D12ProtectedResourceSession,
    NULL,
};

HRESULT NPT_STDMETHODCALLTYPE
npt_id3d12protectedresourcesession_default_QueryInterface(void *self, REFIID riid, void **ppvObject)
{
    HRESULT hr = npt_com_default_query_interface_chain(
        self, riid, ppvObject, npt_id3d12protectedresourcesession_parent_iids);
    if (hr == NPT_S_OK)
        return hr;
    /* Derived/sibling IIDs are resolved against the host object, one
     * wire round trip per (object, IID) lifetime: the runtime memoizes
     * the verdict and the wrapper on `self` (npt_com.c). */
    return npt_com_query_interface_host(self, riid, ppvObject);
}

ULONG NPT_STDMETHODCALLTYPE
npt_id3d12protectedresourcesession_default_AddRef(void *self)
{
    return npt_com_default_addref(self);
}

ULONG NPT_STDMETHODCALLTYPE
npt_id3d12protectedresourcesession_default_Release(void *self)
{
    return npt_com_default_release(self);
}

D3D12_PROTECTED_RESOURCE_SESSION_DESC * NPT_STDMETHODCALLTYPE
npt_id3d12protectedresourcesession_default_GetDesc(void *self, D3D12_PROTECTED_RESOURCE_SESSION_DESC *_ret_out)
{
    D3D12_PROTECTED_RESOURCE_SESSION_DESC _ret = npt_call_ID3D12ProtectedResourceSession_GetDesc(npt_com_self_ring(self),npt_com_self_id(self));
    /* COM x64 aggregate-return ABI: copy into the caller's hidden
     * return slot and hand the pointer back. */
    if (_ret_out) *_ret_out = _ret;
    return _ret_out;
}


void
npt_id3d12protectedresourcesession_fill_default_vtbl(struct npt_id3d12protectedresourcesession_client_vtbl *dst)
{
    dst->QueryInterface = npt_id3d12protectedresourcesession_default_QueryInterface;
    dst->AddRef         = npt_id3d12protectedresourcesession_default_AddRef;
    dst->Release        = npt_id3d12protectedresourcesession_default_Release;
    dst->GetPrivateData = npt_id3d12object_default_GetPrivateData;
    dst->SetPrivateData = npt_id3d12object_default_SetPrivateData;
    dst->SetPrivateDataInterface = npt_id3d12object_default_SetPrivateDataInterface;
    dst->SetName = npt_id3d12object_default_SetName;
    dst->GetDevice = npt_id3d12devicechild_default_GetDevice;
    dst->GetStatusFence = npt_id3d12protectedsession_default_GetStatusFence;
    dst->GetSessionStatus = npt_id3d12protectedsession_default_GetSessionStatus;
    dst->GetDesc = npt_id3d12protectedresourcesession_default_GetDesc;
}

/*
 * Per-interface default vtbl storage.  Populated by
 * npt_id3d12protectedresourcesession_install_default_vtbl(), which is called once at
 * runtime init time from the global client_table init function.
 */
struct npt_id3d12protectedresourcesession_client_vtbl npt_id3d12protectedresourcesession_default_vtbl_storage;

void
npt_id3d12protectedresourcesession_install_default_vtbl(void)
{
    npt_id3d12protectedresourcesession_fill_default_vtbl(&npt_id3d12protectedresourcesession_default_vtbl_storage);
}

void *
npt_id3d12protectedresourcesession_client_create(struct npt_device *dev, uint64_t host_id)
{
    struct npt_com_base *p = (struct npt_com_base *)npt_alloc(sizeof(*p));
    if (!p)
        return NULL;
    npt_com_base_init(p,
        (const void **)&npt_id3d12protectedresourcesession_default_vtbl_storage,
        dev, host_id);
    return p;
}


/* ================================================================== */
/* ID3D12ProtectedResourceSession1                                                       */
/* ================================================================== */

/* Parent IID chain for QueryInterface fast-path.  NULL-terminated list of
 * IID pointers; QI returns self for any IID in this list. */
static const GUID *const npt_id3d12protectedresourcesession1_parent_iids[] = {
    &NPT_IID_IUnknown,
    &NPT_IID_ID3D12Object,
    &NPT_IID_ID3D12DeviceChild,
    &NPT_IID_ID3D12ProtectedSession,
    &NPT_IID_ID3D12ProtectedResourceSession,
    &NPT_IID_ID3D12ProtectedResourceSession1,
    NULL,
};

HRESULT NPT_STDMETHODCALLTYPE
npt_id3d12protectedresourcesession1_default_QueryInterface(void *self, REFIID riid, void **ppvObject)
{
    HRESULT hr = npt_com_default_query_interface_chain(
        self, riid, ppvObject, npt_id3d12protectedresourcesession1_parent_iids);
    if (hr == NPT_S_OK)
        return hr;
    /* Derived/sibling IIDs are resolved against the host object, one
     * wire round trip per (object, IID) lifetime: the runtime memoizes
     * the verdict and the wrapper on `self` (npt_com.c). */
    return npt_com_query_interface_host(self, riid, ppvObject);
}

ULONG NPT_STDMETHODCALLTYPE
npt_id3d12protectedresourcesession1_default_AddRef(void *self)
{
    return npt_com_default_addref(self);
}

ULONG NPT_STDMETHODCALLTYPE
npt_id3d12protectedresourcesession1_default_Release(void *self)
{
    return npt_com_default_release(self);
}

D3D12_PROTECTED_RESOURCE_SESSION_DESC1 * NPT_STDMETHODCALLTYPE
npt_id3d12protectedresourcesession1_default_GetDesc1(void *self, D3D12_PROTECTED_RESOURCE_SESSION_DESC1 *_ret_out)
{
    D3D12_PROTECTED_RESOURCE_SESSION_DESC1 _ret = npt_call_ID3D12ProtectedResourceSession1_GetDesc1(npt_com_self_ring(self),npt_com_self_id(self));
    /* COM x64 aggregate-return ABI: copy into the caller's hidden
     * return slot and hand the pointer back. */
    if (_ret_out) *_ret_out = _ret;
    return _ret_out;
}


void
npt_id3d12protectedresourcesession1_fill_default_vtbl(struct npt_id3d12protectedresourcesession1_client_vtbl *dst)
{
    dst->QueryInterface = npt_id3d12protectedresourcesession1_default_QueryInterface;
    dst->AddRef         = npt_id3d12protectedresourcesession1_default_AddRef;
    dst->Release        = npt_id3d12protectedresourcesession1_default_Release;
    dst->GetPrivateData = npt_id3d12object_default_GetPrivateData;
    dst->SetPrivateData = npt_id3d12object_default_SetPrivateData;
    dst->SetPrivateDataInterface = npt_id3d12object_default_SetPrivateDataInterface;
    dst->SetName = npt_id3d12object_default_SetName;
    dst->GetDevice = npt_id3d12devicechild_default_GetDevice;
    dst->GetStatusFence = npt_id3d12protectedsession_default_GetStatusFence;
    dst->GetSessionStatus = npt_id3d12protectedsession_default_GetSessionStatus;
    dst->GetDesc = npt_id3d12protectedresourcesession_default_GetDesc;
    dst->GetDesc1 = npt_id3d12protectedresourcesession1_default_GetDesc1;
}

/*
 * Per-interface default vtbl storage.  Populated by
 * npt_id3d12protectedresourcesession1_install_default_vtbl(), which is called once at
 * runtime init time from the global client_table init function.
 */
struct npt_id3d12protectedresourcesession1_client_vtbl npt_id3d12protectedresourcesession1_default_vtbl_storage;

void
npt_id3d12protectedresourcesession1_install_default_vtbl(void)
{
    npt_id3d12protectedresourcesession1_fill_default_vtbl(&npt_id3d12protectedresourcesession1_default_vtbl_storage);
}

void *
npt_id3d12protectedresourcesession1_client_create(struct npt_device *dev, uint64_t host_id)
{
    struct npt_com_base *p = (struct npt_com_base *)npt_alloc(sizeof(*p));
    if (!p)
        return NULL;
    npt_com_base_init(p,
        (const void **)&npt_id3d12protectedresourcesession1_default_vtbl_storage,
        dev, host_id);
    return p;
}


#pragma GCC diagnostic pop
