/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3duserdefinedannotation.
 */

#ifndef NPT_PROTOCOL_GUEST_ID3DUSERDEFINEDANNOTATION_H
#define NPT_PROTOCOL_GUEST_ID3DUSERDEFINEDANNOTATION_H

#include "npt_protocol_guest_structs.h"
/* For npt_com_allocate_next_id -- called inline from every output
 * COM handle's encode path. */
#include "npt_protocol_guest_cs.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3DUserDefinedAnnotation::BeginEvent
 */

struct npt_command_ID3DUserDefinedAnnotation_BeginEvent {
    void *_self;
    const WCHAR * Name;
    INT ret;
};

static inline size_t
npt_sizeof_ID3DUserDefinedAnnotation_BeginEvent(const WCHAR * Name)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    if (Name) {
        const size_t _wstr_size = (npt_wcslen((const WCHAR *)Name) + 1) * sizeof(WCHAR);
        cmd_size += npt_sizeof_array_count(_wstr_size);
        cmd_size += npt_sizeof_blob_array(Name, _wstr_size);
    } else {
        cmd_size += npt_sizeof_array_count(0);
    }
    return cmd_size;
}

static inline void
npt_encode_ID3DUserDefinedAnnotation_BeginEvent(struct npt_cs_encoder *enc,
                                                uint32_t cmd_flags,
                                                npt_object_id object_id,
                                                const WCHAR * Name)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3DUserDefinedAnnotation_BeginEvent(Name);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3DUserDefinedAnnotation,
                                 NPT_METHOD_ID3DUserDefinedAnnotation_BeginEvent),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    if (Name) {
        const size_t _wstr_size = (npt_wcslen((const WCHAR *)Name) + 1) * sizeof(WCHAR);
        npt_encode_array_count(enc, _wstr_size);
        npt_encode_blob_array(enc, Name, _wstr_size);
    } else {
        npt_encode_array_count(enc, 0);
    }
}

static inline size_t
npt_sizeof_ID3DUserDefinedAnnotation_BeginEvent_reply(const WCHAR * Name)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip Name (input only) */
    return cmd_size;
}

static inline void
npt_decode_ID3DUserDefinedAnnotation_BeginEvent_reply(struct npt_cs_decoder *dec,
                                                      INT *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3DUserDefinedAnnotation,
                                                  NPT_METHOD_ID3DUserDefinedAnnotation_BeginEvent))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3DUserDefinedAnnotation_BeginEvent reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3DUserDefinedAnnotation,
                                       NPT_METHOD_ID3DUserDefinedAnnotation_BeginEvent));
        if (ret) *ret = (INT)0;
        return;
    }
    if (ret) *ret = (INT)_reply.cmd_return;
}

static inline void
npt_submit_ID3DUserDefinedAnnotation_BeginEvent(struct npt_ring *ring,
                                                uint32_t cmd_flags,
                                                npt_object_id object_id,
                                                const WCHAR * Name,
                                                struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3DUserDefinedAnnotation_BeginEvent(Name);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3DUserDefinedAnnotation_BeginEvent_reply(Name)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3DUserDefinedAnnotation_BeginEvent(enc, cmd_flags, object_id, Name);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3DUserDefinedAnnotation_BeginEvent(struct npt_ring *ring,
                                               npt_object_id object_id,
                                               const WCHAR * Name)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3DUserDefinedAnnotation_BeginEvent(ring, 0, object_id, Name, &submit);
}

static inline INT
npt_call_ID3DUserDefinedAnnotation_BeginEvent(struct npt_ring *ring,
                                              npt_object_id object_id,
                                              const WCHAR * Name)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3DUserDefinedAnnotation_BeginEvent(ring, NPT_CMD_FLAG_REPLY, object_id, Name, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        INT _ret;
        npt_decode_ID3DUserDefinedAnnotation_BeginEvent_reply(dec, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (INT)0;
    }
}

/*
 * ID3DUserDefinedAnnotation::EndEvent
 */

struct npt_command_ID3DUserDefinedAnnotation_EndEvent {
    void *_self;
    INT ret;
};

static inline size_t
npt_sizeof_ID3DUserDefinedAnnotation_EndEvent(void)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    return cmd_size;
}

static inline void
npt_encode_ID3DUserDefinedAnnotation_EndEvent(struct npt_cs_encoder *enc,
                                              uint32_t cmd_flags,
                                              npt_object_id object_id)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3DUserDefinedAnnotation_EndEvent();
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3DUserDefinedAnnotation,
                                 NPT_METHOD_ID3DUserDefinedAnnotation_EndEvent),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
}

static inline size_t
npt_sizeof_ID3DUserDefinedAnnotation_EndEvent_reply(void)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
    return cmd_size;
}

static inline void
npt_decode_ID3DUserDefinedAnnotation_EndEvent_reply(struct npt_cs_decoder *dec,
                                                    INT *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3DUserDefinedAnnotation,
                                                  NPT_METHOD_ID3DUserDefinedAnnotation_EndEvent))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3DUserDefinedAnnotation_EndEvent reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3DUserDefinedAnnotation,
                                       NPT_METHOD_ID3DUserDefinedAnnotation_EndEvent));
        if (ret) *ret = (INT)0;
        return;
    }
    if (ret) *ret = (INT)_reply.cmd_return;
}

static inline void
npt_submit_ID3DUserDefinedAnnotation_EndEvent(struct npt_ring *ring,
                                              uint32_t cmd_flags,
                                              npt_object_id object_id,
                                              struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3DUserDefinedAnnotation_EndEvent();
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3DUserDefinedAnnotation_EndEvent_reply()
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3DUserDefinedAnnotation_EndEvent(enc, cmd_flags, object_id);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3DUserDefinedAnnotation_EndEvent(struct npt_ring *ring,
                                             npt_object_id object_id)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3DUserDefinedAnnotation_EndEvent(ring, 0, object_id, &submit);
}

static inline INT
npt_call_ID3DUserDefinedAnnotation_EndEvent(struct npt_ring *ring,
                                            npt_object_id object_id)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3DUserDefinedAnnotation_EndEvent(ring, NPT_CMD_FLAG_REPLY, object_id, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        INT _ret;
        npt_decode_ID3DUserDefinedAnnotation_EndEvent_reply(dec, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (INT)0;
    }
}

/*
 * ID3DUserDefinedAnnotation::SetMarker
 */

struct npt_command_ID3DUserDefinedAnnotation_SetMarker {
    void *_self;
    const WCHAR * Name;
};

static inline size_t
npt_sizeof_ID3DUserDefinedAnnotation_SetMarker(const WCHAR * Name)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    if (Name) {
        const size_t _wstr_size = (npt_wcslen((const WCHAR *)Name) + 1) * sizeof(WCHAR);
        cmd_size += npt_sizeof_array_count(_wstr_size);
        cmd_size += npt_sizeof_blob_array(Name, _wstr_size);
    } else {
        cmd_size += npt_sizeof_array_count(0);
    }
    return cmd_size;
}

static inline void
npt_encode_ID3DUserDefinedAnnotation_SetMarker(struct npt_cs_encoder *enc,
                                               uint32_t cmd_flags,
                                               npt_object_id object_id,
                                               const WCHAR * Name)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3DUserDefinedAnnotation_SetMarker(Name);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3DUserDefinedAnnotation,
                                 NPT_METHOD_ID3DUserDefinedAnnotation_SetMarker),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    if (Name) {
        const size_t _wstr_size = (npt_wcslen((const WCHAR *)Name) + 1) * sizeof(WCHAR);
        npt_encode_array_count(enc, _wstr_size);
        npt_encode_blob_array(enc, Name, _wstr_size);
    } else {
        npt_encode_array_count(enc, 0);
    }
}

static inline size_t
npt_sizeof_ID3DUserDefinedAnnotation_SetMarker_reply(const WCHAR * Name)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip Name (input only) */
    return cmd_size;
}

static inline void
npt_submit_ID3DUserDefinedAnnotation_SetMarker(struct npt_ring *ring,
                                               uint32_t cmd_flags,
                                               npt_object_id object_id,
                                               const WCHAR * Name,
                                               struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3DUserDefinedAnnotation_SetMarker(Name);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3DUserDefinedAnnotation_SetMarker_reply(Name)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3DUserDefinedAnnotation_SetMarker(enc, cmd_flags, object_id, Name);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3DUserDefinedAnnotation_SetMarker(struct npt_ring *ring,
                                              npt_object_id object_id,
                                              const WCHAR * Name)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3DUserDefinedAnnotation_SetMarker(ring, 0, object_id, Name, &submit);
}

static inline void
npt_call_ID3DUserDefinedAnnotation_SetMarker(struct npt_ring *ring,
                                             npt_object_id object_id,
                                             const WCHAR * Name)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3DUserDefinedAnnotation_SetMarker(ring, NPT_CMD_FLAG_REPLY, object_id, Name, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        npt_ring_free_command_reply(ring, &submit);
    }
}

/*
 * ID3DUserDefinedAnnotation::GetStatus
 */

struct npt_command_ID3DUserDefinedAnnotation_GetStatus {
    void *_self;
    BOOL ret;
};

static inline size_t
npt_sizeof_ID3DUserDefinedAnnotation_GetStatus(void)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    return cmd_size;
}

static inline void
npt_encode_ID3DUserDefinedAnnotation_GetStatus(struct npt_cs_encoder *enc,
                                               uint32_t cmd_flags,
                                               npt_object_id object_id)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3DUserDefinedAnnotation_GetStatus();
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3DUserDefinedAnnotation,
                                 NPT_METHOD_ID3DUserDefinedAnnotation_GetStatus),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
}

static inline size_t
npt_sizeof_ID3DUserDefinedAnnotation_GetStatus_reply(void)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
    return cmd_size;
}

static inline void
npt_decode_ID3DUserDefinedAnnotation_GetStatus_reply(struct npt_cs_decoder *dec,
                                                     BOOL *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3DUserDefinedAnnotation,
                                                  NPT_METHOD_ID3DUserDefinedAnnotation_GetStatus))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3DUserDefinedAnnotation_GetStatus reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3DUserDefinedAnnotation,
                                       NPT_METHOD_ID3DUserDefinedAnnotation_GetStatus));
        if (ret) *ret = (BOOL)0;
        return;
    }
    if (ret) *ret = (BOOL)_reply.cmd_return;
}

static inline void
npt_submit_ID3DUserDefinedAnnotation_GetStatus(struct npt_ring *ring,
                                               uint32_t cmd_flags,
                                               npt_object_id object_id,
                                               struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3DUserDefinedAnnotation_GetStatus();
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3DUserDefinedAnnotation_GetStatus_reply()
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3DUserDefinedAnnotation_GetStatus(enc, cmd_flags, object_id);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3DUserDefinedAnnotation_GetStatus(struct npt_ring *ring,
                                              npt_object_id object_id)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3DUserDefinedAnnotation_GetStatus(ring, 0, object_id, &submit);
}

static inline BOOL
npt_call_ID3DUserDefinedAnnotation_GetStatus(struct npt_ring *ring,
                                             npt_object_id object_id)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3DUserDefinedAnnotation_GetStatus(ring, NPT_CMD_FLAG_REPLY, object_id, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        BOOL _ret;
        npt_decode_ID3DUserDefinedAnnotation_GetStatus_reply(dec, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (BOOL)0;
    }
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_GUEST_ID3DUSERDEFINEDANNOTATION_H */
