/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Client-side COM implementation for id3d11videodecoder: out-of-line default
 * thunks, default vtable populators, and default constructors for every
 * interface in this family.
 */

#include "npt_protocol_client_id3d11videodecoder.h"
#include "npt_com.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-variable"



/* ================================================================== */
/* ID3D11VideoDecoder                                                       */
/* ================================================================== */

/* Parent IID chain for QueryInterface fast-path.  NULL-terminated list of
 * IID pointers; QI returns self for any IID in this list. */
static const GUID *const npt_id3d11videodecoder_parent_iids[] = {
    &NPT_IID_IUnknown,
    &NPT_IID_ID3D11DeviceChild,
    &NPT_IID_ID3D11VideoDecoder,
    NULL,
};

HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11videodecoder_default_QueryInterface(void *self, REFIID riid, void **ppvObject)
{
    HRESULT hr = npt_com_default_query_interface_chain(
        self, riid, ppvObject, npt_id3d11videodecoder_parent_iids);
    if (hr == NPT_S_OK)
        return hr;
    /* Derived/sibling IIDs are resolved against the host object, one
     * wire round trip per (object, IID) lifetime: the runtime memoizes
     * the verdict and the wrapper on `self` (npt_com.c). */
    return npt_com_query_interface_host(self, riid, ppvObject);
}

ULONG NPT_STDMETHODCALLTYPE
npt_id3d11videodecoder_default_AddRef(void *self)
{
    return npt_com_default_addref(self);
}

ULONG NPT_STDMETHODCALLTYPE
npt_id3d11videodecoder_default_Release(void *self)
{
    return npt_com_default_release(self);
}

HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11videodecoder_default_GetCreationParameters(void *self, D3D11_VIDEO_DECODER_DESC * pVideoDesc, D3D11_VIDEO_DECODER_CONFIG * pConfig)
{
    HRESULT _ret = npt_call_ID3D11VideoDecoder_GetCreationParameters(npt_com_self_ring(self),npt_com_self_id(self),pVideoDesc,pConfig);
    return _ret;
}

HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11videodecoder_default_GetDriverHandle(void *self, HANDLE * pDriverHandle)
{
    HRESULT _ret = npt_call_ID3D11VideoDecoder_GetDriverHandle(npt_com_self_ring(self),npt_com_self_id(self),pDriverHandle);
    return _ret;
}


void
npt_id3d11videodecoder_fill_default_vtbl(struct npt_id3d11videodecoder_client_vtbl *dst)
{
    dst->QueryInterface = npt_id3d11videodecoder_default_QueryInterface;
    dst->AddRef         = npt_id3d11videodecoder_default_AddRef;
    dst->Release        = npt_id3d11videodecoder_default_Release;
    dst->GetDevice = npt_id3d11devicechild_default_GetDevice;
    dst->GetPrivateData = npt_id3d11devicechild_default_GetPrivateData;
    dst->SetPrivateData = npt_id3d11devicechild_default_SetPrivateData;
    dst->SetPrivateDataInterface = npt_id3d11devicechild_default_SetPrivateDataInterface;
    dst->GetCreationParameters = npt_id3d11videodecoder_default_GetCreationParameters;
    dst->GetDriverHandle = npt_id3d11videodecoder_default_GetDriverHandle;
}

/*
 * Per-interface default vtbl storage.  Populated by
 * npt_id3d11videodecoder_install_default_vtbl(), which is called once at
 * runtime init time from the global client_table init function.
 */
struct npt_id3d11videodecoder_client_vtbl npt_id3d11videodecoder_default_vtbl_storage;

void
npt_id3d11videodecoder_install_default_vtbl(void)
{
    npt_id3d11videodecoder_fill_default_vtbl(&npt_id3d11videodecoder_default_vtbl_storage);
}

void *
npt_id3d11videodecoder_client_create(struct npt_device *dev, uint64_t host_id)
{
    struct npt_com_base *p = (struct npt_com_base *)npt_alloc(sizeof(*p));
    if (!p)
        return NULL;
    npt_com_base_init(p,
        (const void **)&npt_id3d11videodecoder_default_vtbl_storage,
        dev, host_id);
    return p;
}


#pragma GCC diagnostic pop
