/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Client-side COM declarations for idxgiresource: per-interface vtable
 * structs, default thunk prototypes, default vtable populators, and default
 * constructors.
 *
 * The thunk bodies, populators, and constructors live in the matching .c
 * file.  This split keeps the headers small and prevents N copies of the
 * thunk code from landing in every TU that pulls in this family.
 */

#ifndef NPT_PROTOCOL_CLIENT_IDXGIRESOURCE_H
#define NPT_PROTOCOL_CLIENT_IDXGIRESOURCE_H

#include "npt_protocol_guest_idxgiresource.h"
#include "npt_protocol_client_idxgidevicesubobject.h"

/* Forward-declare struct npt_device so the client_create prototypes don't
 * trigger the "declared inside parameter list" warning.  The full
 * definition lives in the consumer's npt_device.h, which the .c file pulls
 * in via npt_com.h. */
struct npt_device;

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"



/* ================================================================== */
/* IDXGIResource                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * IDXGIResourceVtbl, by construction.
 */
struct npt_idxgiresource_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: IDXGIObject::SetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateData)(void *self, const GUID * Name, UINT DataSize, const void * pData);
    /* slot 4: IDXGIObject::SetPrivateDataInterface */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateDataInterface)(void *self, const GUID * Name, const IUnknown * pUnknown);
    /* slot 5: IDXGIObject::GetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *GetPrivateData)(void *self, const GUID * Name, UINT * pDataSize, void * pData);
    /* slot 6: IDXGIObject::GetParent */
    HRESULT (NPT_STDMETHODCALLTYPE *GetParent)(void *self, const IID * riid, void ** ppParent);
    /* slot 7: IDXGIDeviceSubObject::GetDevice */
    HRESULT (NPT_STDMETHODCALLTYPE *GetDevice)(void *self, const IID * riid, void ** ppDevice);
    /* slot 8: IDXGIResource::GetSharedHandle */
    HRESULT (NPT_STDMETHODCALLTYPE *GetSharedHandle)(void *self, HANDLE * pSharedHandle);
    /* slot 9: IDXGIResource::GetUsage */
    HRESULT (NPT_STDMETHODCALLTYPE *GetUsage)(void *self, DXGI_USAGE * pUsage);
    /* slot 10: IDXGIResource::SetEvictionPriority */
    HRESULT (NPT_STDMETHODCALLTYPE *SetEvictionPriority)(void *self, UINT EvictionPriority);
    /* slot 11: IDXGIResource::GetEvictionPriority */
    HRESULT (NPT_STDMETHODCALLTYPE *GetEvictionPriority)(void *self, UINT * pEvictionPriority);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgiresource_default_GetSharedHandle(void *self, HANDLE * pSharedHandle);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgiresource_default_GetUsage(void *self, DXGI_USAGE * pUsage);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgiresource_default_SetEvictionPriority(void *self, UINT EvictionPriority);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgiresource_default_GetEvictionPriority(void *self, UINT * pEvictionPriority);

/* Default IUnknown thunks for IDXGIResource.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgiresource_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgiresource_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgiresource_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_idxgiresource_fill_default_vtbl(struct npt_idxgiresource_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_idxgiresource_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_idxgiresource_client_vtbl npt_idxgiresource_default_vtbl_storage;
extern void
npt_idxgiresource_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_idxgiresource_client_create(struct npt_device *dev, uint64_t host_id);


/* ================================================================== */
/* IDXGIResource1                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * IDXGIResource1Vtbl, by construction.
 */
struct npt_idxgiresource1_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: IDXGIObject::SetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateData)(void *self, const GUID * Name, UINT DataSize, const void * pData);
    /* slot 4: IDXGIObject::SetPrivateDataInterface */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateDataInterface)(void *self, const GUID * Name, const IUnknown * pUnknown);
    /* slot 5: IDXGIObject::GetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *GetPrivateData)(void *self, const GUID * Name, UINT * pDataSize, void * pData);
    /* slot 6: IDXGIObject::GetParent */
    HRESULT (NPT_STDMETHODCALLTYPE *GetParent)(void *self, const IID * riid, void ** ppParent);
    /* slot 7: IDXGIDeviceSubObject::GetDevice */
    HRESULT (NPT_STDMETHODCALLTYPE *GetDevice)(void *self, const IID * riid, void ** ppDevice);
    /* slot 8: IDXGIResource::GetSharedHandle */
    HRESULT (NPT_STDMETHODCALLTYPE *GetSharedHandle)(void *self, HANDLE * pSharedHandle);
    /* slot 9: IDXGIResource::GetUsage */
    HRESULT (NPT_STDMETHODCALLTYPE *GetUsage)(void *self, DXGI_USAGE * pUsage);
    /* slot 10: IDXGIResource::SetEvictionPriority */
    HRESULT (NPT_STDMETHODCALLTYPE *SetEvictionPriority)(void *self, UINT EvictionPriority);
    /* slot 11: IDXGIResource::GetEvictionPriority */
    HRESULT (NPT_STDMETHODCALLTYPE *GetEvictionPriority)(void *self, UINT * pEvictionPriority);
    /* slot 12: IDXGIResource1::CreateSubresourceSurface */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSubresourceSurface)(void *self, UINT index, IDXGISurface2 ** ppSurface);
    /* slot 13: IDXGIResource1::CreateSharedHandle */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSharedHandle)(void *self, const SECURITY_ATTRIBUTES * pAttributes, DWORD dwAccess, const WCHAR * lpName, HANDLE * pHandle);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgiresource1_default_CreateSubresourceSurface(void *self, UINT index, IDXGISurface2 ** ppSurface);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgiresource1_default_CreateSharedHandle(void *self, const SECURITY_ATTRIBUTES * pAttributes, DWORD dwAccess, const WCHAR * lpName, HANDLE * pHandle);

/* Default IUnknown thunks for IDXGIResource1.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgiresource1_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgiresource1_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgiresource1_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_idxgiresource1_fill_default_vtbl(struct npt_idxgiresource1_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_idxgiresource1_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_idxgiresource1_client_vtbl npt_idxgiresource1_default_vtbl_storage;
extern void
npt_idxgiresource1_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_idxgiresource1_client_create(struct npt_device *dev, uint64_t host_id);


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_CLIENT_IDXGIRESOURCE_H */
