/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Client-side COM declarations for id3d11device: per-interface vtable
 * structs, default thunk prototypes, default vtable populators, and default
 * constructors.
 *
 * The thunk bodies, populators, and constructors live in the matching .c
 * file.  This split keeps the headers small and prevents N copies of the
 * thunk code from landing in every TU that pulls in this family.
 */

#ifndef NPT_PROTOCOL_CLIENT_ID3D11DEVICE_H
#define NPT_PROTOCOL_CLIENT_ID3D11DEVICE_H

#include "npt_protocol_guest_id3d11device.h"

/* Forward-declare struct npt_device so the client_create prototypes don't
 * trigger the "declared inside parameter list" warning.  The full
 * definition lives in the consumer's npt_device.h, which the .c file pulls
 * in via npt_com.h. */
struct npt_device;

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"



/* ================================================================== */
/* ID3D11Device                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * ID3D11DeviceVtbl, by construction.
 */
struct npt_id3d11device_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: ID3D11Device::CreateBuffer */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateBuffer)(void *self, const D3D11_BUFFER_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Buffer ** ppBuffer);
    /* slot 4: ID3D11Device::CreateTexture1D */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture1D)(void *self, const D3D11_TEXTURE1D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture1D ** ppTexture1D);
    /* slot 5: ID3D11Device::CreateTexture2D */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture2D)(void *self, const D3D11_TEXTURE2D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture2D ** ppTexture2D);
    /* slot 6: ID3D11Device::CreateTexture3D */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture3D)(void *self, const D3D11_TEXTURE3D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture3D ** ppTexture3D);
    /* slot 7: ID3D11Device::CreateShaderResourceView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateShaderResourceView)(void *self, ID3D11Resource * pResource, const D3D11_SHADER_RESOURCE_VIEW_DESC * pDesc, ID3D11ShaderResourceView ** ppSRView);
    /* slot 8: ID3D11Device::CreateUnorderedAccessView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateUnorderedAccessView)(void *self, ID3D11Resource * pResource, const D3D11_UNORDERED_ACCESS_VIEW_DESC * pDesc, ID3D11UnorderedAccessView ** ppUAView);
    /* slot 9: ID3D11Device::CreateRenderTargetView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRenderTargetView)(void *self, ID3D11Resource * pResource, const D3D11_RENDER_TARGET_VIEW_DESC * pDesc, ID3D11RenderTargetView ** ppRTView);
    /* slot 10: ID3D11Device::CreateDepthStencilView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDepthStencilView)(void *self, ID3D11Resource * pResource, const D3D11_DEPTH_STENCIL_VIEW_DESC * pDesc, ID3D11DepthStencilView ** ppDepthStencilView);
    /* slot 11: ID3D11Device::CreateInputLayout */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateInputLayout)(void *self, const D3D11_INPUT_ELEMENT_DESC * pInputElementDescs, UINT NumElements, const void * pShaderBytecodeWithInputSignature, SIZE_T BytecodeLength, ID3D11InputLayout ** ppInputLayout);
    /* slot 12: ID3D11Device::CreateVertexShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateVertexShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11VertexShader ** ppVertexShader);
    /* slot 13: ID3D11Device::CreateGeometryShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateGeometryShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11GeometryShader ** ppGeometryShader);
    /* slot 14: ID3D11Device::CreateGeometryShaderWithStreamOutput */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateGeometryShaderWithStreamOutput)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, const D3D11_SO_DECLARATION_ENTRY * pSODeclaration, UINT NumEntries, const UINT * pBufferStrides, UINT NumStrides, UINT RasterizedStream, ID3D11ClassLinkage * pClassLinkage, ID3D11GeometryShader ** ppGeometryShader);
    /* slot 15: ID3D11Device::CreatePixelShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreatePixelShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11PixelShader ** ppPixelShader);
    /* slot 16: ID3D11Device::CreateHullShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateHullShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11HullShader ** ppHullShader);
    /* slot 17: ID3D11Device::CreateDomainShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDomainShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11DomainShader ** ppDomainShader);
    /* slot 18: ID3D11Device::CreateComputeShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateComputeShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11ComputeShader ** ppComputeShader);
    /* slot 19: ID3D11Device::CreateClassLinkage */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateClassLinkage)(void *self, ID3D11ClassLinkage ** ppLinkage);
    /* slot 20: ID3D11Device::CreateBlendState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateBlendState)(void *self, const D3D11_BLEND_DESC * pBlendStateDesc, ID3D11BlendState ** ppBlendState);
    /* slot 21: ID3D11Device::CreateDepthStencilState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDepthStencilState)(void *self, const D3D11_DEPTH_STENCIL_DESC * pDepthStencilDesc, ID3D11DepthStencilState ** ppDepthStencilState);
    /* slot 22: ID3D11Device::CreateRasterizerState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRasterizerState)(void *self, const D3D11_RASTERIZER_DESC * pRasterizerDesc, ID3D11RasterizerState ** ppRasterizerState);
    /* slot 23: ID3D11Device::CreateSamplerState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSamplerState)(void *self, const D3D11_SAMPLER_DESC * pSamplerDesc, ID3D11SamplerState ** ppSamplerState);
    /* slot 24: ID3D11Device::CreateQuery */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateQuery)(void *self, const D3D11_QUERY_DESC * pQueryDesc, ID3D11Query ** ppQuery);
    /* slot 25: ID3D11Device::CreatePredicate */
    HRESULT (NPT_STDMETHODCALLTYPE *CreatePredicate)(void *self, const D3D11_QUERY_DESC * pPredicateDesc, ID3D11Predicate ** ppPredicate);
    /* slot 26: ID3D11Device::CreateCounter */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateCounter)(void *self, const D3D11_COUNTER_DESC * pCounterDesc, ID3D11Counter ** ppCounter);
    /* slot 27: ID3D11Device::CreateDeferredContext */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeferredContext)(void *self, UINT ContextFlags, ID3D11DeviceContext ** ppDeferredContext);
    /* slot 28: ID3D11Device::OpenSharedResource */
    HRESULT (NPT_STDMETHODCALLTYPE *OpenSharedResource)(void *self, HANDLE hResource, const IID * ReturnedInterface, void ** ppResource);
    /* slot 29: ID3D11Device::CheckFormatSupport */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckFormatSupport)(void *self, DXGI_FORMAT Format, UINT * pFormatSupport);
    /* slot 30: ID3D11Device::CheckMultisampleQualityLevels */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckMultisampleQualityLevels)(void *self, DXGI_FORMAT Format, UINT SampleCount, UINT * pNumQualityLevels);
    /* slot 31: ID3D11Device::CheckCounterInfo */
    void (NPT_STDMETHODCALLTYPE *CheckCounterInfo)(void *self, D3D11_COUNTER_INFO * pCounterInfo);
    /* slot 32: ID3D11Device::CheckCounter */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckCounter)(void *self, const D3D11_COUNTER_DESC * pDesc, D3D11_COUNTER_TYPE * pType, UINT * pActiveCounters, CHAR * szName, UINT * pNameLength, CHAR * szUnits, UINT * pUnitsLength, CHAR * szDescription, UINT * pDescriptionLength);
    /* slot 33: ID3D11Device::CheckFeatureSupport */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckFeatureSupport)(void *self, D3D11_FEATURE Feature, void * pFeatureSupportData, UINT FeatureSupportDataSize);
    /* slot 34: ID3D11Device::GetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *GetPrivateData)(void *self, const GUID * guid, UINT * pDataSize, void * pData);
    /* slot 35: ID3D11Device::SetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateData)(void *self, const GUID * guid, UINT DataSize, const void * pData);
    /* slot 36: ID3D11Device::SetPrivateDataInterface */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateDataInterface)(void *self, const GUID * guid, const IUnknown * pData);
    /* slot 37: ID3D11Device::GetFeatureLevel */
    D3D_FEATURE_LEVEL (NPT_STDMETHODCALLTYPE *GetFeatureLevel)(void *self);
    /* slot 38: ID3D11Device::GetCreationFlags */
    UINT (NPT_STDMETHODCALLTYPE *GetCreationFlags)(void *self);
    /* slot 39: ID3D11Device::GetDeviceRemovedReason */
    HRESULT (NPT_STDMETHODCALLTYPE *GetDeviceRemovedReason)(void *self);
    /* slot 40: ID3D11Device::GetImmediateContext */
    void (NPT_STDMETHODCALLTYPE *GetImmediateContext)(void *self, ID3D11DeviceContext ** ppImmediateContext);
    /* slot 41: ID3D11Device::SetExceptionMode */
    HRESULT (NPT_STDMETHODCALLTYPE *SetExceptionMode)(void *self, UINT RaiseFlags);
    /* slot 42: ID3D11Device::GetExceptionMode */
    UINT (NPT_STDMETHODCALLTYPE *GetExceptionMode)(void *self);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateBuffer(void *self, const D3D11_BUFFER_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Buffer ** ppBuffer);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateTexture1D(void *self, const D3D11_TEXTURE1D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture1D ** ppTexture1D);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateTexture2D(void *self, const D3D11_TEXTURE2D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture2D ** ppTexture2D);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateTexture3D(void *self, const D3D11_TEXTURE3D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture3D ** ppTexture3D);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateShaderResourceView(void *self, ID3D11Resource * pResource, const D3D11_SHADER_RESOURCE_VIEW_DESC * pDesc, ID3D11ShaderResourceView ** ppSRView);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateUnorderedAccessView(void *self, ID3D11Resource * pResource, const D3D11_UNORDERED_ACCESS_VIEW_DESC * pDesc, ID3D11UnorderedAccessView ** ppUAView);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateRenderTargetView(void *self, ID3D11Resource * pResource, const D3D11_RENDER_TARGET_VIEW_DESC * pDesc, ID3D11RenderTargetView ** ppRTView);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateDepthStencilView(void *self, ID3D11Resource * pResource, const D3D11_DEPTH_STENCIL_VIEW_DESC * pDesc, ID3D11DepthStencilView ** ppDepthStencilView);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateInputLayout(void *self, const D3D11_INPUT_ELEMENT_DESC * pInputElementDescs, UINT NumElements, const void * pShaderBytecodeWithInputSignature, SIZE_T BytecodeLength, ID3D11InputLayout ** ppInputLayout);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateVertexShader(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11VertexShader ** ppVertexShader);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateGeometryShader(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11GeometryShader ** ppGeometryShader);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateGeometryShaderWithStreamOutput(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, const D3D11_SO_DECLARATION_ENTRY * pSODeclaration, UINT NumEntries, const UINT * pBufferStrides, UINT NumStrides, UINT RasterizedStream, ID3D11ClassLinkage * pClassLinkage, ID3D11GeometryShader ** ppGeometryShader);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreatePixelShader(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11PixelShader ** ppPixelShader);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateHullShader(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11HullShader ** ppHullShader);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateDomainShader(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11DomainShader ** ppDomainShader);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateComputeShader(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11ComputeShader ** ppComputeShader);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateClassLinkage(void *self, ID3D11ClassLinkage ** ppLinkage);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateBlendState(void *self, const D3D11_BLEND_DESC * pBlendStateDesc, ID3D11BlendState ** ppBlendState);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateDepthStencilState(void *self, const D3D11_DEPTH_STENCIL_DESC * pDepthStencilDesc, ID3D11DepthStencilState ** ppDepthStencilState);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateRasterizerState(void *self, const D3D11_RASTERIZER_DESC * pRasterizerDesc, ID3D11RasterizerState ** ppRasterizerState);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateSamplerState(void *self, const D3D11_SAMPLER_DESC * pSamplerDesc, ID3D11SamplerState ** ppSamplerState);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateQuery(void *self, const D3D11_QUERY_DESC * pQueryDesc, ID3D11Query ** ppQuery);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreatePredicate(void *self, const D3D11_QUERY_DESC * pPredicateDesc, ID3D11Predicate ** ppPredicate);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateCounter(void *self, const D3D11_COUNTER_DESC * pCounterDesc, ID3D11Counter ** ppCounter);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CreateDeferredContext(void *self, UINT ContextFlags, ID3D11DeviceContext ** ppDeferredContext);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_OpenSharedResource(void *self, HANDLE hResource, const IID * ReturnedInterface, void ** ppResource);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CheckFormatSupport(void *self, DXGI_FORMAT Format, UINT * pFormatSupport);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CheckMultisampleQualityLevels(void *self, DXGI_FORMAT Format, UINT SampleCount, UINT * pNumQualityLevels);
extern void NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CheckCounterInfo(void *self, D3D11_COUNTER_INFO * pCounterInfo);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CheckCounter(void *self, const D3D11_COUNTER_DESC * pDesc, D3D11_COUNTER_TYPE * pType, UINT * pActiveCounters, CHAR * szName, UINT * pNameLength, CHAR * szUnits, UINT * pUnitsLength, CHAR * szDescription, UINT * pDescriptionLength);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_CheckFeatureSupport(void *self, D3D11_FEATURE Feature, void * pFeatureSupportData, UINT FeatureSupportDataSize);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_GetPrivateData(void *self, const GUID * guid, UINT * pDataSize, void * pData);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_SetPrivateData(void *self, const GUID * guid, UINT DataSize, const void * pData);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_SetPrivateDataInterface(void *self, const GUID * guid, const IUnknown * pData);
extern D3D_FEATURE_LEVEL NPT_STDMETHODCALLTYPE
npt_id3d11device_default_GetFeatureLevel(void *self);
extern UINT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_GetCreationFlags(void *self);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_GetDeviceRemovedReason(void *self);
extern void NPT_STDMETHODCALLTYPE
npt_id3d11device_default_GetImmediateContext(void *self, ID3D11DeviceContext ** ppImmediateContext);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_SetExceptionMode(void *self, UINT RaiseFlags);
extern UINT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_GetExceptionMode(void *self);

/* Default IUnknown thunks for ID3D11Device.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_id3d11device_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_id3d11device_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_id3d11device_fill_default_vtbl(struct npt_id3d11device_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_id3d11device_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_id3d11device_client_vtbl npt_id3d11device_default_vtbl_storage;
extern void
npt_id3d11device_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_id3d11device_client_create(struct npt_device *dev, uint64_t host_id);


/* ================================================================== */
/* ID3D11Device1                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * ID3D11Device1Vtbl, by construction.
 */
struct npt_id3d11device1_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: ID3D11Device::CreateBuffer */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateBuffer)(void *self, const D3D11_BUFFER_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Buffer ** ppBuffer);
    /* slot 4: ID3D11Device::CreateTexture1D */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture1D)(void *self, const D3D11_TEXTURE1D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture1D ** ppTexture1D);
    /* slot 5: ID3D11Device::CreateTexture2D */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture2D)(void *self, const D3D11_TEXTURE2D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture2D ** ppTexture2D);
    /* slot 6: ID3D11Device::CreateTexture3D */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture3D)(void *self, const D3D11_TEXTURE3D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture3D ** ppTexture3D);
    /* slot 7: ID3D11Device::CreateShaderResourceView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateShaderResourceView)(void *self, ID3D11Resource * pResource, const D3D11_SHADER_RESOURCE_VIEW_DESC * pDesc, ID3D11ShaderResourceView ** ppSRView);
    /* slot 8: ID3D11Device::CreateUnorderedAccessView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateUnorderedAccessView)(void *self, ID3D11Resource * pResource, const D3D11_UNORDERED_ACCESS_VIEW_DESC * pDesc, ID3D11UnorderedAccessView ** ppUAView);
    /* slot 9: ID3D11Device::CreateRenderTargetView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRenderTargetView)(void *self, ID3D11Resource * pResource, const D3D11_RENDER_TARGET_VIEW_DESC * pDesc, ID3D11RenderTargetView ** ppRTView);
    /* slot 10: ID3D11Device::CreateDepthStencilView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDepthStencilView)(void *self, ID3D11Resource * pResource, const D3D11_DEPTH_STENCIL_VIEW_DESC * pDesc, ID3D11DepthStencilView ** ppDepthStencilView);
    /* slot 11: ID3D11Device::CreateInputLayout */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateInputLayout)(void *self, const D3D11_INPUT_ELEMENT_DESC * pInputElementDescs, UINT NumElements, const void * pShaderBytecodeWithInputSignature, SIZE_T BytecodeLength, ID3D11InputLayout ** ppInputLayout);
    /* slot 12: ID3D11Device::CreateVertexShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateVertexShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11VertexShader ** ppVertexShader);
    /* slot 13: ID3D11Device::CreateGeometryShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateGeometryShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11GeometryShader ** ppGeometryShader);
    /* slot 14: ID3D11Device::CreateGeometryShaderWithStreamOutput */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateGeometryShaderWithStreamOutput)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, const D3D11_SO_DECLARATION_ENTRY * pSODeclaration, UINT NumEntries, const UINT * pBufferStrides, UINT NumStrides, UINT RasterizedStream, ID3D11ClassLinkage * pClassLinkage, ID3D11GeometryShader ** ppGeometryShader);
    /* slot 15: ID3D11Device::CreatePixelShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreatePixelShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11PixelShader ** ppPixelShader);
    /* slot 16: ID3D11Device::CreateHullShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateHullShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11HullShader ** ppHullShader);
    /* slot 17: ID3D11Device::CreateDomainShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDomainShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11DomainShader ** ppDomainShader);
    /* slot 18: ID3D11Device::CreateComputeShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateComputeShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11ComputeShader ** ppComputeShader);
    /* slot 19: ID3D11Device::CreateClassLinkage */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateClassLinkage)(void *self, ID3D11ClassLinkage ** ppLinkage);
    /* slot 20: ID3D11Device::CreateBlendState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateBlendState)(void *self, const D3D11_BLEND_DESC * pBlendStateDesc, ID3D11BlendState ** ppBlendState);
    /* slot 21: ID3D11Device::CreateDepthStencilState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDepthStencilState)(void *self, const D3D11_DEPTH_STENCIL_DESC * pDepthStencilDesc, ID3D11DepthStencilState ** ppDepthStencilState);
    /* slot 22: ID3D11Device::CreateRasterizerState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRasterizerState)(void *self, const D3D11_RASTERIZER_DESC * pRasterizerDesc, ID3D11RasterizerState ** ppRasterizerState);
    /* slot 23: ID3D11Device::CreateSamplerState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSamplerState)(void *self, const D3D11_SAMPLER_DESC * pSamplerDesc, ID3D11SamplerState ** ppSamplerState);
    /* slot 24: ID3D11Device::CreateQuery */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateQuery)(void *self, const D3D11_QUERY_DESC * pQueryDesc, ID3D11Query ** ppQuery);
    /* slot 25: ID3D11Device::CreatePredicate */
    HRESULT (NPT_STDMETHODCALLTYPE *CreatePredicate)(void *self, const D3D11_QUERY_DESC * pPredicateDesc, ID3D11Predicate ** ppPredicate);
    /* slot 26: ID3D11Device::CreateCounter */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateCounter)(void *self, const D3D11_COUNTER_DESC * pCounterDesc, ID3D11Counter ** ppCounter);
    /* slot 27: ID3D11Device::CreateDeferredContext */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeferredContext)(void *self, UINT ContextFlags, ID3D11DeviceContext ** ppDeferredContext);
    /* slot 28: ID3D11Device::OpenSharedResource */
    HRESULT (NPT_STDMETHODCALLTYPE *OpenSharedResource)(void *self, HANDLE hResource, const IID * ReturnedInterface, void ** ppResource);
    /* slot 29: ID3D11Device::CheckFormatSupport */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckFormatSupport)(void *self, DXGI_FORMAT Format, UINT * pFormatSupport);
    /* slot 30: ID3D11Device::CheckMultisampleQualityLevels */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckMultisampleQualityLevels)(void *self, DXGI_FORMAT Format, UINT SampleCount, UINT * pNumQualityLevels);
    /* slot 31: ID3D11Device::CheckCounterInfo */
    void (NPT_STDMETHODCALLTYPE *CheckCounterInfo)(void *self, D3D11_COUNTER_INFO * pCounterInfo);
    /* slot 32: ID3D11Device::CheckCounter */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckCounter)(void *self, const D3D11_COUNTER_DESC * pDesc, D3D11_COUNTER_TYPE * pType, UINT * pActiveCounters, CHAR * szName, UINT * pNameLength, CHAR * szUnits, UINT * pUnitsLength, CHAR * szDescription, UINT * pDescriptionLength);
    /* slot 33: ID3D11Device::CheckFeatureSupport */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckFeatureSupport)(void *self, D3D11_FEATURE Feature, void * pFeatureSupportData, UINT FeatureSupportDataSize);
    /* slot 34: ID3D11Device::GetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *GetPrivateData)(void *self, const GUID * guid, UINT * pDataSize, void * pData);
    /* slot 35: ID3D11Device::SetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateData)(void *self, const GUID * guid, UINT DataSize, const void * pData);
    /* slot 36: ID3D11Device::SetPrivateDataInterface */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateDataInterface)(void *self, const GUID * guid, const IUnknown * pData);
    /* slot 37: ID3D11Device::GetFeatureLevel */
    D3D_FEATURE_LEVEL (NPT_STDMETHODCALLTYPE *GetFeatureLevel)(void *self);
    /* slot 38: ID3D11Device::GetCreationFlags */
    UINT (NPT_STDMETHODCALLTYPE *GetCreationFlags)(void *self);
    /* slot 39: ID3D11Device::GetDeviceRemovedReason */
    HRESULT (NPT_STDMETHODCALLTYPE *GetDeviceRemovedReason)(void *self);
    /* slot 40: ID3D11Device::GetImmediateContext */
    void (NPT_STDMETHODCALLTYPE *GetImmediateContext)(void *self, ID3D11DeviceContext ** ppImmediateContext);
    /* slot 41: ID3D11Device::SetExceptionMode */
    HRESULT (NPT_STDMETHODCALLTYPE *SetExceptionMode)(void *self, UINT RaiseFlags);
    /* slot 42: ID3D11Device::GetExceptionMode */
    UINT (NPT_STDMETHODCALLTYPE *GetExceptionMode)(void *self);
    /* slot 43: ID3D11Device1::GetImmediateContext1 */
    void (NPT_STDMETHODCALLTYPE *GetImmediateContext1)(void *self, ID3D11DeviceContext1 ** ppImmediateContext);
    /* slot 44: ID3D11Device1::CreateDeferredContext1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeferredContext1)(void *self, UINT ContextFlags, ID3D11DeviceContext1 ** ppDeferredContext);
    /* slot 45: ID3D11Device1::CreateBlendState1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateBlendState1)(void *self, const D3D11_BLEND_DESC1 * pBlendStateDesc, ID3D11BlendState1 ** ppBlendState);
    /* slot 46: ID3D11Device1::CreateRasterizerState1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRasterizerState1)(void *self, const D3D11_RASTERIZER_DESC1 * pRasterizerDesc, ID3D11RasterizerState1 ** ppRasterizerState);
    /* slot 47: ID3D11Device1::CreateDeviceContextState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeviceContextState)(void *self, UINT Flags, const D3D_FEATURE_LEVEL * pFeatureLevels, UINT FeatureLevels, UINT SDKVersion, const IID * EmulatedInterface, D3D_FEATURE_LEVEL * pChosenFeatureLevel, ID3DDeviceContextState ** ppContextState);
    /* slot 48: ID3D11Device1::OpenSharedResource1 */
    HRESULT (NPT_STDMETHODCALLTYPE *OpenSharedResource1)(void *self, HANDLE hResource, const IID * returnedInterface, void ** ppResource);
    /* slot 49: ID3D11Device1::OpenSharedResourceByName */
    HRESULT (NPT_STDMETHODCALLTYPE *OpenSharedResourceByName)(void *self, const WCHAR * lpName, DWORD dwDesiredAccess, const IID * returnedInterface, void ** ppResource);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern void NPT_STDMETHODCALLTYPE
npt_id3d11device1_default_GetImmediateContext1(void *self, ID3D11DeviceContext1 ** ppImmediateContext);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device1_default_CreateDeferredContext1(void *self, UINT ContextFlags, ID3D11DeviceContext1 ** ppDeferredContext);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device1_default_CreateBlendState1(void *self, const D3D11_BLEND_DESC1 * pBlendStateDesc, ID3D11BlendState1 ** ppBlendState);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device1_default_CreateRasterizerState1(void *self, const D3D11_RASTERIZER_DESC1 * pRasterizerDesc, ID3D11RasterizerState1 ** ppRasterizerState);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device1_default_CreateDeviceContextState(void *self, UINT Flags, const D3D_FEATURE_LEVEL * pFeatureLevels, UINT FeatureLevels, UINT SDKVersion, const IID * EmulatedInterface, D3D_FEATURE_LEVEL * pChosenFeatureLevel, ID3DDeviceContextState ** ppContextState);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device1_default_OpenSharedResource1(void *self, HANDLE hResource, const IID * returnedInterface, void ** ppResource);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device1_default_OpenSharedResourceByName(void *self, const WCHAR * lpName, DWORD dwDesiredAccess, const IID * returnedInterface, void ** ppResource);

/* Default IUnknown thunks for ID3D11Device1.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device1_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_id3d11device1_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_id3d11device1_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_id3d11device1_fill_default_vtbl(struct npt_id3d11device1_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_id3d11device1_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_id3d11device1_client_vtbl npt_id3d11device1_default_vtbl_storage;
extern void
npt_id3d11device1_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_id3d11device1_client_create(struct npt_device *dev, uint64_t host_id);


/* ================================================================== */
/* ID3D11Device2                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * ID3D11Device2Vtbl, by construction.
 */
struct npt_id3d11device2_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: ID3D11Device::CreateBuffer */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateBuffer)(void *self, const D3D11_BUFFER_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Buffer ** ppBuffer);
    /* slot 4: ID3D11Device::CreateTexture1D */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture1D)(void *self, const D3D11_TEXTURE1D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture1D ** ppTexture1D);
    /* slot 5: ID3D11Device::CreateTexture2D */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture2D)(void *self, const D3D11_TEXTURE2D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture2D ** ppTexture2D);
    /* slot 6: ID3D11Device::CreateTexture3D */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture3D)(void *self, const D3D11_TEXTURE3D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture3D ** ppTexture3D);
    /* slot 7: ID3D11Device::CreateShaderResourceView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateShaderResourceView)(void *self, ID3D11Resource * pResource, const D3D11_SHADER_RESOURCE_VIEW_DESC * pDesc, ID3D11ShaderResourceView ** ppSRView);
    /* slot 8: ID3D11Device::CreateUnorderedAccessView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateUnorderedAccessView)(void *self, ID3D11Resource * pResource, const D3D11_UNORDERED_ACCESS_VIEW_DESC * pDesc, ID3D11UnorderedAccessView ** ppUAView);
    /* slot 9: ID3D11Device::CreateRenderTargetView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRenderTargetView)(void *self, ID3D11Resource * pResource, const D3D11_RENDER_TARGET_VIEW_DESC * pDesc, ID3D11RenderTargetView ** ppRTView);
    /* slot 10: ID3D11Device::CreateDepthStencilView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDepthStencilView)(void *self, ID3D11Resource * pResource, const D3D11_DEPTH_STENCIL_VIEW_DESC * pDesc, ID3D11DepthStencilView ** ppDepthStencilView);
    /* slot 11: ID3D11Device::CreateInputLayout */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateInputLayout)(void *self, const D3D11_INPUT_ELEMENT_DESC * pInputElementDescs, UINT NumElements, const void * pShaderBytecodeWithInputSignature, SIZE_T BytecodeLength, ID3D11InputLayout ** ppInputLayout);
    /* slot 12: ID3D11Device::CreateVertexShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateVertexShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11VertexShader ** ppVertexShader);
    /* slot 13: ID3D11Device::CreateGeometryShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateGeometryShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11GeometryShader ** ppGeometryShader);
    /* slot 14: ID3D11Device::CreateGeometryShaderWithStreamOutput */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateGeometryShaderWithStreamOutput)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, const D3D11_SO_DECLARATION_ENTRY * pSODeclaration, UINT NumEntries, const UINT * pBufferStrides, UINT NumStrides, UINT RasterizedStream, ID3D11ClassLinkage * pClassLinkage, ID3D11GeometryShader ** ppGeometryShader);
    /* slot 15: ID3D11Device::CreatePixelShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreatePixelShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11PixelShader ** ppPixelShader);
    /* slot 16: ID3D11Device::CreateHullShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateHullShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11HullShader ** ppHullShader);
    /* slot 17: ID3D11Device::CreateDomainShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDomainShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11DomainShader ** ppDomainShader);
    /* slot 18: ID3D11Device::CreateComputeShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateComputeShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11ComputeShader ** ppComputeShader);
    /* slot 19: ID3D11Device::CreateClassLinkage */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateClassLinkage)(void *self, ID3D11ClassLinkage ** ppLinkage);
    /* slot 20: ID3D11Device::CreateBlendState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateBlendState)(void *self, const D3D11_BLEND_DESC * pBlendStateDesc, ID3D11BlendState ** ppBlendState);
    /* slot 21: ID3D11Device::CreateDepthStencilState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDepthStencilState)(void *self, const D3D11_DEPTH_STENCIL_DESC * pDepthStencilDesc, ID3D11DepthStencilState ** ppDepthStencilState);
    /* slot 22: ID3D11Device::CreateRasterizerState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRasterizerState)(void *self, const D3D11_RASTERIZER_DESC * pRasterizerDesc, ID3D11RasterizerState ** ppRasterizerState);
    /* slot 23: ID3D11Device::CreateSamplerState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSamplerState)(void *self, const D3D11_SAMPLER_DESC * pSamplerDesc, ID3D11SamplerState ** ppSamplerState);
    /* slot 24: ID3D11Device::CreateQuery */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateQuery)(void *self, const D3D11_QUERY_DESC * pQueryDesc, ID3D11Query ** ppQuery);
    /* slot 25: ID3D11Device::CreatePredicate */
    HRESULT (NPT_STDMETHODCALLTYPE *CreatePredicate)(void *self, const D3D11_QUERY_DESC * pPredicateDesc, ID3D11Predicate ** ppPredicate);
    /* slot 26: ID3D11Device::CreateCounter */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateCounter)(void *self, const D3D11_COUNTER_DESC * pCounterDesc, ID3D11Counter ** ppCounter);
    /* slot 27: ID3D11Device::CreateDeferredContext */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeferredContext)(void *self, UINT ContextFlags, ID3D11DeviceContext ** ppDeferredContext);
    /* slot 28: ID3D11Device::OpenSharedResource */
    HRESULT (NPT_STDMETHODCALLTYPE *OpenSharedResource)(void *self, HANDLE hResource, const IID * ReturnedInterface, void ** ppResource);
    /* slot 29: ID3D11Device::CheckFormatSupport */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckFormatSupport)(void *self, DXGI_FORMAT Format, UINT * pFormatSupport);
    /* slot 30: ID3D11Device::CheckMultisampleQualityLevels */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckMultisampleQualityLevels)(void *self, DXGI_FORMAT Format, UINT SampleCount, UINT * pNumQualityLevels);
    /* slot 31: ID3D11Device::CheckCounterInfo */
    void (NPT_STDMETHODCALLTYPE *CheckCounterInfo)(void *self, D3D11_COUNTER_INFO * pCounterInfo);
    /* slot 32: ID3D11Device::CheckCounter */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckCounter)(void *self, const D3D11_COUNTER_DESC * pDesc, D3D11_COUNTER_TYPE * pType, UINT * pActiveCounters, CHAR * szName, UINT * pNameLength, CHAR * szUnits, UINT * pUnitsLength, CHAR * szDescription, UINT * pDescriptionLength);
    /* slot 33: ID3D11Device::CheckFeatureSupport */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckFeatureSupport)(void *self, D3D11_FEATURE Feature, void * pFeatureSupportData, UINT FeatureSupportDataSize);
    /* slot 34: ID3D11Device::GetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *GetPrivateData)(void *self, const GUID * guid, UINT * pDataSize, void * pData);
    /* slot 35: ID3D11Device::SetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateData)(void *self, const GUID * guid, UINT DataSize, const void * pData);
    /* slot 36: ID3D11Device::SetPrivateDataInterface */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateDataInterface)(void *self, const GUID * guid, const IUnknown * pData);
    /* slot 37: ID3D11Device::GetFeatureLevel */
    D3D_FEATURE_LEVEL (NPT_STDMETHODCALLTYPE *GetFeatureLevel)(void *self);
    /* slot 38: ID3D11Device::GetCreationFlags */
    UINT (NPT_STDMETHODCALLTYPE *GetCreationFlags)(void *self);
    /* slot 39: ID3D11Device::GetDeviceRemovedReason */
    HRESULT (NPT_STDMETHODCALLTYPE *GetDeviceRemovedReason)(void *self);
    /* slot 40: ID3D11Device::GetImmediateContext */
    void (NPT_STDMETHODCALLTYPE *GetImmediateContext)(void *self, ID3D11DeviceContext ** ppImmediateContext);
    /* slot 41: ID3D11Device::SetExceptionMode */
    HRESULT (NPT_STDMETHODCALLTYPE *SetExceptionMode)(void *self, UINT RaiseFlags);
    /* slot 42: ID3D11Device::GetExceptionMode */
    UINT (NPT_STDMETHODCALLTYPE *GetExceptionMode)(void *self);
    /* slot 43: ID3D11Device1::GetImmediateContext1 */
    void (NPT_STDMETHODCALLTYPE *GetImmediateContext1)(void *self, ID3D11DeviceContext1 ** ppImmediateContext);
    /* slot 44: ID3D11Device1::CreateDeferredContext1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeferredContext1)(void *self, UINT ContextFlags, ID3D11DeviceContext1 ** ppDeferredContext);
    /* slot 45: ID3D11Device1::CreateBlendState1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateBlendState1)(void *self, const D3D11_BLEND_DESC1 * pBlendStateDesc, ID3D11BlendState1 ** ppBlendState);
    /* slot 46: ID3D11Device1::CreateRasterizerState1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRasterizerState1)(void *self, const D3D11_RASTERIZER_DESC1 * pRasterizerDesc, ID3D11RasterizerState1 ** ppRasterizerState);
    /* slot 47: ID3D11Device1::CreateDeviceContextState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeviceContextState)(void *self, UINT Flags, const D3D_FEATURE_LEVEL * pFeatureLevels, UINT FeatureLevels, UINT SDKVersion, const IID * EmulatedInterface, D3D_FEATURE_LEVEL * pChosenFeatureLevel, ID3DDeviceContextState ** ppContextState);
    /* slot 48: ID3D11Device1::OpenSharedResource1 */
    HRESULT (NPT_STDMETHODCALLTYPE *OpenSharedResource1)(void *self, HANDLE hResource, const IID * returnedInterface, void ** ppResource);
    /* slot 49: ID3D11Device1::OpenSharedResourceByName */
    HRESULT (NPT_STDMETHODCALLTYPE *OpenSharedResourceByName)(void *self, const WCHAR * lpName, DWORD dwDesiredAccess, const IID * returnedInterface, void ** ppResource);
    /* slot 50: ID3D11Device2::GetImmediateContext2 */
    void (NPT_STDMETHODCALLTYPE *GetImmediateContext2)(void *self, ID3D11DeviceContext2 ** ppImmediateContext);
    /* slot 51: ID3D11Device2::CreateDeferredContext2 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeferredContext2)(void *self, UINT ContextFlags, ID3D11DeviceContext2 ** ppDeferredContext);
    /* slot 52: ID3D11Device2::GetResourceTiling */
    void (NPT_STDMETHODCALLTYPE *GetResourceTiling)(void *self, ID3D11Resource * pTiledResource, UINT * pNumTilesForEntireResource, D3D11_PACKED_MIP_DESC * pPackedMipDesc, D3D11_TILE_SHAPE * pStandardTileShapeForNonPackedMips, UINT * pNumSubresourceTilings, UINT FirstSubresourceTilingToGet, D3D11_SUBRESOURCE_TILING * pSubresourceTilingsForNonPackedMips);
    /* slot 53: ID3D11Device2::CheckMultisampleQualityLevels1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckMultisampleQualityLevels1)(void *self, DXGI_FORMAT Format, UINT SampleCount, UINT Flags, UINT * pNumQualityLevels);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern void NPT_STDMETHODCALLTYPE
npt_id3d11device2_default_GetImmediateContext2(void *self, ID3D11DeviceContext2 ** ppImmediateContext);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device2_default_CreateDeferredContext2(void *self, UINT ContextFlags, ID3D11DeviceContext2 ** ppDeferredContext);
extern void NPT_STDMETHODCALLTYPE
npt_id3d11device2_default_GetResourceTiling(void *self, ID3D11Resource * pTiledResource, UINT * pNumTilesForEntireResource, D3D11_PACKED_MIP_DESC * pPackedMipDesc, D3D11_TILE_SHAPE * pStandardTileShapeForNonPackedMips, UINT * pNumSubresourceTilings, UINT FirstSubresourceTilingToGet, D3D11_SUBRESOURCE_TILING * pSubresourceTilingsForNonPackedMips);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device2_default_CheckMultisampleQualityLevels1(void *self, DXGI_FORMAT Format, UINT SampleCount, UINT Flags, UINT * pNumQualityLevels);

/* Default IUnknown thunks for ID3D11Device2.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device2_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_id3d11device2_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_id3d11device2_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_id3d11device2_fill_default_vtbl(struct npt_id3d11device2_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_id3d11device2_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_id3d11device2_client_vtbl npt_id3d11device2_default_vtbl_storage;
extern void
npt_id3d11device2_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_id3d11device2_client_create(struct npt_device *dev, uint64_t host_id);


/* ================================================================== */
/* ID3D11Device3                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * ID3D11Device3Vtbl, by construction.
 */
struct npt_id3d11device3_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: ID3D11Device::CreateBuffer */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateBuffer)(void *self, const D3D11_BUFFER_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Buffer ** ppBuffer);
    /* slot 4: ID3D11Device::CreateTexture1D */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture1D)(void *self, const D3D11_TEXTURE1D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture1D ** ppTexture1D);
    /* slot 5: ID3D11Device::CreateTexture2D */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture2D)(void *self, const D3D11_TEXTURE2D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture2D ** ppTexture2D);
    /* slot 6: ID3D11Device::CreateTexture3D */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture3D)(void *self, const D3D11_TEXTURE3D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture3D ** ppTexture3D);
    /* slot 7: ID3D11Device::CreateShaderResourceView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateShaderResourceView)(void *self, ID3D11Resource * pResource, const D3D11_SHADER_RESOURCE_VIEW_DESC * pDesc, ID3D11ShaderResourceView ** ppSRView);
    /* slot 8: ID3D11Device::CreateUnorderedAccessView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateUnorderedAccessView)(void *self, ID3D11Resource * pResource, const D3D11_UNORDERED_ACCESS_VIEW_DESC * pDesc, ID3D11UnorderedAccessView ** ppUAView);
    /* slot 9: ID3D11Device::CreateRenderTargetView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRenderTargetView)(void *self, ID3D11Resource * pResource, const D3D11_RENDER_TARGET_VIEW_DESC * pDesc, ID3D11RenderTargetView ** ppRTView);
    /* slot 10: ID3D11Device::CreateDepthStencilView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDepthStencilView)(void *self, ID3D11Resource * pResource, const D3D11_DEPTH_STENCIL_VIEW_DESC * pDesc, ID3D11DepthStencilView ** ppDepthStencilView);
    /* slot 11: ID3D11Device::CreateInputLayout */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateInputLayout)(void *self, const D3D11_INPUT_ELEMENT_DESC * pInputElementDescs, UINT NumElements, const void * pShaderBytecodeWithInputSignature, SIZE_T BytecodeLength, ID3D11InputLayout ** ppInputLayout);
    /* slot 12: ID3D11Device::CreateVertexShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateVertexShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11VertexShader ** ppVertexShader);
    /* slot 13: ID3D11Device::CreateGeometryShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateGeometryShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11GeometryShader ** ppGeometryShader);
    /* slot 14: ID3D11Device::CreateGeometryShaderWithStreamOutput */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateGeometryShaderWithStreamOutput)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, const D3D11_SO_DECLARATION_ENTRY * pSODeclaration, UINT NumEntries, const UINT * pBufferStrides, UINT NumStrides, UINT RasterizedStream, ID3D11ClassLinkage * pClassLinkage, ID3D11GeometryShader ** ppGeometryShader);
    /* slot 15: ID3D11Device::CreatePixelShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreatePixelShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11PixelShader ** ppPixelShader);
    /* slot 16: ID3D11Device::CreateHullShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateHullShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11HullShader ** ppHullShader);
    /* slot 17: ID3D11Device::CreateDomainShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDomainShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11DomainShader ** ppDomainShader);
    /* slot 18: ID3D11Device::CreateComputeShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateComputeShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11ComputeShader ** ppComputeShader);
    /* slot 19: ID3D11Device::CreateClassLinkage */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateClassLinkage)(void *self, ID3D11ClassLinkage ** ppLinkage);
    /* slot 20: ID3D11Device::CreateBlendState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateBlendState)(void *self, const D3D11_BLEND_DESC * pBlendStateDesc, ID3D11BlendState ** ppBlendState);
    /* slot 21: ID3D11Device::CreateDepthStencilState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDepthStencilState)(void *self, const D3D11_DEPTH_STENCIL_DESC * pDepthStencilDesc, ID3D11DepthStencilState ** ppDepthStencilState);
    /* slot 22: ID3D11Device::CreateRasterizerState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRasterizerState)(void *self, const D3D11_RASTERIZER_DESC * pRasterizerDesc, ID3D11RasterizerState ** ppRasterizerState);
    /* slot 23: ID3D11Device::CreateSamplerState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSamplerState)(void *self, const D3D11_SAMPLER_DESC * pSamplerDesc, ID3D11SamplerState ** ppSamplerState);
    /* slot 24: ID3D11Device::CreateQuery */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateQuery)(void *self, const D3D11_QUERY_DESC * pQueryDesc, ID3D11Query ** ppQuery);
    /* slot 25: ID3D11Device::CreatePredicate */
    HRESULT (NPT_STDMETHODCALLTYPE *CreatePredicate)(void *self, const D3D11_QUERY_DESC * pPredicateDesc, ID3D11Predicate ** ppPredicate);
    /* slot 26: ID3D11Device::CreateCounter */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateCounter)(void *self, const D3D11_COUNTER_DESC * pCounterDesc, ID3D11Counter ** ppCounter);
    /* slot 27: ID3D11Device::CreateDeferredContext */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeferredContext)(void *self, UINT ContextFlags, ID3D11DeviceContext ** ppDeferredContext);
    /* slot 28: ID3D11Device::OpenSharedResource */
    HRESULT (NPT_STDMETHODCALLTYPE *OpenSharedResource)(void *self, HANDLE hResource, const IID * ReturnedInterface, void ** ppResource);
    /* slot 29: ID3D11Device::CheckFormatSupport */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckFormatSupport)(void *self, DXGI_FORMAT Format, UINT * pFormatSupport);
    /* slot 30: ID3D11Device::CheckMultisampleQualityLevels */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckMultisampleQualityLevels)(void *self, DXGI_FORMAT Format, UINT SampleCount, UINT * pNumQualityLevels);
    /* slot 31: ID3D11Device::CheckCounterInfo */
    void (NPT_STDMETHODCALLTYPE *CheckCounterInfo)(void *self, D3D11_COUNTER_INFO * pCounterInfo);
    /* slot 32: ID3D11Device::CheckCounter */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckCounter)(void *self, const D3D11_COUNTER_DESC * pDesc, D3D11_COUNTER_TYPE * pType, UINT * pActiveCounters, CHAR * szName, UINT * pNameLength, CHAR * szUnits, UINT * pUnitsLength, CHAR * szDescription, UINT * pDescriptionLength);
    /* slot 33: ID3D11Device::CheckFeatureSupport */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckFeatureSupport)(void *self, D3D11_FEATURE Feature, void * pFeatureSupportData, UINT FeatureSupportDataSize);
    /* slot 34: ID3D11Device::GetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *GetPrivateData)(void *self, const GUID * guid, UINT * pDataSize, void * pData);
    /* slot 35: ID3D11Device::SetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateData)(void *self, const GUID * guid, UINT DataSize, const void * pData);
    /* slot 36: ID3D11Device::SetPrivateDataInterface */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateDataInterface)(void *self, const GUID * guid, const IUnknown * pData);
    /* slot 37: ID3D11Device::GetFeatureLevel */
    D3D_FEATURE_LEVEL (NPT_STDMETHODCALLTYPE *GetFeatureLevel)(void *self);
    /* slot 38: ID3D11Device::GetCreationFlags */
    UINT (NPT_STDMETHODCALLTYPE *GetCreationFlags)(void *self);
    /* slot 39: ID3D11Device::GetDeviceRemovedReason */
    HRESULT (NPT_STDMETHODCALLTYPE *GetDeviceRemovedReason)(void *self);
    /* slot 40: ID3D11Device::GetImmediateContext */
    void (NPT_STDMETHODCALLTYPE *GetImmediateContext)(void *self, ID3D11DeviceContext ** ppImmediateContext);
    /* slot 41: ID3D11Device::SetExceptionMode */
    HRESULT (NPT_STDMETHODCALLTYPE *SetExceptionMode)(void *self, UINT RaiseFlags);
    /* slot 42: ID3D11Device::GetExceptionMode */
    UINT (NPT_STDMETHODCALLTYPE *GetExceptionMode)(void *self);
    /* slot 43: ID3D11Device1::GetImmediateContext1 */
    void (NPT_STDMETHODCALLTYPE *GetImmediateContext1)(void *self, ID3D11DeviceContext1 ** ppImmediateContext);
    /* slot 44: ID3D11Device1::CreateDeferredContext1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeferredContext1)(void *self, UINT ContextFlags, ID3D11DeviceContext1 ** ppDeferredContext);
    /* slot 45: ID3D11Device1::CreateBlendState1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateBlendState1)(void *self, const D3D11_BLEND_DESC1 * pBlendStateDesc, ID3D11BlendState1 ** ppBlendState);
    /* slot 46: ID3D11Device1::CreateRasterizerState1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRasterizerState1)(void *self, const D3D11_RASTERIZER_DESC1 * pRasterizerDesc, ID3D11RasterizerState1 ** ppRasterizerState);
    /* slot 47: ID3D11Device1::CreateDeviceContextState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeviceContextState)(void *self, UINT Flags, const D3D_FEATURE_LEVEL * pFeatureLevels, UINT FeatureLevels, UINT SDKVersion, const IID * EmulatedInterface, D3D_FEATURE_LEVEL * pChosenFeatureLevel, ID3DDeviceContextState ** ppContextState);
    /* slot 48: ID3D11Device1::OpenSharedResource1 */
    HRESULT (NPT_STDMETHODCALLTYPE *OpenSharedResource1)(void *self, HANDLE hResource, const IID * returnedInterface, void ** ppResource);
    /* slot 49: ID3D11Device1::OpenSharedResourceByName */
    HRESULT (NPT_STDMETHODCALLTYPE *OpenSharedResourceByName)(void *self, const WCHAR * lpName, DWORD dwDesiredAccess, const IID * returnedInterface, void ** ppResource);
    /* slot 50: ID3D11Device2::GetImmediateContext2 */
    void (NPT_STDMETHODCALLTYPE *GetImmediateContext2)(void *self, ID3D11DeviceContext2 ** ppImmediateContext);
    /* slot 51: ID3D11Device2::CreateDeferredContext2 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeferredContext2)(void *self, UINT ContextFlags, ID3D11DeviceContext2 ** ppDeferredContext);
    /* slot 52: ID3D11Device2::GetResourceTiling */
    void (NPT_STDMETHODCALLTYPE *GetResourceTiling)(void *self, ID3D11Resource * pTiledResource, UINT * pNumTilesForEntireResource, D3D11_PACKED_MIP_DESC * pPackedMipDesc, D3D11_TILE_SHAPE * pStandardTileShapeForNonPackedMips, UINT * pNumSubresourceTilings, UINT FirstSubresourceTilingToGet, D3D11_SUBRESOURCE_TILING * pSubresourceTilingsForNonPackedMips);
    /* slot 53: ID3D11Device2::CheckMultisampleQualityLevels1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckMultisampleQualityLevels1)(void *self, DXGI_FORMAT Format, UINT SampleCount, UINT Flags, UINT * pNumQualityLevels);
    /* slot 54: ID3D11Device3::CreateTexture2D1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture2D1)(void *self, const D3D11_TEXTURE2D_DESC1 * pDesc1, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture2D1 ** ppTexture2D);
    /* slot 55: ID3D11Device3::CreateTexture3D1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture3D1)(void *self, const D3D11_TEXTURE3D_DESC1 * pDesc1, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture3D1 ** ppTexture3D);
    /* slot 56: ID3D11Device3::CreateRasterizerState2 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRasterizerState2)(void *self, const D3D11_RASTERIZER_DESC2 * pRasterizerDesc, ID3D11RasterizerState2 ** ppRasterizerState);
    /* slot 57: ID3D11Device3::CreateShaderResourceView1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateShaderResourceView1)(void *self, ID3D11Resource * pResource, const D3D11_SHADER_RESOURCE_VIEW_DESC1 * pDesc1, ID3D11ShaderResourceView1 ** ppSRView1);
    /* slot 58: ID3D11Device3::CreateUnorderedAccessView1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateUnorderedAccessView1)(void *self, ID3D11Resource * pResource, const D3D11_UNORDERED_ACCESS_VIEW_DESC1 * pDesc1, ID3D11UnorderedAccessView1 ** ppUAView1);
    /* slot 59: ID3D11Device3::CreateRenderTargetView1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRenderTargetView1)(void *self, ID3D11Resource * pResource, const D3D11_RENDER_TARGET_VIEW_DESC1 * pDesc1, ID3D11RenderTargetView1 ** ppRTView1);
    /* slot 60: ID3D11Device3::CreateQuery1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateQuery1)(void *self, const D3D11_QUERY_DESC1 * pQueryDesc1, ID3D11Query1 ** ppQuery1);
    /* slot 61: ID3D11Device3::GetImmediateContext3 */
    void (NPT_STDMETHODCALLTYPE *GetImmediateContext3)(void *self, ID3D11DeviceContext3 ** ppImmediateContext);
    /* slot 62: ID3D11Device3::CreateDeferredContext3 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeferredContext3)(void *self, UINT ContextFlags, ID3D11DeviceContext3 ** ppDeferredContext);
    /* slot 63: ID3D11Device3::WriteToSubresource */
    void (NPT_STDMETHODCALLTYPE *WriteToSubresource)(void *self, ID3D11Resource * pDstResource, UINT DstSubresource, const D3D11_BOX * pDstBox, const void * pSrcData, UINT SrcRowPitch, UINT SrcDepthPitch);
    /* slot 64: ID3D11Device3::ReadFromSubresource */
    void (NPT_STDMETHODCALLTYPE *ReadFromSubresource)(void *self, void * pDstData, UINT DstRowPitch, UINT DstDepthPitch, ID3D11Resource * pSrcResource, UINT SrcSubresource, const D3D11_BOX * pSrcBox);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device3_default_CreateTexture2D1(void *self, const D3D11_TEXTURE2D_DESC1 * pDesc1, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture2D1 ** ppTexture2D);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device3_default_CreateTexture3D1(void *self, const D3D11_TEXTURE3D_DESC1 * pDesc1, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture3D1 ** ppTexture3D);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device3_default_CreateRasterizerState2(void *self, const D3D11_RASTERIZER_DESC2 * pRasterizerDesc, ID3D11RasterizerState2 ** ppRasterizerState);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device3_default_CreateShaderResourceView1(void *self, ID3D11Resource * pResource, const D3D11_SHADER_RESOURCE_VIEW_DESC1 * pDesc1, ID3D11ShaderResourceView1 ** ppSRView1);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device3_default_CreateUnorderedAccessView1(void *self, ID3D11Resource * pResource, const D3D11_UNORDERED_ACCESS_VIEW_DESC1 * pDesc1, ID3D11UnorderedAccessView1 ** ppUAView1);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device3_default_CreateRenderTargetView1(void *self, ID3D11Resource * pResource, const D3D11_RENDER_TARGET_VIEW_DESC1 * pDesc1, ID3D11RenderTargetView1 ** ppRTView1);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device3_default_CreateQuery1(void *self, const D3D11_QUERY_DESC1 * pQueryDesc1, ID3D11Query1 ** ppQuery1);
extern void NPT_STDMETHODCALLTYPE
npt_id3d11device3_default_GetImmediateContext3(void *self, ID3D11DeviceContext3 ** ppImmediateContext);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device3_default_CreateDeferredContext3(void *self, UINT ContextFlags, ID3D11DeviceContext3 ** ppDeferredContext);
extern void NPT_STDMETHODCALLTYPE
npt_id3d11device3_default_WriteToSubresource(void *self, ID3D11Resource * pDstResource, UINT DstSubresource, const D3D11_BOX * pDstBox, const void * pSrcData, UINT SrcRowPitch, UINT SrcDepthPitch);
extern void NPT_STDMETHODCALLTYPE
npt_id3d11device3_default_ReadFromSubresource(void *self, void * pDstData, UINT DstRowPitch, UINT DstDepthPitch, ID3D11Resource * pSrcResource, UINT SrcSubresource, const D3D11_BOX * pSrcBox);

/* Default IUnknown thunks for ID3D11Device3.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device3_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_id3d11device3_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_id3d11device3_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_id3d11device3_fill_default_vtbl(struct npt_id3d11device3_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_id3d11device3_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_id3d11device3_client_vtbl npt_id3d11device3_default_vtbl_storage;
extern void
npt_id3d11device3_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_id3d11device3_client_create(struct npt_device *dev, uint64_t host_id);


/* ================================================================== */
/* ID3D11Device4                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * ID3D11Device4Vtbl, by construction.
 */
struct npt_id3d11device4_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: ID3D11Device::CreateBuffer */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateBuffer)(void *self, const D3D11_BUFFER_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Buffer ** ppBuffer);
    /* slot 4: ID3D11Device::CreateTexture1D */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture1D)(void *self, const D3D11_TEXTURE1D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture1D ** ppTexture1D);
    /* slot 5: ID3D11Device::CreateTexture2D */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture2D)(void *self, const D3D11_TEXTURE2D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture2D ** ppTexture2D);
    /* slot 6: ID3D11Device::CreateTexture3D */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture3D)(void *self, const D3D11_TEXTURE3D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture3D ** ppTexture3D);
    /* slot 7: ID3D11Device::CreateShaderResourceView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateShaderResourceView)(void *self, ID3D11Resource * pResource, const D3D11_SHADER_RESOURCE_VIEW_DESC * pDesc, ID3D11ShaderResourceView ** ppSRView);
    /* slot 8: ID3D11Device::CreateUnorderedAccessView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateUnorderedAccessView)(void *self, ID3D11Resource * pResource, const D3D11_UNORDERED_ACCESS_VIEW_DESC * pDesc, ID3D11UnorderedAccessView ** ppUAView);
    /* slot 9: ID3D11Device::CreateRenderTargetView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRenderTargetView)(void *self, ID3D11Resource * pResource, const D3D11_RENDER_TARGET_VIEW_DESC * pDesc, ID3D11RenderTargetView ** ppRTView);
    /* slot 10: ID3D11Device::CreateDepthStencilView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDepthStencilView)(void *self, ID3D11Resource * pResource, const D3D11_DEPTH_STENCIL_VIEW_DESC * pDesc, ID3D11DepthStencilView ** ppDepthStencilView);
    /* slot 11: ID3D11Device::CreateInputLayout */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateInputLayout)(void *self, const D3D11_INPUT_ELEMENT_DESC * pInputElementDescs, UINT NumElements, const void * pShaderBytecodeWithInputSignature, SIZE_T BytecodeLength, ID3D11InputLayout ** ppInputLayout);
    /* slot 12: ID3D11Device::CreateVertexShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateVertexShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11VertexShader ** ppVertexShader);
    /* slot 13: ID3D11Device::CreateGeometryShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateGeometryShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11GeometryShader ** ppGeometryShader);
    /* slot 14: ID3D11Device::CreateGeometryShaderWithStreamOutput */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateGeometryShaderWithStreamOutput)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, const D3D11_SO_DECLARATION_ENTRY * pSODeclaration, UINT NumEntries, const UINT * pBufferStrides, UINT NumStrides, UINT RasterizedStream, ID3D11ClassLinkage * pClassLinkage, ID3D11GeometryShader ** ppGeometryShader);
    /* slot 15: ID3D11Device::CreatePixelShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreatePixelShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11PixelShader ** ppPixelShader);
    /* slot 16: ID3D11Device::CreateHullShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateHullShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11HullShader ** ppHullShader);
    /* slot 17: ID3D11Device::CreateDomainShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDomainShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11DomainShader ** ppDomainShader);
    /* slot 18: ID3D11Device::CreateComputeShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateComputeShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11ComputeShader ** ppComputeShader);
    /* slot 19: ID3D11Device::CreateClassLinkage */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateClassLinkage)(void *self, ID3D11ClassLinkage ** ppLinkage);
    /* slot 20: ID3D11Device::CreateBlendState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateBlendState)(void *self, const D3D11_BLEND_DESC * pBlendStateDesc, ID3D11BlendState ** ppBlendState);
    /* slot 21: ID3D11Device::CreateDepthStencilState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDepthStencilState)(void *self, const D3D11_DEPTH_STENCIL_DESC * pDepthStencilDesc, ID3D11DepthStencilState ** ppDepthStencilState);
    /* slot 22: ID3D11Device::CreateRasterizerState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRasterizerState)(void *self, const D3D11_RASTERIZER_DESC * pRasterizerDesc, ID3D11RasterizerState ** ppRasterizerState);
    /* slot 23: ID3D11Device::CreateSamplerState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSamplerState)(void *self, const D3D11_SAMPLER_DESC * pSamplerDesc, ID3D11SamplerState ** ppSamplerState);
    /* slot 24: ID3D11Device::CreateQuery */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateQuery)(void *self, const D3D11_QUERY_DESC * pQueryDesc, ID3D11Query ** ppQuery);
    /* slot 25: ID3D11Device::CreatePredicate */
    HRESULT (NPT_STDMETHODCALLTYPE *CreatePredicate)(void *self, const D3D11_QUERY_DESC * pPredicateDesc, ID3D11Predicate ** ppPredicate);
    /* slot 26: ID3D11Device::CreateCounter */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateCounter)(void *self, const D3D11_COUNTER_DESC * pCounterDesc, ID3D11Counter ** ppCounter);
    /* slot 27: ID3D11Device::CreateDeferredContext */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeferredContext)(void *self, UINT ContextFlags, ID3D11DeviceContext ** ppDeferredContext);
    /* slot 28: ID3D11Device::OpenSharedResource */
    HRESULT (NPT_STDMETHODCALLTYPE *OpenSharedResource)(void *self, HANDLE hResource, const IID * ReturnedInterface, void ** ppResource);
    /* slot 29: ID3D11Device::CheckFormatSupport */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckFormatSupport)(void *self, DXGI_FORMAT Format, UINT * pFormatSupport);
    /* slot 30: ID3D11Device::CheckMultisampleQualityLevels */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckMultisampleQualityLevels)(void *self, DXGI_FORMAT Format, UINT SampleCount, UINT * pNumQualityLevels);
    /* slot 31: ID3D11Device::CheckCounterInfo */
    void (NPT_STDMETHODCALLTYPE *CheckCounterInfo)(void *self, D3D11_COUNTER_INFO * pCounterInfo);
    /* slot 32: ID3D11Device::CheckCounter */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckCounter)(void *self, const D3D11_COUNTER_DESC * pDesc, D3D11_COUNTER_TYPE * pType, UINT * pActiveCounters, CHAR * szName, UINT * pNameLength, CHAR * szUnits, UINT * pUnitsLength, CHAR * szDescription, UINT * pDescriptionLength);
    /* slot 33: ID3D11Device::CheckFeatureSupport */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckFeatureSupport)(void *self, D3D11_FEATURE Feature, void * pFeatureSupportData, UINT FeatureSupportDataSize);
    /* slot 34: ID3D11Device::GetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *GetPrivateData)(void *self, const GUID * guid, UINT * pDataSize, void * pData);
    /* slot 35: ID3D11Device::SetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateData)(void *self, const GUID * guid, UINT DataSize, const void * pData);
    /* slot 36: ID3D11Device::SetPrivateDataInterface */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateDataInterface)(void *self, const GUID * guid, const IUnknown * pData);
    /* slot 37: ID3D11Device::GetFeatureLevel */
    D3D_FEATURE_LEVEL (NPT_STDMETHODCALLTYPE *GetFeatureLevel)(void *self);
    /* slot 38: ID3D11Device::GetCreationFlags */
    UINT (NPT_STDMETHODCALLTYPE *GetCreationFlags)(void *self);
    /* slot 39: ID3D11Device::GetDeviceRemovedReason */
    HRESULT (NPT_STDMETHODCALLTYPE *GetDeviceRemovedReason)(void *self);
    /* slot 40: ID3D11Device::GetImmediateContext */
    void (NPT_STDMETHODCALLTYPE *GetImmediateContext)(void *self, ID3D11DeviceContext ** ppImmediateContext);
    /* slot 41: ID3D11Device::SetExceptionMode */
    HRESULT (NPT_STDMETHODCALLTYPE *SetExceptionMode)(void *self, UINT RaiseFlags);
    /* slot 42: ID3D11Device::GetExceptionMode */
    UINT (NPT_STDMETHODCALLTYPE *GetExceptionMode)(void *self);
    /* slot 43: ID3D11Device1::GetImmediateContext1 */
    void (NPT_STDMETHODCALLTYPE *GetImmediateContext1)(void *self, ID3D11DeviceContext1 ** ppImmediateContext);
    /* slot 44: ID3D11Device1::CreateDeferredContext1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeferredContext1)(void *self, UINT ContextFlags, ID3D11DeviceContext1 ** ppDeferredContext);
    /* slot 45: ID3D11Device1::CreateBlendState1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateBlendState1)(void *self, const D3D11_BLEND_DESC1 * pBlendStateDesc, ID3D11BlendState1 ** ppBlendState);
    /* slot 46: ID3D11Device1::CreateRasterizerState1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRasterizerState1)(void *self, const D3D11_RASTERIZER_DESC1 * pRasterizerDesc, ID3D11RasterizerState1 ** ppRasterizerState);
    /* slot 47: ID3D11Device1::CreateDeviceContextState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeviceContextState)(void *self, UINT Flags, const D3D_FEATURE_LEVEL * pFeatureLevels, UINT FeatureLevels, UINT SDKVersion, const IID * EmulatedInterface, D3D_FEATURE_LEVEL * pChosenFeatureLevel, ID3DDeviceContextState ** ppContextState);
    /* slot 48: ID3D11Device1::OpenSharedResource1 */
    HRESULT (NPT_STDMETHODCALLTYPE *OpenSharedResource1)(void *self, HANDLE hResource, const IID * returnedInterface, void ** ppResource);
    /* slot 49: ID3D11Device1::OpenSharedResourceByName */
    HRESULT (NPT_STDMETHODCALLTYPE *OpenSharedResourceByName)(void *self, const WCHAR * lpName, DWORD dwDesiredAccess, const IID * returnedInterface, void ** ppResource);
    /* slot 50: ID3D11Device2::GetImmediateContext2 */
    void (NPT_STDMETHODCALLTYPE *GetImmediateContext2)(void *self, ID3D11DeviceContext2 ** ppImmediateContext);
    /* slot 51: ID3D11Device2::CreateDeferredContext2 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeferredContext2)(void *self, UINT ContextFlags, ID3D11DeviceContext2 ** ppDeferredContext);
    /* slot 52: ID3D11Device2::GetResourceTiling */
    void (NPT_STDMETHODCALLTYPE *GetResourceTiling)(void *self, ID3D11Resource * pTiledResource, UINT * pNumTilesForEntireResource, D3D11_PACKED_MIP_DESC * pPackedMipDesc, D3D11_TILE_SHAPE * pStandardTileShapeForNonPackedMips, UINT * pNumSubresourceTilings, UINT FirstSubresourceTilingToGet, D3D11_SUBRESOURCE_TILING * pSubresourceTilingsForNonPackedMips);
    /* slot 53: ID3D11Device2::CheckMultisampleQualityLevels1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckMultisampleQualityLevels1)(void *self, DXGI_FORMAT Format, UINT SampleCount, UINT Flags, UINT * pNumQualityLevels);
    /* slot 54: ID3D11Device3::CreateTexture2D1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture2D1)(void *self, const D3D11_TEXTURE2D_DESC1 * pDesc1, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture2D1 ** ppTexture2D);
    /* slot 55: ID3D11Device3::CreateTexture3D1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture3D1)(void *self, const D3D11_TEXTURE3D_DESC1 * pDesc1, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture3D1 ** ppTexture3D);
    /* slot 56: ID3D11Device3::CreateRasterizerState2 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRasterizerState2)(void *self, const D3D11_RASTERIZER_DESC2 * pRasterizerDesc, ID3D11RasterizerState2 ** ppRasterizerState);
    /* slot 57: ID3D11Device3::CreateShaderResourceView1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateShaderResourceView1)(void *self, ID3D11Resource * pResource, const D3D11_SHADER_RESOURCE_VIEW_DESC1 * pDesc1, ID3D11ShaderResourceView1 ** ppSRView1);
    /* slot 58: ID3D11Device3::CreateUnorderedAccessView1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateUnorderedAccessView1)(void *self, ID3D11Resource * pResource, const D3D11_UNORDERED_ACCESS_VIEW_DESC1 * pDesc1, ID3D11UnorderedAccessView1 ** ppUAView1);
    /* slot 59: ID3D11Device3::CreateRenderTargetView1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRenderTargetView1)(void *self, ID3D11Resource * pResource, const D3D11_RENDER_TARGET_VIEW_DESC1 * pDesc1, ID3D11RenderTargetView1 ** ppRTView1);
    /* slot 60: ID3D11Device3::CreateQuery1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateQuery1)(void *self, const D3D11_QUERY_DESC1 * pQueryDesc1, ID3D11Query1 ** ppQuery1);
    /* slot 61: ID3D11Device3::GetImmediateContext3 */
    void (NPT_STDMETHODCALLTYPE *GetImmediateContext3)(void *self, ID3D11DeviceContext3 ** ppImmediateContext);
    /* slot 62: ID3D11Device3::CreateDeferredContext3 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeferredContext3)(void *self, UINT ContextFlags, ID3D11DeviceContext3 ** ppDeferredContext);
    /* slot 63: ID3D11Device3::WriteToSubresource */
    void (NPT_STDMETHODCALLTYPE *WriteToSubresource)(void *self, ID3D11Resource * pDstResource, UINT DstSubresource, const D3D11_BOX * pDstBox, const void * pSrcData, UINT SrcRowPitch, UINT SrcDepthPitch);
    /* slot 64: ID3D11Device3::ReadFromSubresource */
    void (NPT_STDMETHODCALLTYPE *ReadFromSubresource)(void *self, void * pDstData, UINT DstRowPitch, UINT DstDepthPitch, ID3D11Resource * pSrcResource, UINT SrcSubresource, const D3D11_BOX * pSrcBox);
    /* slot 65: ID3D11Device4::RegisterDeviceRemovedEvent */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterDeviceRemovedEvent)(void *self, HANDLE hEvent, DWORD * pdwCookie);
    /* slot 66: ID3D11Device4::UnregisterDeviceRemoved */
    void (NPT_STDMETHODCALLTYPE *UnregisterDeviceRemoved)(void *self, DWORD dwCookie);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device4_default_RegisterDeviceRemovedEvent(void *self, HANDLE hEvent, DWORD * pdwCookie);
extern void NPT_STDMETHODCALLTYPE
npt_id3d11device4_default_UnregisterDeviceRemoved(void *self, DWORD dwCookie);

/* Default IUnknown thunks for ID3D11Device4.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device4_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_id3d11device4_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_id3d11device4_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_id3d11device4_fill_default_vtbl(struct npt_id3d11device4_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_id3d11device4_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_id3d11device4_client_vtbl npt_id3d11device4_default_vtbl_storage;
extern void
npt_id3d11device4_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_id3d11device4_client_create(struct npt_device *dev, uint64_t host_id);


/* ================================================================== */
/* ID3D11Device5                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * ID3D11Device5Vtbl, by construction.
 */
struct npt_id3d11device5_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: ID3D11Device::CreateBuffer */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateBuffer)(void *self, const D3D11_BUFFER_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Buffer ** ppBuffer);
    /* slot 4: ID3D11Device::CreateTexture1D */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture1D)(void *self, const D3D11_TEXTURE1D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture1D ** ppTexture1D);
    /* slot 5: ID3D11Device::CreateTexture2D */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture2D)(void *self, const D3D11_TEXTURE2D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture2D ** ppTexture2D);
    /* slot 6: ID3D11Device::CreateTexture3D */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture3D)(void *self, const D3D11_TEXTURE3D_DESC * pDesc, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture3D ** ppTexture3D);
    /* slot 7: ID3D11Device::CreateShaderResourceView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateShaderResourceView)(void *self, ID3D11Resource * pResource, const D3D11_SHADER_RESOURCE_VIEW_DESC * pDesc, ID3D11ShaderResourceView ** ppSRView);
    /* slot 8: ID3D11Device::CreateUnorderedAccessView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateUnorderedAccessView)(void *self, ID3D11Resource * pResource, const D3D11_UNORDERED_ACCESS_VIEW_DESC * pDesc, ID3D11UnorderedAccessView ** ppUAView);
    /* slot 9: ID3D11Device::CreateRenderTargetView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRenderTargetView)(void *self, ID3D11Resource * pResource, const D3D11_RENDER_TARGET_VIEW_DESC * pDesc, ID3D11RenderTargetView ** ppRTView);
    /* slot 10: ID3D11Device::CreateDepthStencilView */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDepthStencilView)(void *self, ID3D11Resource * pResource, const D3D11_DEPTH_STENCIL_VIEW_DESC * pDesc, ID3D11DepthStencilView ** ppDepthStencilView);
    /* slot 11: ID3D11Device::CreateInputLayout */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateInputLayout)(void *self, const D3D11_INPUT_ELEMENT_DESC * pInputElementDescs, UINT NumElements, const void * pShaderBytecodeWithInputSignature, SIZE_T BytecodeLength, ID3D11InputLayout ** ppInputLayout);
    /* slot 12: ID3D11Device::CreateVertexShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateVertexShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11VertexShader ** ppVertexShader);
    /* slot 13: ID3D11Device::CreateGeometryShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateGeometryShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11GeometryShader ** ppGeometryShader);
    /* slot 14: ID3D11Device::CreateGeometryShaderWithStreamOutput */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateGeometryShaderWithStreamOutput)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, const D3D11_SO_DECLARATION_ENTRY * pSODeclaration, UINT NumEntries, const UINT * pBufferStrides, UINT NumStrides, UINT RasterizedStream, ID3D11ClassLinkage * pClassLinkage, ID3D11GeometryShader ** ppGeometryShader);
    /* slot 15: ID3D11Device::CreatePixelShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreatePixelShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11PixelShader ** ppPixelShader);
    /* slot 16: ID3D11Device::CreateHullShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateHullShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11HullShader ** ppHullShader);
    /* slot 17: ID3D11Device::CreateDomainShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDomainShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11DomainShader ** ppDomainShader);
    /* slot 18: ID3D11Device::CreateComputeShader */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateComputeShader)(void *self, const void * pShaderBytecode, SIZE_T BytecodeLength, ID3D11ClassLinkage * pClassLinkage, ID3D11ComputeShader ** ppComputeShader);
    /* slot 19: ID3D11Device::CreateClassLinkage */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateClassLinkage)(void *self, ID3D11ClassLinkage ** ppLinkage);
    /* slot 20: ID3D11Device::CreateBlendState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateBlendState)(void *self, const D3D11_BLEND_DESC * pBlendStateDesc, ID3D11BlendState ** ppBlendState);
    /* slot 21: ID3D11Device::CreateDepthStencilState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDepthStencilState)(void *self, const D3D11_DEPTH_STENCIL_DESC * pDepthStencilDesc, ID3D11DepthStencilState ** ppDepthStencilState);
    /* slot 22: ID3D11Device::CreateRasterizerState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRasterizerState)(void *self, const D3D11_RASTERIZER_DESC * pRasterizerDesc, ID3D11RasterizerState ** ppRasterizerState);
    /* slot 23: ID3D11Device::CreateSamplerState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSamplerState)(void *self, const D3D11_SAMPLER_DESC * pSamplerDesc, ID3D11SamplerState ** ppSamplerState);
    /* slot 24: ID3D11Device::CreateQuery */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateQuery)(void *self, const D3D11_QUERY_DESC * pQueryDesc, ID3D11Query ** ppQuery);
    /* slot 25: ID3D11Device::CreatePredicate */
    HRESULT (NPT_STDMETHODCALLTYPE *CreatePredicate)(void *self, const D3D11_QUERY_DESC * pPredicateDesc, ID3D11Predicate ** ppPredicate);
    /* slot 26: ID3D11Device::CreateCounter */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateCounter)(void *self, const D3D11_COUNTER_DESC * pCounterDesc, ID3D11Counter ** ppCounter);
    /* slot 27: ID3D11Device::CreateDeferredContext */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeferredContext)(void *self, UINT ContextFlags, ID3D11DeviceContext ** ppDeferredContext);
    /* slot 28: ID3D11Device::OpenSharedResource */
    HRESULT (NPT_STDMETHODCALLTYPE *OpenSharedResource)(void *self, HANDLE hResource, const IID * ReturnedInterface, void ** ppResource);
    /* slot 29: ID3D11Device::CheckFormatSupport */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckFormatSupport)(void *self, DXGI_FORMAT Format, UINT * pFormatSupport);
    /* slot 30: ID3D11Device::CheckMultisampleQualityLevels */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckMultisampleQualityLevels)(void *self, DXGI_FORMAT Format, UINT SampleCount, UINT * pNumQualityLevels);
    /* slot 31: ID3D11Device::CheckCounterInfo */
    void (NPT_STDMETHODCALLTYPE *CheckCounterInfo)(void *self, D3D11_COUNTER_INFO * pCounterInfo);
    /* slot 32: ID3D11Device::CheckCounter */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckCounter)(void *self, const D3D11_COUNTER_DESC * pDesc, D3D11_COUNTER_TYPE * pType, UINT * pActiveCounters, CHAR * szName, UINT * pNameLength, CHAR * szUnits, UINT * pUnitsLength, CHAR * szDescription, UINT * pDescriptionLength);
    /* slot 33: ID3D11Device::CheckFeatureSupport */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckFeatureSupport)(void *self, D3D11_FEATURE Feature, void * pFeatureSupportData, UINT FeatureSupportDataSize);
    /* slot 34: ID3D11Device::GetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *GetPrivateData)(void *self, const GUID * guid, UINT * pDataSize, void * pData);
    /* slot 35: ID3D11Device::SetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateData)(void *self, const GUID * guid, UINT DataSize, const void * pData);
    /* slot 36: ID3D11Device::SetPrivateDataInterface */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateDataInterface)(void *self, const GUID * guid, const IUnknown * pData);
    /* slot 37: ID3D11Device::GetFeatureLevel */
    D3D_FEATURE_LEVEL (NPT_STDMETHODCALLTYPE *GetFeatureLevel)(void *self);
    /* slot 38: ID3D11Device::GetCreationFlags */
    UINT (NPT_STDMETHODCALLTYPE *GetCreationFlags)(void *self);
    /* slot 39: ID3D11Device::GetDeviceRemovedReason */
    HRESULT (NPT_STDMETHODCALLTYPE *GetDeviceRemovedReason)(void *self);
    /* slot 40: ID3D11Device::GetImmediateContext */
    void (NPT_STDMETHODCALLTYPE *GetImmediateContext)(void *self, ID3D11DeviceContext ** ppImmediateContext);
    /* slot 41: ID3D11Device::SetExceptionMode */
    HRESULT (NPT_STDMETHODCALLTYPE *SetExceptionMode)(void *self, UINT RaiseFlags);
    /* slot 42: ID3D11Device::GetExceptionMode */
    UINT (NPT_STDMETHODCALLTYPE *GetExceptionMode)(void *self);
    /* slot 43: ID3D11Device1::GetImmediateContext1 */
    void (NPT_STDMETHODCALLTYPE *GetImmediateContext1)(void *self, ID3D11DeviceContext1 ** ppImmediateContext);
    /* slot 44: ID3D11Device1::CreateDeferredContext1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeferredContext1)(void *self, UINT ContextFlags, ID3D11DeviceContext1 ** ppDeferredContext);
    /* slot 45: ID3D11Device1::CreateBlendState1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateBlendState1)(void *self, const D3D11_BLEND_DESC1 * pBlendStateDesc, ID3D11BlendState1 ** ppBlendState);
    /* slot 46: ID3D11Device1::CreateRasterizerState1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRasterizerState1)(void *self, const D3D11_RASTERIZER_DESC1 * pRasterizerDesc, ID3D11RasterizerState1 ** ppRasterizerState);
    /* slot 47: ID3D11Device1::CreateDeviceContextState */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeviceContextState)(void *self, UINT Flags, const D3D_FEATURE_LEVEL * pFeatureLevels, UINT FeatureLevels, UINT SDKVersion, const IID * EmulatedInterface, D3D_FEATURE_LEVEL * pChosenFeatureLevel, ID3DDeviceContextState ** ppContextState);
    /* slot 48: ID3D11Device1::OpenSharedResource1 */
    HRESULT (NPT_STDMETHODCALLTYPE *OpenSharedResource1)(void *self, HANDLE hResource, const IID * returnedInterface, void ** ppResource);
    /* slot 49: ID3D11Device1::OpenSharedResourceByName */
    HRESULT (NPT_STDMETHODCALLTYPE *OpenSharedResourceByName)(void *self, const WCHAR * lpName, DWORD dwDesiredAccess, const IID * returnedInterface, void ** ppResource);
    /* slot 50: ID3D11Device2::GetImmediateContext2 */
    void (NPT_STDMETHODCALLTYPE *GetImmediateContext2)(void *self, ID3D11DeviceContext2 ** ppImmediateContext);
    /* slot 51: ID3D11Device2::CreateDeferredContext2 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeferredContext2)(void *self, UINT ContextFlags, ID3D11DeviceContext2 ** ppDeferredContext);
    /* slot 52: ID3D11Device2::GetResourceTiling */
    void (NPT_STDMETHODCALLTYPE *GetResourceTiling)(void *self, ID3D11Resource * pTiledResource, UINT * pNumTilesForEntireResource, D3D11_PACKED_MIP_DESC * pPackedMipDesc, D3D11_TILE_SHAPE * pStandardTileShapeForNonPackedMips, UINT * pNumSubresourceTilings, UINT FirstSubresourceTilingToGet, D3D11_SUBRESOURCE_TILING * pSubresourceTilingsForNonPackedMips);
    /* slot 53: ID3D11Device2::CheckMultisampleQualityLevels1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckMultisampleQualityLevels1)(void *self, DXGI_FORMAT Format, UINT SampleCount, UINT Flags, UINT * pNumQualityLevels);
    /* slot 54: ID3D11Device3::CreateTexture2D1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture2D1)(void *self, const D3D11_TEXTURE2D_DESC1 * pDesc1, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture2D1 ** ppTexture2D);
    /* slot 55: ID3D11Device3::CreateTexture3D1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateTexture3D1)(void *self, const D3D11_TEXTURE3D_DESC1 * pDesc1, const D3D11_SUBRESOURCE_DATA * pInitialData, ID3D11Texture3D1 ** ppTexture3D);
    /* slot 56: ID3D11Device3::CreateRasterizerState2 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRasterizerState2)(void *self, const D3D11_RASTERIZER_DESC2 * pRasterizerDesc, ID3D11RasterizerState2 ** ppRasterizerState);
    /* slot 57: ID3D11Device3::CreateShaderResourceView1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateShaderResourceView1)(void *self, ID3D11Resource * pResource, const D3D11_SHADER_RESOURCE_VIEW_DESC1 * pDesc1, ID3D11ShaderResourceView1 ** ppSRView1);
    /* slot 58: ID3D11Device3::CreateUnorderedAccessView1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateUnorderedAccessView1)(void *self, ID3D11Resource * pResource, const D3D11_UNORDERED_ACCESS_VIEW_DESC1 * pDesc1, ID3D11UnorderedAccessView1 ** ppUAView1);
    /* slot 59: ID3D11Device3::CreateRenderTargetView1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateRenderTargetView1)(void *self, ID3D11Resource * pResource, const D3D11_RENDER_TARGET_VIEW_DESC1 * pDesc1, ID3D11RenderTargetView1 ** ppRTView1);
    /* slot 60: ID3D11Device3::CreateQuery1 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateQuery1)(void *self, const D3D11_QUERY_DESC1 * pQueryDesc1, ID3D11Query1 ** ppQuery1);
    /* slot 61: ID3D11Device3::GetImmediateContext3 */
    void (NPT_STDMETHODCALLTYPE *GetImmediateContext3)(void *self, ID3D11DeviceContext3 ** ppImmediateContext);
    /* slot 62: ID3D11Device3::CreateDeferredContext3 */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateDeferredContext3)(void *self, UINT ContextFlags, ID3D11DeviceContext3 ** ppDeferredContext);
    /* slot 63: ID3D11Device3::WriteToSubresource */
    void (NPT_STDMETHODCALLTYPE *WriteToSubresource)(void *self, ID3D11Resource * pDstResource, UINT DstSubresource, const D3D11_BOX * pDstBox, const void * pSrcData, UINT SrcRowPitch, UINT SrcDepthPitch);
    /* slot 64: ID3D11Device3::ReadFromSubresource */
    void (NPT_STDMETHODCALLTYPE *ReadFromSubresource)(void *self, void * pDstData, UINT DstRowPitch, UINT DstDepthPitch, ID3D11Resource * pSrcResource, UINT SrcSubresource, const D3D11_BOX * pSrcBox);
    /* slot 65: ID3D11Device4::RegisterDeviceRemovedEvent */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterDeviceRemovedEvent)(void *self, HANDLE hEvent, DWORD * pdwCookie);
    /* slot 66: ID3D11Device4::UnregisterDeviceRemoved */
    void (NPT_STDMETHODCALLTYPE *UnregisterDeviceRemoved)(void *self, DWORD dwCookie);
    /* slot 67: ID3D11Device5::OpenSharedFence */
    HRESULT (NPT_STDMETHODCALLTYPE *OpenSharedFence)(void *self, HANDLE hFence, const IID * ReturnedInterface, void ** ppFence);
    /* slot 68: ID3D11Device5::CreateFence */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateFence)(void *self, UINT64 InitialValue, D3D11_FENCE_FLAG Flags, const IID * ReturnedInterface, void ** ppFence);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device5_default_OpenSharedFence(void *self, HANDLE hFence, const IID * ReturnedInterface, void ** ppFence);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device5_default_CreateFence(void *self, UINT64 InitialValue, D3D11_FENCE_FLAG Flags, const IID * ReturnedInterface, void ** ppFence);

/* Default IUnknown thunks for ID3D11Device5.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11device5_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_id3d11device5_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_id3d11device5_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_id3d11device5_fill_default_vtbl(struct npt_id3d11device5_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_id3d11device5_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_id3d11device5_client_vtbl npt_id3d11device5_default_vtbl_storage;
extern void
npt_id3d11device5_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_id3d11device5_client_create(struct npt_device *dev, uint64_t host_id);


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_CLIENT_ID3D11DEVICE_H */
