/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Client-side COM implementation for id3d11classlinkage: out-of-line default
 * thunks, default vtable populators, and default constructors for every
 * interface in this family.
 */

#include "npt_protocol_client_id3d11classlinkage.h"
#include "npt_com.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-variable"



/* ================================================================== */
/* ID3D11ClassLinkage                                                       */
/* ================================================================== */

/* Parent IID chain for QueryInterface fast-path.  NULL-terminated list of
 * IID pointers; QI returns self for any IID in this list. */
static const GUID *const npt_id3d11classlinkage_parent_iids[] = {
    &NPT_IID_IUnknown,
    &NPT_IID_ID3D11DeviceChild,
    &NPT_IID_ID3D11ClassLinkage,
    NULL,
};

HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11classlinkage_default_QueryInterface(void *self, REFIID riid, void **ppvObject)
{
    HRESULT hr = npt_com_default_query_interface_chain(
        self, riid, ppvObject, npt_id3d11classlinkage_parent_iids);
    if (hr == NPT_S_OK)
        return hr;
    /* Derived/sibling IIDs are resolved against the host object, one
     * wire round trip per (object, IID) lifetime: the runtime memoizes
     * the verdict and the wrapper on `self` (npt_com.c). */
    return npt_com_query_interface_host(self, riid, ppvObject);
}

ULONG NPT_STDMETHODCALLTYPE
npt_id3d11classlinkage_default_AddRef(void *self)
{
    return npt_com_default_addref(self);
}

ULONG NPT_STDMETHODCALLTYPE
npt_id3d11classlinkage_default_Release(void *self)
{
    return npt_com_default_release(self);
}

HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11classlinkage_default_GetClassInstance(void *self, const CHAR * pClassInstanceName, UINT InstanceIndex, ID3D11ClassInstance ** ppInstance)
{
    ID3D11ClassInstance *_raw_ppInstance = NULL;
    /* Redirect each single-output pointer to a local _raw_ slot so the
     * encoder's stashed guest_id lands somewhere we can read after the
     * submit returns; the original caller-side pointers are restored
     * with the wrapped result at the end. */
    ID3D11ClassInstance **_orig_ppInstance = ppInstance;
    if (ppInstance)
        ppInstance = (ID3D11ClassInstance **)&_raw_ppInstance;
    /* Runtime-conditional sync: with multi_ring_enabled the caller may
     * use the new handle on a different ring, so we must wait for the
     * host register.  With multi_ring off, all traffic is FIFO-ordered
     * on primary and async is race-free. */
    HRESULT _ret;
    if (npt_com_self_device(self)->multi_ring_enabled) {
        _ret = npt_call_ID3D11ClassLinkage_GetClassInstance(npt_com_self_ring(self),npt_com_self_id(self),pClassInstanceName,InstanceIndex,ppInstance);
    } else {
        npt_async_ID3D11ClassLinkage_GetClassInstance(npt_com_self_ring(self),npt_com_self_id(self),pClassInstanceName,InstanceIndex,ppInstance);
        _ret = (HRESULT)0;  /* deferred-fatal: assume S_OK */
    }
    if (_orig_ppInstance) {
        /* Sync HRESULT: discard the stashed id on failure -- the host
         * won't have registered it, so any wrapper we build would be
         * bogus.  Under the deferred-fatal model an unregistered id
         * surfaces at first use, but returning the right HRESULT here
         * lets well-behaved callers short-circuit without an allocation. */
        if (NPT_SUCCEEDED((HRESULT)_ret) && _raw_ppInstance)
            *_orig_ppInstance = (ID3D11ClassInstance *)npt_com_get_or_wrap(
                npt_com_self_device(self),
                &NPT_IID_ID3D11ClassInstance,
                (uint64_t)(uintptr_t)_raw_ppInstance,
                (struct npt_com_base *)self);
        else
            *_orig_ppInstance = NULL;
    }
    return _ret;
}

HRESULT NPT_STDMETHODCALLTYPE
npt_id3d11classlinkage_default_CreateClassInstance(void *self, const CHAR * pClassTypeName, UINT ConstantBufferOffset, UINT ConstantVectorOffset, UINT TextureOffset, UINT SamplerOffset, ID3D11ClassInstance ** ppInstance)
{
    ID3D11ClassInstance *_raw_ppInstance = NULL;
    /* Redirect each single-output pointer to a local _raw_ slot so the
     * encoder's stashed guest_id lands somewhere we can read after the
     * submit returns; the original caller-side pointers are restored
     * with the wrapped result at the end. */
    ID3D11ClassInstance **_orig_ppInstance = ppInstance;
    if (ppInstance)
        ppInstance = (ID3D11ClassInstance **)&_raw_ppInstance;
    /* Runtime-conditional sync: with multi_ring_enabled the caller may
     * use the new handle on a different ring, so we must wait for the
     * host register.  With multi_ring off, all traffic is FIFO-ordered
     * on primary and async is race-free. */
    HRESULT _ret;
    if (npt_com_self_device(self)->multi_ring_enabled) {
        _ret = npt_call_ID3D11ClassLinkage_CreateClassInstance(npt_com_self_ring(self),npt_com_self_id(self),pClassTypeName,ConstantBufferOffset,ConstantVectorOffset,TextureOffset,SamplerOffset,ppInstance);
    } else {
        npt_async_ID3D11ClassLinkage_CreateClassInstance(npt_com_self_ring(self),npt_com_self_id(self),pClassTypeName,ConstantBufferOffset,ConstantVectorOffset,TextureOffset,SamplerOffset,ppInstance);
        _ret = (HRESULT)0;  /* deferred-fatal: assume S_OK */
    }
    if (_orig_ppInstance) {
        /* Sync HRESULT: discard the stashed id on failure -- the host
         * won't have registered it, so any wrapper we build would be
         * bogus.  Under the deferred-fatal model an unregistered id
         * surfaces at first use, but returning the right HRESULT here
         * lets well-behaved callers short-circuit without an allocation. */
        if (NPT_SUCCEEDED((HRESULT)_ret) && _raw_ppInstance)
            *_orig_ppInstance = (ID3D11ClassInstance *)npt_com_get_or_wrap(
                npt_com_self_device(self),
                &NPT_IID_ID3D11ClassInstance,
                (uint64_t)(uintptr_t)_raw_ppInstance,
                (struct npt_com_base *)self);
        else
            *_orig_ppInstance = NULL;
    }
    return _ret;
}


void
npt_id3d11classlinkage_fill_default_vtbl(struct npt_id3d11classlinkage_client_vtbl *dst)
{
    dst->QueryInterface = npt_id3d11classlinkage_default_QueryInterface;
    dst->AddRef         = npt_id3d11classlinkage_default_AddRef;
    dst->Release        = npt_id3d11classlinkage_default_Release;
    dst->GetDevice = npt_id3d11devicechild_default_GetDevice;
    dst->GetPrivateData = npt_id3d11devicechild_default_GetPrivateData;
    dst->SetPrivateData = npt_id3d11devicechild_default_SetPrivateData;
    dst->SetPrivateDataInterface = npt_id3d11devicechild_default_SetPrivateDataInterface;
    dst->GetClassInstance = npt_id3d11classlinkage_default_GetClassInstance;
    dst->CreateClassInstance = npt_id3d11classlinkage_default_CreateClassInstance;
}

/*
 * Per-interface default vtbl storage.  Populated by
 * npt_id3d11classlinkage_install_default_vtbl(), which is called once at
 * runtime init time from the global client_table init function.
 */
struct npt_id3d11classlinkage_client_vtbl npt_id3d11classlinkage_default_vtbl_storage;

void
npt_id3d11classlinkage_install_default_vtbl(void)
{
    npt_id3d11classlinkage_fill_default_vtbl(&npt_id3d11classlinkage_default_vtbl_storage);
}

void *
npt_id3d11classlinkage_client_create(struct npt_device *dev, uint64_t host_id)
{
    struct npt_com_base *p = (struct npt_com_base *)npt_alloc(sizeof(*p));
    if (!p)
        return NULL;
    npt_com_base_init(p,
        (const void **)&npt_id3d11classlinkage_default_vtbl_storage,
        dev, host_id);
    return p;
}


#pragma GCC diagnostic pop
