/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d12workgraphproperties.
 */

#ifndef NPT_PROTOCOL_GUEST_ID3D12WORKGRAPHPROPERTIES_H
#define NPT_PROTOCOL_GUEST_ID3D12WORKGRAPHPROPERTIES_H

#include "npt_protocol_guest_structs.h"
/* For npt_com_allocate_next_id -- called inline from every output
 * COM handle's encode path. */
#include "npt_protocol_guest_cs.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D12WorkGraphProperties::GetNumWorkGraphs
 */

struct npt_command_ID3D12WorkGraphProperties_GetNumWorkGraphs {
    void *_self;
    UINT ret;
};

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetNumWorkGraphs(void)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    return cmd_size;
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetNumWorkGraphs(struct npt_cs_encoder *enc,
                                                      uint32_t cmd_flags,
                                                      npt_object_id object_id)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12WorkGraphProperties_GetNumWorkGraphs();
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetNumWorkGraphs),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
}

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetNumWorkGraphs_reply(void)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
    return cmd_size;
}

static inline void
npt_decode_ID3D12WorkGraphProperties_GetNumWorkGraphs_reply(struct npt_cs_decoder *dec,
                                                            UINT *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                                  NPT_METHOD_ID3D12WorkGraphProperties_GetNumWorkGraphs))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D12WorkGraphProperties_GetNumWorkGraphs reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                       NPT_METHOD_ID3D12WorkGraphProperties_GetNumWorkGraphs));
        if (ret) *ret = (UINT)0;
        return;
    }
    if (ret) *ret = (UINT)_reply.cmd_return;
}

static inline void
npt_submit_ID3D12WorkGraphProperties_GetNumWorkGraphs(struct npt_ring *ring,
                                                      uint32_t cmd_flags,
                                                      npt_object_id object_id,
                                                      struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12WorkGraphProperties_GetNumWorkGraphs();
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12WorkGraphProperties_GetNumWorkGraphs_reply()
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12WorkGraphProperties_GetNumWorkGraphs(enc, cmd_flags, object_id);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12WorkGraphProperties_GetNumWorkGraphs(struct npt_ring *ring,
                                                     npt_object_id object_id)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetNumWorkGraphs(ring, 0, object_id, &submit);
}

static inline UINT
npt_call_ID3D12WorkGraphProperties_GetNumWorkGraphs(struct npt_ring *ring,
                                                    npt_object_id object_id)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetNumWorkGraphs(ring, NPT_CMD_FLAG_REPLY, object_id, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        UINT _ret;
        npt_decode_ID3D12WorkGraphProperties_GetNumWorkGraphs_reply(dec, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (UINT)0;
    }
}

/*
 * ID3D12WorkGraphProperties::GetProgramName
 */

struct npt_command_ID3D12WorkGraphProperties_GetProgramName {
    void *_self;
    UINT WorkGraphIndex;
    WCHAR ret;
};

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetProgramName(const UINT WorkGraphIndex)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_UINT(&WorkGraphIndex, max_mode);
    return cmd_size;
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetProgramName(struct npt_cs_encoder *enc,
                                                    uint32_t cmd_flags,
                                                    npt_object_id object_id,
                                                    UINT WorkGraphIndex)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12WorkGraphProperties_GetProgramName(WorkGraphIndex);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetProgramName),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_UINT(enc, &WorkGraphIndex);
}

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetProgramName_reply(const UINT WorkGraphIndex)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip WorkGraphIndex (input only) */
    return cmd_size;
}

static inline void
npt_decode_ID3D12WorkGraphProperties_GetProgramName_reply(struct npt_cs_decoder *dec,
                                                          WCHAR *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                                  NPT_METHOD_ID3D12WorkGraphProperties_GetProgramName))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D12WorkGraphProperties_GetProgramName reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                       NPT_METHOD_ID3D12WorkGraphProperties_GetProgramName));
        if (ret) *ret = (WCHAR)0;
        return;
    }
    if (ret) *ret = (WCHAR)_reply.cmd_return;
}

static inline void
npt_submit_ID3D12WorkGraphProperties_GetProgramName(struct npt_ring *ring,
                                                    uint32_t cmd_flags,
                                                    npt_object_id object_id,
                                                    UINT WorkGraphIndex,
                                                    struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12WorkGraphProperties_GetProgramName(WorkGraphIndex);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12WorkGraphProperties_GetProgramName_reply(WorkGraphIndex)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12WorkGraphProperties_GetProgramName(enc, cmd_flags, object_id, WorkGraphIndex);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12WorkGraphProperties_GetProgramName(struct npt_ring *ring,
                                                   npt_object_id object_id,
                                                   UINT WorkGraphIndex)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetProgramName(ring, 0, object_id, WorkGraphIndex, &submit);
}

static inline WCHAR
npt_call_ID3D12WorkGraphProperties_GetProgramName(struct npt_ring *ring,
                                                  npt_object_id object_id,
                                                  UINT WorkGraphIndex)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetProgramName(ring, NPT_CMD_FLAG_REPLY, object_id, WorkGraphIndex, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        WCHAR _ret;
        npt_decode_ID3D12WorkGraphProperties_GetProgramName_reply(dec, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (WCHAR)0;
    }
}

/*
 * ID3D12WorkGraphProperties::GetWorkGraphIndex
 */

struct npt_command_ID3D12WorkGraphProperties_GetWorkGraphIndex {
    void *_self;
    const WCHAR * pProgramName;
    UINT ret;
};

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetWorkGraphIndex(const WCHAR * pProgramName)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    if (pProgramName) {
        const size_t _wstr_size = (npt_wcslen((const WCHAR *)pProgramName) + 1) * sizeof(WCHAR);
        cmd_size += npt_sizeof_array_count(_wstr_size);
        cmd_size += npt_sizeof_blob_array(pProgramName, _wstr_size);
    } else {
        cmd_size += npt_sizeof_array_count(0);
    }
    return cmd_size;
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetWorkGraphIndex(struct npt_cs_encoder *enc,
                                                       uint32_t cmd_flags,
                                                       npt_object_id object_id,
                                                       const WCHAR * pProgramName)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12WorkGraphProperties_GetWorkGraphIndex(pProgramName);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetWorkGraphIndex),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    if (pProgramName) {
        const size_t _wstr_size = (npt_wcslen((const WCHAR *)pProgramName) + 1) * sizeof(WCHAR);
        npt_encode_array_count(enc, _wstr_size);
        npt_encode_blob_array(enc, pProgramName, _wstr_size);
    } else {
        npt_encode_array_count(enc, 0);
    }
}

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetWorkGraphIndex_reply(const WCHAR * pProgramName)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip pProgramName (input only) */
    return cmd_size;
}

static inline void
npt_decode_ID3D12WorkGraphProperties_GetWorkGraphIndex_reply(struct npt_cs_decoder *dec,
                                                             UINT *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                                  NPT_METHOD_ID3D12WorkGraphProperties_GetWorkGraphIndex))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D12WorkGraphProperties_GetWorkGraphIndex reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                       NPT_METHOD_ID3D12WorkGraphProperties_GetWorkGraphIndex));
        if (ret) *ret = (UINT)0;
        return;
    }
    if (ret) *ret = (UINT)_reply.cmd_return;
}

static inline void
npt_submit_ID3D12WorkGraphProperties_GetWorkGraphIndex(struct npt_ring *ring,
                                                       uint32_t cmd_flags,
                                                       npt_object_id object_id,
                                                       const WCHAR * pProgramName,
                                                       struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12WorkGraphProperties_GetWorkGraphIndex(pProgramName);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12WorkGraphProperties_GetWorkGraphIndex_reply(pProgramName)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12WorkGraphProperties_GetWorkGraphIndex(enc, cmd_flags, object_id, pProgramName);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12WorkGraphProperties_GetWorkGraphIndex(struct npt_ring *ring,
                                                      npt_object_id object_id,
                                                      const WCHAR * pProgramName)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetWorkGraphIndex(ring, 0, object_id, pProgramName, &submit);
}

static inline UINT
npt_call_ID3D12WorkGraphProperties_GetWorkGraphIndex(struct npt_ring *ring,
                                                     npt_object_id object_id,
                                                     const WCHAR * pProgramName)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetWorkGraphIndex(ring, NPT_CMD_FLAG_REPLY, object_id, pProgramName, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        UINT _ret;
        npt_decode_ID3D12WorkGraphProperties_GetWorkGraphIndex_reply(dec, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (UINT)0;
    }
}

/*
 * ID3D12WorkGraphProperties::GetNumNodes
 */

struct npt_command_ID3D12WorkGraphProperties_GetNumNodes {
    void *_self;
    UINT WorkGraphIndex;
    UINT ret;
};

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetNumNodes(const UINT WorkGraphIndex)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_UINT(&WorkGraphIndex, max_mode);
    return cmd_size;
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetNumNodes(struct npt_cs_encoder *enc,
                                                 uint32_t cmd_flags,
                                                 npt_object_id object_id,
                                                 UINT WorkGraphIndex)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12WorkGraphProperties_GetNumNodes(WorkGraphIndex);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetNumNodes),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_UINT(enc, &WorkGraphIndex);
}

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetNumNodes_reply(const UINT WorkGraphIndex)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip WorkGraphIndex (input only) */
    return cmd_size;
}

static inline void
npt_decode_ID3D12WorkGraphProperties_GetNumNodes_reply(struct npt_cs_decoder *dec,
                                                       UINT *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                                  NPT_METHOD_ID3D12WorkGraphProperties_GetNumNodes))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D12WorkGraphProperties_GetNumNodes reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                       NPT_METHOD_ID3D12WorkGraphProperties_GetNumNodes));
        if (ret) *ret = (UINT)0;
        return;
    }
    if (ret) *ret = (UINT)_reply.cmd_return;
}

static inline void
npt_submit_ID3D12WorkGraphProperties_GetNumNodes(struct npt_ring *ring,
                                                 uint32_t cmd_flags,
                                                 npt_object_id object_id,
                                                 UINT WorkGraphIndex,
                                                 struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12WorkGraphProperties_GetNumNodes(WorkGraphIndex);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12WorkGraphProperties_GetNumNodes_reply(WorkGraphIndex)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12WorkGraphProperties_GetNumNodes(enc, cmd_flags, object_id, WorkGraphIndex);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12WorkGraphProperties_GetNumNodes(struct npt_ring *ring,
                                                npt_object_id object_id,
                                                UINT WorkGraphIndex)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetNumNodes(ring, 0, object_id, WorkGraphIndex, &submit);
}

static inline UINT
npt_call_ID3D12WorkGraphProperties_GetNumNodes(struct npt_ring *ring,
                                               npt_object_id object_id,
                                               UINT WorkGraphIndex)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetNumNodes(ring, NPT_CMD_FLAG_REPLY, object_id, WorkGraphIndex, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        UINT _ret;
        npt_decode_ID3D12WorkGraphProperties_GetNumNodes_reply(dec, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (UINT)0;
    }
}

/*
 * ID3D12WorkGraphProperties::GetNodeID
 */

struct npt_command_ID3D12WorkGraphProperties_GetNodeID {
    void *_self;
    UINT WorkGraphIndex;
    UINT NodeIndex;
    D3D12_NODE_ID ret;
};

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetNodeID(const UINT WorkGraphIndex,const UINT NodeIndex)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_UINT(&WorkGraphIndex, max_mode);
    cmd_size += npt_sizeof_UINT(&NodeIndex, max_mode);
    return cmd_size;
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetNodeID(struct npt_cs_encoder *enc,
                                               uint32_t cmd_flags,
                                               npt_object_id object_id,
                                               UINT WorkGraphIndex,
                                               UINT NodeIndex)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12WorkGraphProperties_GetNodeID(WorkGraphIndex,NodeIndex);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetNodeID),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_UINT(enc, &WorkGraphIndex);
    npt_encode_UINT(enc, &NodeIndex);
}

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetNodeID_reply(const UINT WorkGraphIndex,const UINT NodeIndex)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
    /* Reply has runtime-unbounded wire size; reserve only the header.
     * Host encode_reply sets the encoder fatal flag and the guest
     * decode path returns the documented default. */
    return cmd_size;
}

static inline void
npt_decode_ID3D12WorkGraphProperties_GetNodeID_reply(struct npt_cs_decoder *dec,
                                                     D3D12_NODE_ID *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                                  NPT_METHOD_ID3D12WorkGraphProperties_GetNodeID))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D12WorkGraphProperties_GetNodeID reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                       NPT_METHOD_ID3D12WorkGraphProperties_GetNodeID));
        if (ret) memset(ret, 0, sizeof(*ret));
        return;
    }
    if (ret) npt_decode_D3D12_NODE_ID(dec, ret);
}

static inline void
npt_submit_ID3D12WorkGraphProperties_GetNodeID(struct npt_ring *ring,
                                               uint32_t cmd_flags,
                                               npt_object_id object_id,
                                               UINT WorkGraphIndex,
                                               UINT NodeIndex,
                                               struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12WorkGraphProperties_GetNodeID(WorkGraphIndex,NodeIndex);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12WorkGraphProperties_GetNodeID_reply(WorkGraphIndex,NodeIndex)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12WorkGraphProperties_GetNodeID(enc, cmd_flags, object_id, WorkGraphIndex, NodeIndex);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12WorkGraphProperties_GetNodeID(struct npt_ring *ring,
                                              npt_object_id object_id,
                                              UINT WorkGraphIndex,
                                              UINT NodeIndex)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetNodeID(ring, 0, object_id, WorkGraphIndex, NodeIndex, &submit);
}

static inline D3D12_NODE_ID
npt_call_ID3D12WorkGraphProperties_GetNodeID(struct npt_ring *ring,
                                             npt_object_id object_id,
                                             UINT WorkGraphIndex,
                                             UINT NodeIndex)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetNodeID(ring, NPT_CMD_FLAG_REPLY, object_id, WorkGraphIndex, NodeIndex, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        D3D12_NODE_ID _ret;
        npt_decode_ID3D12WorkGraphProperties_GetNodeID_reply(dec, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (D3D12_NODE_ID){0};
    }
}

/*
 * ID3D12WorkGraphProperties::GetNodeIndex
 */

struct npt_command_ID3D12WorkGraphProperties_GetNodeIndex {
    void *_self;
    UINT WorkGraphIndex;
    D3D12_NODE_ID NodeID;
    UINT ret;
};

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetNodeIndex(const UINT WorkGraphIndex,const D3D12_NODE_ID NodeID)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_UINT(&WorkGraphIndex, max_mode);
    cmd_size += npt_sizeof_D3D12_NODE_ID(&NodeID, max_mode);
    return cmd_size;
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetNodeIndex(struct npt_cs_encoder *enc,
                                                  uint32_t cmd_flags,
                                                  npt_object_id object_id,
                                                  UINT WorkGraphIndex,
                                                  D3D12_NODE_ID NodeID)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12WorkGraphProperties_GetNodeIndex(WorkGraphIndex,NodeID);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetNodeIndex),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_UINT(enc, &WorkGraphIndex);
    npt_encode_D3D12_NODE_ID(enc, &NodeID);
}

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetNodeIndex_reply(const UINT WorkGraphIndex,const D3D12_NODE_ID NodeID)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip WorkGraphIndex (input only) */
/* skip NodeID (input only) */
    return cmd_size;
}

static inline void
npt_decode_ID3D12WorkGraphProperties_GetNodeIndex_reply(struct npt_cs_decoder *dec,
                                                        UINT *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                                  NPT_METHOD_ID3D12WorkGraphProperties_GetNodeIndex))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D12WorkGraphProperties_GetNodeIndex reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                       NPT_METHOD_ID3D12WorkGraphProperties_GetNodeIndex));
        if (ret) *ret = (UINT)0;
        return;
    }
    if (ret) *ret = (UINT)_reply.cmd_return;
}

static inline void
npt_submit_ID3D12WorkGraphProperties_GetNodeIndex(struct npt_ring *ring,
                                                  uint32_t cmd_flags,
                                                  npt_object_id object_id,
                                                  UINT WorkGraphIndex,
                                                  D3D12_NODE_ID NodeID,
                                                  struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12WorkGraphProperties_GetNodeIndex(WorkGraphIndex,NodeID);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12WorkGraphProperties_GetNodeIndex_reply(WorkGraphIndex,NodeID)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12WorkGraphProperties_GetNodeIndex(enc, cmd_flags, object_id, WorkGraphIndex, NodeID);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12WorkGraphProperties_GetNodeIndex(struct npt_ring *ring,
                                                 npt_object_id object_id,
                                                 UINT WorkGraphIndex,
                                                 D3D12_NODE_ID NodeID)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetNodeIndex(ring, 0, object_id, WorkGraphIndex, NodeID, &submit);
}

static inline UINT
npt_call_ID3D12WorkGraphProperties_GetNodeIndex(struct npt_ring *ring,
                                                npt_object_id object_id,
                                                UINT WorkGraphIndex,
                                                D3D12_NODE_ID NodeID)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetNodeIndex(ring, NPT_CMD_FLAG_REPLY, object_id, WorkGraphIndex, NodeID, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        UINT _ret;
        npt_decode_ID3D12WorkGraphProperties_GetNodeIndex_reply(dec, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (UINT)0;
    }
}

/*
 * ID3D12WorkGraphProperties::GetNodeLocalRootArgumentsTableIndex
 */

struct npt_command_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex {
    void *_self;
    UINT WorkGraphIndex;
    UINT NodeIndex;
    UINT ret;
};

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex(const UINT WorkGraphIndex,const UINT NodeIndex)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_UINT(&WorkGraphIndex, max_mode);
    cmd_size += npt_sizeof_UINT(&NodeIndex, max_mode);
    return cmd_size;
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex(struct npt_cs_encoder *enc,
                                                                         uint32_t cmd_flags,
                                                                         npt_object_id object_id,
                                                                         UINT WorkGraphIndex,
                                                                         UINT NodeIndex)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex(WorkGraphIndex,NodeIndex);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_UINT(enc, &WorkGraphIndex);
    npt_encode_UINT(enc, &NodeIndex);
}

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex_reply(const UINT WorkGraphIndex,const UINT NodeIndex)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip WorkGraphIndex (input only) */
/* skip NodeIndex (input only) */
    return cmd_size;
}

static inline void
npt_decode_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex_reply(struct npt_cs_decoder *dec,
                                                                               UINT *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                                  NPT_METHOD_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                       NPT_METHOD_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex));
        if (ret) *ret = (UINT)0;
        return;
    }
    if (ret) *ret = (UINT)_reply.cmd_return;
}

static inline void
npt_submit_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex(struct npt_ring *ring,
                                                                         uint32_t cmd_flags,
                                                                         npt_object_id object_id,
                                                                         UINT WorkGraphIndex,
                                                                         UINT NodeIndex,
                                                                         struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex(WorkGraphIndex,NodeIndex);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex_reply(WorkGraphIndex,NodeIndex)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex(enc, cmd_flags, object_id, WorkGraphIndex, NodeIndex);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex(struct npt_ring *ring,
                                                                        npt_object_id object_id,
                                                                        UINT WorkGraphIndex,
                                                                        UINT NodeIndex)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex(ring, 0, object_id, WorkGraphIndex, NodeIndex, &submit);
}

static inline UINT
npt_call_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex(struct npt_ring *ring,
                                                                       npt_object_id object_id,
                                                                       UINT WorkGraphIndex,
                                                                       UINT NodeIndex)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex(ring, NPT_CMD_FLAG_REPLY, object_id, WorkGraphIndex, NodeIndex, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        UINT _ret;
        npt_decode_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex_reply(dec, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (UINT)0;
    }
}

/*
 * ID3D12WorkGraphProperties::GetNumEntrypoints
 */

struct npt_command_ID3D12WorkGraphProperties_GetNumEntrypoints {
    void *_self;
    UINT WorkGraphIndex;
    UINT ret;
};

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetNumEntrypoints(const UINT WorkGraphIndex)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_UINT(&WorkGraphIndex, max_mode);
    return cmd_size;
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetNumEntrypoints(struct npt_cs_encoder *enc,
                                                       uint32_t cmd_flags,
                                                       npt_object_id object_id,
                                                       UINT WorkGraphIndex)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12WorkGraphProperties_GetNumEntrypoints(WorkGraphIndex);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetNumEntrypoints),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_UINT(enc, &WorkGraphIndex);
}

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetNumEntrypoints_reply(const UINT WorkGraphIndex)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip WorkGraphIndex (input only) */
    return cmd_size;
}

static inline void
npt_decode_ID3D12WorkGraphProperties_GetNumEntrypoints_reply(struct npt_cs_decoder *dec,
                                                             UINT *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                                  NPT_METHOD_ID3D12WorkGraphProperties_GetNumEntrypoints))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D12WorkGraphProperties_GetNumEntrypoints reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                       NPT_METHOD_ID3D12WorkGraphProperties_GetNumEntrypoints));
        if (ret) *ret = (UINT)0;
        return;
    }
    if (ret) *ret = (UINT)_reply.cmd_return;
}

static inline void
npt_submit_ID3D12WorkGraphProperties_GetNumEntrypoints(struct npt_ring *ring,
                                                       uint32_t cmd_flags,
                                                       npt_object_id object_id,
                                                       UINT WorkGraphIndex,
                                                       struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12WorkGraphProperties_GetNumEntrypoints(WorkGraphIndex);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12WorkGraphProperties_GetNumEntrypoints_reply(WorkGraphIndex)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12WorkGraphProperties_GetNumEntrypoints(enc, cmd_flags, object_id, WorkGraphIndex);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12WorkGraphProperties_GetNumEntrypoints(struct npt_ring *ring,
                                                      npt_object_id object_id,
                                                      UINT WorkGraphIndex)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetNumEntrypoints(ring, 0, object_id, WorkGraphIndex, &submit);
}

static inline UINT
npt_call_ID3D12WorkGraphProperties_GetNumEntrypoints(struct npt_ring *ring,
                                                     npt_object_id object_id,
                                                     UINT WorkGraphIndex)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetNumEntrypoints(ring, NPT_CMD_FLAG_REPLY, object_id, WorkGraphIndex, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        UINT _ret;
        npt_decode_ID3D12WorkGraphProperties_GetNumEntrypoints_reply(dec, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (UINT)0;
    }
}

/*
 * ID3D12WorkGraphProperties::GetEntrypointID
 */

struct npt_command_ID3D12WorkGraphProperties_GetEntrypointID {
    void *_self;
    UINT WorkGraphIndex;
    UINT EntrypointIndex;
    D3D12_NODE_ID ret;
};

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetEntrypointID(const UINT WorkGraphIndex,const UINT EntrypointIndex)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_UINT(&WorkGraphIndex, max_mode);
    cmd_size += npt_sizeof_UINT(&EntrypointIndex, max_mode);
    return cmd_size;
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetEntrypointID(struct npt_cs_encoder *enc,
                                                     uint32_t cmd_flags,
                                                     npt_object_id object_id,
                                                     UINT WorkGraphIndex,
                                                     UINT EntrypointIndex)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12WorkGraphProperties_GetEntrypointID(WorkGraphIndex,EntrypointIndex);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetEntrypointID),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_UINT(enc, &WorkGraphIndex);
    npt_encode_UINT(enc, &EntrypointIndex);
}

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetEntrypointID_reply(const UINT WorkGraphIndex,const UINT EntrypointIndex)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
    /* Reply has runtime-unbounded wire size; reserve only the header.
     * Host encode_reply sets the encoder fatal flag and the guest
     * decode path returns the documented default. */
    return cmd_size;
}

static inline void
npt_decode_ID3D12WorkGraphProperties_GetEntrypointID_reply(struct npt_cs_decoder *dec,
                                                           D3D12_NODE_ID *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                                  NPT_METHOD_ID3D12WorkGraphProperties_GetEntrypointID))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D12WorkGraphProperties_GetEntrypointID reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                       NPT_METHOD_ID3D12WorkGraphProperties_GetEntrypointID));
        if (ret) memset(ret, 0, sizeof(*ret));
        return;
    }
    if (ret) npt_decode_D3D12_NODE_ID(dec, ret);
}

static inline void
npt_submit_ID3D12WorkGraphProperties_GetEntrypointID(struct npt_ring *ring,
                                                     uint32_t cmd_flags,
                                                     npt_object_id object_id,
                                                     UINT WorkGraphIndex,
                                                     UINT EntrypointIndex,
                                                     struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12WorkGraphProperties_GetEntrypointID(WorkGraphIndex,EntrypointIndex);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12WorkGraphProperties_GetEntrypointID_reply(WorkGraphIndex,EntrypointIndex)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12WorkGraphProperties_GetEntrypointID(enc, cmd_flags, object_id, WorkGraphIndex, EntrypointIndex);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12WorkGraphProperties_GetEntrypointID(struct npt_ring *ring,
                                                    npt_object_id object_id,
                                                    UINT WorkGraphIndex,
                                                    UINT EntrypointIndex)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetEntrypointID(ring, 0, object_id, WorkGraphIndex, EntrypointIndex, &submit);
}

static inline D3D12_NODE_ID
npt_call_ID3D12WorkGraphProperties_GetEntrypointID(struct npt_ring *ring,
                                                   npt_object_id object_id,
                                                   UINT WorkGraphIndex,
                                                   UINT EntrypointIndex)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetEntrypointID(ring, NPT_CMD_FLAG_REPLY, object_id, WorkGraphIndex, EntrypointIndex, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        D3D12_NODE_ID _ret;
        npt_decode_ID3D12WorkGraphProperties_GetEntrypointID_reply(dec, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (D3D12_NODE_ID){0};
    }
}

/*
 * ID3D12WorkGraphProperties::GetEntrypointIndex
 */

struct npt_command_ID3D12WorkGraphProperties_GetEntrypointIndex {
    void *_self;
    UINT WorkGraphIndex;
    D3D12_NODE_ID NodeID;
    UINT ret;
};

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetEntrypointIndex(const UINT WorkGraphIndex,const D3D12_NODE_ID NodeID)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_UINT(&WorkGraphIndex, max_mode);
    cmd_size += npt_sizeof_D3D12_NODE_ID(&NodeID, max_mode);
    return cmd_size;
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetEntrypointIndex(struct npt_cs_encoder *enc,
                                                        uint32_t cmd_flags,
                                                        npt_object_id object_id,
                                                        UINT WorkGraphIndex,
                                                        D3D12_NODE_ID NodeID)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12WorkGraphProperties_GetEntrypointIndex(WorkGraphIndex,NodeID);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetEntrypointIndex),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_UINT(enc, &WorkGraphIndex);
    npt_encode_D3D12_NODE_ID(enc, &NodeID);
}

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetEntrypointIndex_reply(const UINT WorkGraphIndex,const D3D12_NODE_ID NodeID)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip WorkGraphIndex (input only) */
/* skip NodeID (input only) */
    return cmd_size;
}

static inline void
npt_decode_ID3D12WorkGraphProperties_GetEntrypointIndex_reply(struct npt_cs_decoder *dec,
                                                              UINT *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                                  NPT_METHOD_ID3D12WorkGraphProperties_GetEntrypointIndex))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D12WorkGraphProperties_GetEntrypointIndex reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                       NPT_METHOD_ID3D12WorkGraphProperties_GetEntrypointIndex));
        if (ret) *ret = (UINT)0;
        return;
    }
    if (ret) *ret = (UINT)_reply.cmd_return;
}

static inline void
npt_submit_ID3D12WorkGraphProperties_GetEntrypointIndex(struct npt_ring *ring,
                                                        uint32_t cmd_flags,
                                                        npt_object_id object_id,
                                                        UINT WorkGraphIndex,
                                                        D3D12_NODE_ID NodeID,
                                                        struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12WorkGraphProperties_GetEntrypointIndex(WorkGraphIndex,NodeID);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12WorkGraphProperties_GetEntrypointIndex_reply(WorkGraphIndex,NodeID)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12WorkGraphProperties_GetEntrypointIndex(enc, cmd_flags, object_id, WorkGraphIndex, NodeID);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12WorkGraphProperties_GetEntrypointIndex(struct npt_ring *ring,
                                                       npt_object_id object_id,
                                                       UINT WorkGraphIndex,
                                                       D3D12_NODE_ID NodeID)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetEntrypointIndex(ring, 0, object_id, WorkGraphIndex, NodeID, &submit);
}

static inline UINT
npt_call_ID3D12WorkGraphProperties_GetEntrypointIndex(struct npt_ring *ring,
                                                      npt_object_id object_id,
                                                      UINT WorkGraphIndex,
                                                      D3D12_NODE_ID NodeID)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetEntrypointIndex(ring, NPT_CMD_FLAG_REPLY, object_id, WorkGraphIndex, NodeID, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        UINT _ret;
        npt_decode_ID3D12WorkGraphProperties_GetEntrypointIndex_reply(dec, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (UINT)0;
    }
}

/*
 * ID3D12WorkGraphProperties::GetEntrypointRecordSizeInBytes
 */

struct npt_command_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes {
    void *_self;
    UINT WorkGraphIndex;
    UINT EntrypointIndex;
    UINT ret;
};

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes(const UINT WorkGraphIndex,const UINT EntrypointIndex)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_UINT(&WorkGraphIndex, max_mode);
    cmd_size += npt_sizeof_UINT(&EntrypointIndex, max_mode);
    return cmd_size;
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes(struct npt_cs_encoder *enc,
                                                                    uint32_t cmd_flags,
                                                                    npt_object_id object_id,
                                                                    UINT WorkGraphIndex,
                                                                    UINT EntrypointIndex)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes(WorkGraphIndex,EntrypointIndex);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_UINT(enc, &WorkGraphIndex);
    npt_encode_UINT(enc, &EntrypointIndex);
}

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes_reply(const UINT WorkGraphIndex,const UINT EntrypointIndex)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip WorkGraphIndex (input only) */
/* skip EntrypointIndex (input only) */
    return cmd_size;
}

static inline void
npt_decode_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes_reply(struct npt_cs_decoder *dec,
                                                                          UINT *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                                  NPT_METHOD_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                       NPT_METHOD_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes));
        if (ret) *ret = (UINT)0;
        return;
    }
    if (ret) *ret = (UINT)_reply.cmd_return;
}

static inline void
npt_submit_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes(struct npt_ring *ring,
                                                                    uint32_t cmd_flags,
                                                                    npt_object_id object_id,
                                                                    UINT WorkGraphIndex,
                                                                    UINT EntrypointIndex,
                                                                    struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes(WorkGraphIndex,EntrypointIndex);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes_reply(WorkGraphIndex,EntrypointIndex)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes(enc, cmd_flags, object_id, WorkGraphIndex, EntrypointIndex);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes(struct npt_ring *ring,
                                                                   npt_object_id object_id,
                                                                   UINT WorkGraphIndex,
                                                                   UINT EntrypointIndex)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes(ring, 0, object_id, WorkGraphIndex, EntrypointIndex, &submit);
}

static inline UINT
npt_call_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes(struct npt_ring *ring,
                                                                  npt_object_id object_id,
                                                                  UINT WorkGraphIndex,
                                                                  UINT EntrypointIndex)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes(ring, NPT_CMD_FLAG_REPLY, object_id, WorkGraphIndex, EntrypointIndex, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        UINT _ret;
        npt_decode_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes_reply(dec, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (UINT)0;
    }
}

/*
 * ID3D12WorkGraphProperties::GetWorkGraphMemoryRequirements
 */

struct npt_command_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements {
    void *_self;
    UINT WorkGraphIndex;
    D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS * pWorkGraphMemoryRequirements;
};

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements(const UINT WorkGraphIndex,const D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS * pWorkGraphMemoryRequirements)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_UINT(&WorkGraphIndex, max_mode);
/* skip pWorkGraphMemoryRequirements (output only) */
    return cmd_size;
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements(struct npt_cs_encoder *enc,
                                                                    uint32_t cmd_flags,
                                                                    npt_object_id object_id,
                                                                    UINT WorkGraphIndex,
                                                                    D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS * pWorkGraphMemoryRequirements)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements(WorkGraphIndex,pWorkGraphMemoryRequirements);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_UINT(enc, &WorkGraphIndex);
/* skip pWorkGraphMemoryRequirements (output only) */
}

static inline size_t
npt_sizeof_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements_reply(const UINT WorkGraphIndex,const D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS * pWorkGraphMemoryRequirements)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip WorkGraphIndex (input only) */
    cmd_size += npt_sizeof_simple_pointer((const void *)1);
    cmd_size += npt_sizeof_D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS(&(const D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS){0}, 1);
    return cmd_size;
}

static inline void
npt_decode_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements_reply(struct npt_cs_decoder *dec,
                                                                          D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS * pWorkGraphMemoryRequirements)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                                  NPT_METHOD_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                       NPT_METHOD_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements));
        return;
    }
    if (npt_decode_simple_pointer(dec)) {
        if (pWorkGraphMemoryRequirements)
            npt_decode_D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS(dec, (D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS *)pWorkGraphMemoryRequirements);
    }
}

static inline void
npt_submit_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements(struct npt_ring *ring,
                                                                    uint32_t cmd_flags,
                                                                    npt_object_id object_id,
                                                                    UINT WorkGraphIndex,
                                                                    D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS * pWorkGraphMemoryRequirements,
                                                                    struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements(WorkGraphIndex,pWorkGraphMemoryRequirements);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements_reply(WorkGraphIndex,pWorkGraphMemoryRequirements)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements(enc, cmd_flags, object_id, WorkGraphIndex, pWorkGraphMemoryRequirements);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements(struct npt_ring *ring,
                                                                   npt_object_id object_id,
                                                                   UINT WorkGraphIndex,
                                                                   D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS * pWorkGraphMemoryRequirements)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements(ring, 0, object_id, WorkGraphIndex, pWorkGraphMemoryRequirements, &submit);
}

static inline void
npt_call_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements(struct npt_ring *ring,
                                                                  npt_object_id object_id,
                                                                  UINT WorkGraphIndex,
                                                                  D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS * pWorkGraphMemoryRequirements)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements(ring, NPT_CMD_FLAG_REPLY, object_id, WorkGraphIndex, pWorkGraphMemoryRequirements, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        npt_decode_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements_reply(dec, pWorkGraphMemoryRequirements);
        npt_ring_free_command_reply(ring, &submit);
    }
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_GUEST_ID3D12WORKGRAPHPROPERTIES_H */
