/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d12deviceremovedextendeddatasettings.
 */

#ifndef NPT_PROTOCOL_GUEST_ID3D12DEVICEREMOVEDEXTENDEDDATASETTINGS_H
#define NPT_PROTOCOL_GUEST_ID3D12DEVICEREMOVEDEXTENDEDDATASETTINGS_H

#include "npt_protocol_guest_structs.h"
/* For npt_com_allocate_next_id -- called inline from every output
 * COM handle's encode path. */
#include "npt_protocol_guest_cs.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D12DeviceRemovedExtendedDataSettings::SetAutoBreadcrumbsEnablement
 */

struct npt_command_ID3D12DeviceRemovedExtendedDataSettings_SetAutoBreadcrumbsEnablement {
    void *_self;
    D3D12_DRED_ENABLEMENT Enablement;
};

static inline size_t
npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings_SetAutoBreadcrumbsEnablement(const D3D12_DRED_ENABLEMENT Enablement)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_D3D12_DRED_ENABLEMENT(&Enablement, max_mode);
    return cmd_size;
}

static inline void
npt_encode_ID3D12DeviceRemovedExtendedDataSettings_SetAutoBreadcrumbsEnablement(struct npt_cs_encoder *enc,
                                                                                uint32_t cmd_flags,
                                                                                npt_object_id object_id,
                                                                                D3D12_DRED_ENABLEMENT Enablement)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings_SetAutoBreadcrumbsEnablement(Enablement);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12DeviceRemovedExtendedDataSettings,
                                 NPT_METHOD_ID3D12DeviceRemovedExtendedDataSettings_SetAutoBreadcrumbsEnablement),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_D3D12_DRED_ENABLEMENT(enc, &Enablement);
}

static inline size_t
npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings_SetAutoBreadcrumbsEnablement_reply(const D3D12_DRED_ENABLEMENT Enablement)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip Enablement (input only) */
    return cmd_size;
}

static inline void
npt_submit_ID3D12DeviceRemovedExtendedDataSettings_SetAutoBreadcrumbsEnablement(struct npt_ring *ring,
                                                                                uint32_t cmd_flags,
                                                                                npt_object_id object_id,
                                                                                D3D12_DRED_ENABLEMENT Enablement,
                                                                                struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings_SetAutoBreadcrumbsEnablement(Enablement);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings_SetAutoBreadcrumbsEnablement_reply(Enablement)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12DeviceRemovedExtendedDataSettings_SetAutoBreadcrumbsEnablement(enc, cmd_flags, object_id, Enablement);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12DeviceRemovedExtendedDataSettings_SetAutoBreadcrumbsEnablement(struct npt_ring *ring,
                                                                               npt_object_id object_id,
                                                                               D3D12_DRED_ENABLEMENT Enablement)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12DeviceRemovedExtendedDataSettings_SetAutoBreadcrumbsEnablement(ring, 0, object_id, Enablement, &submit);
}

static inline void
npt_call_ID3D12DeviceRemovedExtendedDataSettings_SetAutoBreadcrumbsEnablement(struct npt_ring *ring,
                                                                              npt_object_id object_id,
                                                                              D3D12_DRED_ENABLEMENT Enablement)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12DeviceRemovedExtendedDataSettings_SetAutoBreadcrumbsEnablement(ring, NPT_CMD_FLAG_REPLY, object_id, Enablement, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        npt_ring_free_command_reply(ring, &submit);
    }
}

/*
 * ID3D12DeviceRemovedExtendedDataSettings::SetPageFaultEnablement
 */

struct npt_command_ID3D12DeviceRemovedExtendedDataSettings_SetPageFaultEnablement {
    void *_self;
    D3D12_DRED_ENABLEMENT Enablement;
};

static inline size_t
npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings_SetPageFaultEnablement(const D3D12_DRED_ENABLEMENT Enablement)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_D3D12_DRED_ENABLEMENT(&Enablement, max_mode);
    return cmd_size;
}

static inline void
npt_encode_ID3D12DeviceRemovedExtendedDataSettings_SetPageFaultEnablement(struct npt_cs_encoder *enc,
                                                                          uint32_t cmd_flags,
                                                                          npt_object_id object_id,
                                                                          D3D12_DRED_ENABLEMENT Enablement)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings_SetPageFaultEnablement(Enablement);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12DeviceRemovedExtendedDataSettings,
                                 NPT_METHOD_ID3D12DeviceRemovedExtendedDataSettings_SetPageFaultEnablement),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_D3D12_DRED_ENABLEMENT(enc, &Enablement);
}

static inline size_t
npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings_SetPageFaultEnablement_reply(const D3D12_DRED_ENABLEMENT Enablement)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip Enablement (input only) */
    return cmd_size;
}

static inline void
npt_submit_ID3D12DeviceRemovedExtendedDataSettings_SetPageFaultEnablement(struct npt_ring *ring,
                                                                          uint32_t cmd_flags,
                                                                          npt_object_id object_id,
                                                                          D3D12_DRED_ENABLEMENT Enablement,
                                                                          struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings_SetPageFaultEnablement(Enablement);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings_SetPageFaultEnablement_reply(Enablement)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12DeviceRemovedExtendedDataSettings_SetPageFaultEnablement(enc, cmd_flags, object_id, Enablement);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12DeviceRemovedExtendedDataSettings_SetPageFaultEnablement(struct npt_ring *ring,
                                                                         npt_object_id object_id,
                                                                         D3D12_DRED_ENABLEMENT Enablement)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12DeviceRemovedExtendedDataSettings_SetPageFaultEnablement(ring, 0, object_id, Enablement, &submit);
}

static inline void
npt_call_ID3D12DeviceRemovedExtendedDataSettings_SetPageFaultEnablement(struct npt_ring *ring,
                                                                        npt_object_id object_id,
                                                                        D3D12_DRED_ENABLEMENT Enablement)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12DeviceRemovedExtendedDataSettings_SetPageFaultEnablement(ring, NPT_CMD_FLAG_REPLY, object_id, Enablement, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        npt_ring_free_command_reply(ring, &submit);
    }
}

/*
 * ID3D12DeviceRemovedExtendedDataSettings::SetWatsonDumpEnablement
 */

struct npt_command_ID3D12DeviceRemovedExtendedDataSettings_SetWatsonDumpEnablement {
    void *_self;
    D3D12_DRED_ENABLEMENT Enablement;
};

static inline size_t
npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings_SetWatsonDumpEnablement(const D3D12_DRED_ENABLEMENT Enablement)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_D3D12_DRED_ENABLEMENT(&Enablement, max_mode);
    return cmd_size;
}

static inline void
npt_encode_ID3D12DeviceRemovedExtendedDataSettings_SetWatsonDumpEnablement(struct npt_cs_encoder *enc,
                                                                           uint32_t cmd_flags,
                                                                           npt_object_id object_id,
                                                                           D3D12_DRED_ENABLEMENT Enablement)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings_SetWatsonDumpEnablement(Enablement);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12DeviceRemovedExtendedDataSettings,
                                 NPT_METHOD_ID3D12DeviceRemovedExtendedDataSettings_SetWatsonDumpEnablement),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_D3D12_DRED_ENABLEMENT(enc, &Enablement);
}

static inline size_t
npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings_SetWatsonDumpEnablement_reply(const D3D12_DRED_ENABLEMENT Enablement)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip Enablement (input only) */
    return cmd_size;
}

static inline void
npt_submit_ID3D12DeviceRemovedExtendedDataSettings_SetWatsonDumpEnablement(struct npt_ring *ring,
                                                                           uint32_t cmd_flags,
                                                                           npt_object_id object_id,
                                                                           D3D12_DRED_ENABLEMENT Enablement,
                                                                           struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings_SetWatsonDumpEnablement(Enablement);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings_SetWatsonDumpEnablement_reply(Enablement)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12DeviceRemovedExtendedDataSettings_SetWatsonDumpEnablement(enc, cmd_flags, object_id, Enablement);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12DeviceRemovedExtendedDataSettings_SetWatsonDumpEnablement(struct npt_ring *ring,
                                                                          npt_object_id object_id,
                                                                          D3D12_DRED_ENABLEMENT Enablement)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12DeviceRemovedExtendedDataSettings_SetWatsonDumpEnablement(ring, 0, object_id, Enablement, &submit);
}

static inline void
npt_call_ID3D12DeviceRemovedExtendedDataSettings_SetWatsonDumpEnablement(struct npt_ring *ring,
                                                                         npt_object_id object_id,
                                                                         D3D12_DRED_ENABLEMENT Enablement)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12DeviceRemovedExtendedDataSettings_SetWatsonDumpEnablement(ring, NPT_CMD_FLAG_REPLY, object_id, Enablement, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        npt_ring_free_command_reply(ring, &submit);
    }
}

/*
 * ID3D12DeviceRemovedExtendedDataSettings1::SetBreadcrumbContextEnablement
 */

struct npt_command_ID3D12DeviceRemovedExtendedDataSettings1_SetBreadcrumbContextEnablement {
    void *_self;
    D3D12_DRED_ENABLEMENT Enablement;
};

static inline size_t
npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings1_SetBreadcrumbContextEnablement(const D3D12_DRED_ENABLEMENT Enablement)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_D3D12_DRED_ENABLEMENT(&Enablement, max_mode);
    return cmd_size;
}

static inline void
npt_encode_ID3D12DeviceRemovedExtendedDataSettings1_SetBreadcrumbContextEnablement(struct npt_cs_encoder *enc,
                                                                                   uint32_t cmd_flags,
                                                                                   npt_object_id object_id,
                                                                                   D3D12_DRED_ENABLEMENT Enablement)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings1_SetBreadcrumbContextEnablement(Enablement);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12DeviceRemovedExtendedDataSettings1,
                                 NPT_METHOD_ID3D12DeviceRemovedExtendedDataSettings1_SetBreadcrumbContextEnablement),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_D3D12_DRED_ENABLEMENT(enc, &Enablement);
}

static inline size_t
npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings1_SetBreadcrumbContextEnablement_reply(const D3D12_DRED_ENABLEMENT Enablement)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip Enablement (input only) */
    return cmd_size;
}

static inline void
npt_submit_ID3D12DeviceRemovedExtendedDataSettings1_SetBreadcrumbContextEnablement(struct npt_ring *ring,
                                                                                   uint32_t cmd_flags,
                                                                                   npt_object_id object_id,
                                                                                   D3D12_DRED_ENABLEMENT Enablement,
                                                                                   struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings1_SetBreadcrumbContextEnablement(Enablement);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings1_SetBreadcrumbContextEnablement_reply(Enablement)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12DeviceRemovedExtendedDataSettings1_SetBreadcrumbContextEnablement(enc, cmd_flags, object_id, Enablement);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12DeviceRemovedExtendedDataSettings1_SetBreadcrumbContextEnablement(struct npt_ring *ring,
                                                                                  npt_object_id object_id,
                                                                                  D3D12_DRED_ENABLEMENT Enablement)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12DeviceRemovedExtendedDataSettings1_SetBreadcrumbContextEnablement(ring, 0, object_id, Enablement, &submit);
}

static inline void
npt_call_ID3D12DeviceRemovedExtendedDataSettings1_SetBreadcrumbContextEnablement(struct npt_ring *ring,
                                                                                 npt_object_id object_id,
                                                                                 D3D12_DRED_ENABLEMENT Enablement)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12DeviceRemovedExtendedDataSettings1_SetBreadcrumbContextEnablement(ring, NPT_CMD_FLAG_REPLY, object_id, Enablement, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        npt_ring_free_command_reply(ring, &submit);
    }
}

/*
 * ID3D12DeviceRemovedExtendedDataSettings2::UseMarkersOnlyAutoBreadcrumbs
 */

struct npt_command_ID3D12DeviceRemovedExtendedDataSettings2_UseMarkersOnlyAutoBreadcrumbs {
    void *_self;
    BOOL MarkersOnly;
};

static inline size_t
npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings2_UseMarkersOnlyAutoBreadcrumbs(const BOOL MarkersOnly)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_BOOL(&MarkersOnly, max_mode);
    return cmd_size;
}

static inline void
npt_encode_ID3D12DeviceRemovedExtendedDataSettings2_UseMarkersOnlyAutoBreadcrumbs(struct npt_cs_encoder *enc,
                                                                                  uint32_t cmd_flags,
                                                                                  npt_object_id object_id,
                                                                                  BOOL MarkersOnly)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings2_UseMarkersOnlyAutoBreadcrumbs(MarkersOnly);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12DeviceRemovedExtendedDataSettings2,
                                 NPT_METHOD_ID3D12DeviceRemovedExtendedDataSettings2_UseMarkersOnlyAutoBreadcrumbs),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_BOOL(enc, &MarkersOnly);
}

static inline size_t
npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings2_UseMarkersOnlyAutoBreadcrumbs_reply(const BOOL MarkersOnly)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip MarkersOnly (input only) */
    return cmd_size;
}

static inline void
npt_submit_ID3D12DeviceRemovedExtendedDataSettings2_UseMarkersOnlyAutoBreadcrumbs(struct npt_ring *ring,
                                                                                  uint32_t cmd_flags,
                                                                                  npt_object_id object_id,
                                                                                  BOOL MarkersOnly,
                                                                                  struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings2_UseMarkersOnlyAutoBreadcrumbs(MarkersOnly);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12DeviceRemovedExtendedDataSettings2_UseMarkersOnlyAutoBreadcrumbs_reply(MarkersOnly)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12DeviceRemovedExtendedDataSettings2_UseMarkersOnlyAutoBreadcrumbs(enc, cmd_flags, object_id, MarkersOnly);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12DeviceRemovedExtendedDataSettings2_UseMarkersOnlyAutoBreadcrumbs(struct npt_ring *ring,
                                                                                 npt_object_id object_id,
                                                                                 BOOL MarkersOnly)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12DeviceRemovedExtendedDataSettings2_UseMarkersOnlyAutoBreadcrumbs(ring, 0, object_id, MarkersOnly, &submit);
}

static inline void
npt_call_ID3D12DeviceRemovedExtendedDataSettings2_UseMarkersOnlyAutoBreadcrumbs(struct npt_ring *ring,
                                                                                npt_object_id object_id,
                                                                                BOOL MarkersOnly)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12DeviceRemovedExtendedDataSettings2_UseMarkersOnlyAutoBreadcrumbs(ring, NPT_CMD_FLAG_REPLY, object_id, MarkersOnly, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        npt_ring_free_command_reply(ring, &submit);
    }
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_GUEST_ID3D12DEVICEREMOVEDEXTENDEDDATASETTINGS_H */
