/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Client-side COM declarations for idxgisurface: per-interface vtable
 * structs, default thunk prototypes, default vtable populators, and default
 * constructors.
 *
 * The thunk bodies, populators, and constructors live in the matching .c
 * file.  This split keeps the headers small and prevents N copies of the
 * thunk code from landing in every TU that pulls in this family.
 */

#ifndef NPT_PROTOCOL_CLIENT_IDXGISURFACE_H
#define NPT_PROTOCOL_CLIENT_IDXGISURFACE_H

#include "npt_protocol_guest_idxgisurface.h"
#include "npt_protocol_client_idxgidevicesubobject.h"

/* Forward-declare struct npt_device so the client_create prototypes don't
 * trigger the "declared inside parameter list" warning.  The full
 * definition lives in the consumer's npt_device.h, which the .c file pulls
 * in via npt_com.h. */
struct npt_device;

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"



/* ================================================================== */
/* IDXGISurface                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * IDXGISurfaceVtbl, by construction.
 */
struct npt_idxgisurface_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: IDXGIObject::SetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateData)(void *self, const GUID * Name, UINT DataSize, const void * pData);
    /* slot 4: IDXGIObject::SetPrivateDataInterface */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateDataInterface)(void *self, const GUID * Name, const IUnknown * pUnknown);
    /* slot 5: IDXGIObject::GetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *GetPrivateData)(void *self, const GUID * Name, UINT * pDataSize, void * pData);
    /* slot 6: IDXGIObject::GetParent */
    HRESULT (NPT_STDMETHODCALLTYPE *GetParent)(void *self, const IID * riid, void ** ppParent);
    /* slot 7: IDXGIDeviceSubObject::GetDevice */
    HRESULT (NPT_STDMETHODCALLTYPE *GetDevice)(void *self, const IID * riid, void ** ppDevice);
    /* slot 8: IDXGISurface::GetDesc */
    HRESULT (NPT_STDMETHODCALLTYPE *GetDesc)(void *self, DXGI_SURFACE_DESC * pDesc);
    /* slot 9: IDXGISurface::Map */
    HRESULT (NPT_STDMETHODCALLTYPE *Map)(void *self, DXGI_MAPPED_RECT * pLockedRect, UINT MapFlags);
    /* slot 10: IDXGISurface::Unmap */
    HRESULT (NPT_STDMETHODCALLTYPE *Unmap)(void *self);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgisurface_default_GetDesc(void *self, DXGI_SURFACE_DESC * pDesc);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgisurface_default_Map(void *self, DXGI_MAPPED_RECT * pLockedRect, UINT MapFlags);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgisurface_default_Unmap(void *self);

/* Default IUnknown thunks for IDXGISurface.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgisurface_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgisurface_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgisurface_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_idxgisurface_fill_default_vtbl(struct npt_idxgisurface_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_idxgisurface_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_idxgisurface_client_vtbl npt_idxgisurface_default_vtbl_storage;
extern void
npt_idxgisurface_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_idxgisurface_client_create(struct npt_device *dev, uint64_t host_id);


/* ================================================================== */
/* IDXGISurface1                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * IDXGISurface1Vtbl, by construction.
 */
struct npt_idxgisurface1_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: IDXGIObject::SetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateData)(void *self, const GUID * Name, UINT DataSize, const void * pData);
    /* slot 4: IDXGIObject::SetPrivateDataInterface */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateDataInterface)(void *self, const GUID * Name, const IUnknown * pUnknown);
    /* slot 5: IDXGIObject::GetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *GetPrivateData)(void *self, const GUID * Name, UINT * pDataSize, void * pData);
    /* slot 6: IDXGIObject::GetParent */
    HRESULT (NPT_STDMETHODCALLTYPE *GetParent)(void *self, const IID * riid, void ** ppParent);
    /* slot 7: IDXGIDeviceSubObject::GetDevice */
    HRESULT (NPT_STDMETHODCALLTYPE *GetDevice)(void *self, const IID * riid, void ** ppDevice);
    /* slot 8: IDXGISurface::GetDesc */
    HRESULT (NPT_STDMETHODCALLTYPE *GetDesc)(void *self, DXGI_SURFACE_DESC * pDesc);
    /* slot 9: IDXGISurface::Map */
    HRESULT (NPT_STDMETHODCALLTYPE *Map)(void *self, DXGI_MAPPED_RECT * pLockedRect, UINT MapFlags);
    /* slot 10: IDXGISurface::Unmap */
    HRESULT (NPT_STDMETHODCALLTYPE *Unmap)(void *self);
    /* slot 11: IDXGISurface1::GetDC */
    HRESULT (NPT_STDMETHODCALLTYPE *GetDC)(void *self, BOOL Discard, HDC * phdc);
    /* slot 12: IDXGISurface1::ReleaseDC */
    HRESULT (NPT_STDMETHODCALLTYPE *ReleaseDC)(void *self, RECT * pDirtyRect);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgisurface1_default_GetDC(void *self, BOOL Discard, HDC * phdc);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgisurface1_default_ReleaseDC(void *self, RECT * pDirtyRect);

/* Default IUnknown thunks for IDXGISurface1.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgisurface1_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgisurface1_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgisurface1_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_idxgisurface1_fill_default_vtbl(struct npt_idxgisurface1_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_idxgisurface1_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_idxgisurface1_client_vtbl npt_idxgisurface1_default_vtbl_storage;
extern void
npt_idxgisurface1_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_idxgisurface1_client_create(struct npt_device *dev, uint64_t host_id);


/* ================================================================== */
/* IDXGISurface2                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * IDXGISurface2Vtbl, by construction.
 */
struct npt_idxgisurface2_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: IDXGIObject::SetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateData)(void *self, const GUID * Name, UINT DataSize, const void * pData);
    /* slot 4: IDXGIObject::SetPrivateDataInterface */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateDataInterface)(void *self, const GUID * Name, const IUnknown * pUnknown);
    /* slot 5: IDXGIObject::GetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *GetPrivateData)(void *self, const GUID * Name, UINT * pDataSize, void * pData);
    /* slot 6: IDXGIObject::GetParent */
    HRESULT (NPT_STDMETHODCALLTYPE *GetParent)(void *self, const IID * riid, void ** ppParent);
    /* slot 7: IDXGIDeviceSubObject::GetDevice */
    HRESULT (NPT_STDMETHODCALLTYPE *GetDevice)(void *self, const IID * riid, void ** ppDevice);
    /* slot 8: IDXGISurface::GetDesc */
    HRESULT (NPT_STDMETHODCALLTYPE *GetDesc)(void *self, DXGI_SURFACE_DESC * pDesc);
    /* slot 9: IDXGISurface::Map */
    HRESULT (NPT_STDMETHODCALLTYPE *Map)(void *self, DXGI_MAPPED_RECT * pLockedRect, UINT MapFlags);
    /* slot 10: IDXGISurface::Unmap */
    HRESULT (NPT_STDMETHODCALLTYPE *Unmap)(void *self);
    /* slot 11: IDXGISurface1::GetDC */
    HRESULT (NPT_STDMETHODCALLTYPE *GetDC)(void *self, BOOL Discard, HDC * phdc);
    /* slot 12: IDXGISurface1::ReleaseDC */
    HRESULT (NPT_STDMETHODCALLTYPE *ReleaseDC)(void *self, RECT * pDirtyRect);
    /* slot 13: IDXGISurface2::GetResource */
    HRESULT (NPT_STDMETHODCALLTYPE *GetResource)(void *self, const IID * riid, void ** ppParentResource, UINT * pSubresourceIndex);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgisurface2_default_GetResource(void *self, const IID * riid, void ** ppParentResource, UINT * pSubresourceIndex);

/* Default IUnknown thunks for IDXGISurface2.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgisurface2_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgisurface2_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgisurface2_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_idxgisurface2_fill_default_vtbl(struct npt_idxgisurface2_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_idxgisurface2_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_idxgisurface2_client_vtbl npt_idxgisurface2_default_vtbl_storage;
extern void
npt_idxgisurface2_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_idxgisurface2_client_create(struct npt_device *dev, uint64_t host_id);


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_CLIENT_IDXGISURFACE_H */
