/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d12commandqueue.
 */

#ifndef NPT_PROTOCOL_GUEST_ID3D12COMMANDQUEUE_H
#define NPT_PROTOCOL_GUEST_ID3D12COMMANDQUEUE_H

#include "npt_protocol_guest_structs.h"
/* For npt_com_allocate_next_id -- called inline from every output
 * COM handle's encode path. */
#include "npt_protocol_guest_cs.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D12CommandQueue::UpdateTileMappings
 */

struct npt_command_ID3D12CommandQueue_UpdateTileMappings {
    void *_self;
    ID3D12Resource * pResource;
    UINT NumResourceRegions;
    const D3D12_TILED_RESOURCE_COORDINATE * pResourceRegionStartCoordinates;
    const D3D12_TILE_REGION_SIZE * pResourceRegionSizes;
    ID3D12Heap * pHeap;
    UINT NumRanges;
    const D3D12_TILE_RANGE_FLAGS * pRangeFlags;
    const UINT * pHeapRangeStartOffsets;
    const UINT * pRangeTileCounts;
    D3D12_TILE_MAPPING_FLAGS Flags;
};

static inline size_t
npt_sizeof_ID3D12CommandQueue_UpdateTileMappings(const ID3D12Resource * pResource,const UINT NumResourceRegions,const D3D12_TILED_RESOURCE_COORDINATE * pResourceRegionStartCoordinates,const D3D12_TILE_REGION_SIZE * pResourceRegionSizes,const ID3D12Heap * pHeap,const UINT NumRanges,const D3D12_TILE_RANGE_FLAGS * pRangeFlags,const UINT * pHeapRangeStartOffsets,const UINT * pRangeTileCounts,const D3D12_TILE_MAPPING_FLAGS Flags)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += sizeof(uint64_t);
    cmd_size += npt_sizeof_UINT(&NumResourceRegions, max_mode);
    cmd_size += npt_sizeof_array_count(pResourceRegionStartCoordinates ? NumResourceRegions : 0);
    for (uint32_t _i = 0; _i < (pResourceRegionStartCoordinates ? NumResourceRegions : 0); _i++)
        cmd_size += npt_sizeof_D3D12_TILED_RESOURCE_COORDINATE(&pResourceRegionStartCoordinates[_i], max_mode);
    cmd_size += npt_sizeof_array_count(pResourceRegionSizes ? NumResourceRegions : 0);
    for (uint32_t _i = 0; _i < (pResourceRegionSizes ? NumResourceRegions : 0); _i++)
        cmd_size += npt_sizeof_D3D12_TILE_REGION_SIZE(&pResourceRegionSizes[_i], max_mode);
    cmd_size += sizeof(uint64_t);
    cmd_size += npt_sizeof_UINT(&NumRanges, max_mode);
    cmd_size += npt_sizeof_array_count(pRangeFlags ? NumRanges : 0);
    if (pRangeFlags)
        cmd_size += npt_sizeof_D3D12_TILE_RANGE_FLAGS_array(pRangeFlags, NumRanges);
    cmd_size += npt_sizeof_array_count(pHeapRangeStartOffsets ? NumRanges : 0);
    if (pHeapRangeStartOffsets)
        cmd_size += npt_sizeof_UINT_array(pHeapRangeStartOffsets, NumRanges);
    cmd_size += npt_sizeof_array_count(pRangeTileCounts ? NumRanges : 0);
    if (pRangeTileCounts)
        cmd_size += npt_sizeof_UINT_array(pRangeTileCounts, NumRanges);
    cmd_size += npt_sizeof_D3D12_TILE_MAPPING_FLAGS(&Flags, max_mode);
    return cmd_size;
}

static inline void
npt_encode_ID3D12CommandQueue_UpdateTileMappings(struct npt_cs_encoder *enc,
                                                 uint32_t cmd_flags,
                                                 npt_object_id object_id,
                                                 ID3D12Resource * pResource,
                                                 UINT NumResourceRegions,
                                                 const D3D12_TILED_RESOURCE_COORDINATE * pResourceRegionStartCoordinates,
                                                 const D3D12_TILE_REGION_SIZE * pResourceRegionSizes,
                                                 ID3D12Heap * pHeap,
                                                 UINT NumRanges,
                                                 const D3D12_TILE_RANGE_FLAGS * pRangeFlags,
                                                 const UINT * pHeapRangeStartOffsets,
                                                 const UINT * pRangeTileCounts,
                                                 D3D12_TILE_MAPPING_FLAGS Flags)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12CommandQueue_UpdateTileMappings(pResource,NumResourceRegions,pResourceRegionStartCoordinates,pResourceRegionSizes,pHeap,NumRanges,pRangeFlags,pHeapRangeStartOffsets,pRangeTileCounts,Flags);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_UpdateTileMappings),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_com_handle(enc, npt_object_get_id(pResource));
    npt_encode_UINT(enc, &NumResourceRegions);
    if (pResourceRegionStartCoordinates) {
        npt_encode_array_count(enc, NumResourceRegions);
        for (uint32_t _i = 0; _i < (uint32_t)(NumResourceRegions); _i++)
            npt_encode_D3D12_TILED_RESOURCE_COORDINATE(enc, &pResourceRegionStartCoordinates[_i]);
    } else {
        npt_encode_array_count(enc, 0);
    }
    if (pResourceRegionSizes) {
        npt_encode_array_count(enc, NumResourceRegions);
        for (uint32_t _i = 0; _i < (uint32_t)(NumResourceRegions); _i++)
            npt_encode_D3D12_TILE_REGION_SIZE(enc, &pResourceRegionSizes[_i]);
    } else {
        npt_encode_array_count(enc, 0);
    }
    npt_encode_com_handle(enc, npt_object_get_id(pHeap));
    npt_encode_UINT(enc, &NumRanges);
    if (pRangeFlags) {
        npt_encode_array_count(enc, NumRanges);
        npt_encode_D3D12_TILE_RANGE_FLAGS_array(enc, pRangeFlags, NumRanges);
    } else {
        npt_encode_array_count(enc, 0);
    }
    if (pHeapRangeStartOffsets) {
        npt_encode_array_count(enc, NumRanges);
        npt_encode_UINT_array(enc, pHeapRangeStartOffsets, NumRanges);
    } else {
        npt_encode_array_count(enc, 0);
    }
    if (pRangeTileCounts) {
        npt_encode_array_count(enc, NumRanges);
        npt_encode_UINT_array(enc, pRangeTileCounts, NumRanges);
    } else {
        npt_encode_array_count(enc, 0);
    }
    npt_encode_D3D12_TILE_MAPPING_FLAGS(enc, &Flags);
}

static inline size_t
npt_sizeof_ID3D12CommandQueue_UpdateTileMappings_reply(const ID3D12Resource * pResource,const UINT NumResourceRegions,const D3D12_TILED_RESOURCE_COORDINATE * pResourceRegionStartCoordinates,const D3D12_TILE_REGION_SIZE * pResourceRegionSizes,const ID3D12Heap * pHeap,const UINT NumRanges,const D3D12_TILE_RANGE_FLAGS * pRangeFlags,const UINT * pHeapRangeStartOffsets,const UINT * pRangeTileCounts,const D3D12_TILE_MAPPING_FLAGS Flags)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip pResource (input only) */
/* skip NumResourceRegions (input only) */
/* skip pResourceRegionStartCoordinates (input only) */
/* skip pResourceRegionSizes (input only) */
/* skip pHeap (input only) */
/* skip NumRanges (input only) */
/* skip pRangeFlags (input only) */
/* skip pHeapRangeStartOffsets (input only) */
/* skip pRangeTileCounts (input only) */
/* skip Flags (input only) */
    return cmd_size;
}

static inline void
npt_submit_ID3D12CommandQueue_UpdateTileMappings(struct npt_ring *ring,
                                                 uint32_t cmd_flags,
                                                 npt_object_id object_id,
                                                 ID3D12Resource * pResource,
                                                 UINT NumResourceRegions,
                                                 const D3D12_TILED_RESOURCE_COORDINATE * pResourceRegionStartCoordinates,
                                                 const D3D12_TILE_REGION_SIZE * pResourceRegionSizes,
                                                 ID3D12Heap * pHeap,
                                                 UINT NumRanges,
                                                 const D3D12_TILE_RANGE_FLAGS * pRangeFlags,
                                                 const UINT * pHeapRangeStartOffsets,
                                                 const UINT * pRangeTileCounts,
                                                 D3D12_TILE_MAPPING_FLAGS Flags,
                                                 struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12CommandQueue_UpdateTileMappings(pResource,NumResourceRegions,pResourceRegionStartCoordinates,pResourceRegionSizes,pHeap,NumRanges,pRangeFlags,pHeapRangeStartOffsets,pRangeTileCounts,Flags);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12CommandQueue_UpdateTileMappings_reply(pResource,NumResourceRegions,pResourceRegionStartCoordinates,pResourceRegionSizes,pHeap,NumRanges,pRangeFlags,pHeapRangeStartOffsets,pRangeTileCounts,Flags)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12CommandQueue_UpdateTileMappings(enc, cmd_flags, object_id, pResource, NumResourceRegions, pResourceRegionStartCoordinates, pResourceRegionSizes, pHeap, NumRanges, pRangeFlags, pHeapRangeStartOffsets, pRangeTileCounts, Flags);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12CommandQueue_UpdateTileMappings(struct npt_ring *ring,
                                                npt_object_id object_id,
                                                ID3D12Resource * pResource,
                                                UINT NumResourceRegions,
                                                const D3D12_TILED_RESOURCE_COORDINATE * pResourceRegionStartCoordinates,
                                                const D3D12_TILE_REGION_SIZE * pResourceRegionSizes,
                                                ID3D12Heap * pHeap,
                                                UINT NumRanges,
                                                const D3D12_TILE_RANGE_FLAGS * pRangeFlags,
                                                const UINT * pHeapRangeStartOffsets,
                                                const UINT * pRangeTileCounts,
                                                D3D12_TILE_MAPPING_FLAGS Flags)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_UpdateTileMappings(ring, 0, object_id, pResource, NumResourceRegions, pResourceRegionStartCoordinates, pResourceRegionSizes, pHeap, NumRanges, pRangeFlags, pHeapRangeStartOffsets, pRangeTileCounts, Flags, &submit);
}

static inline void
npt_call_ID3D12CommandQueue_UpdateTileMappings(struct npt_ring *ring,
                                               npt_object_id object_id,
                                               ID3D12Resource * pResource,
                                               UINT NumResourceRegions,
                                               const D3D12_TILED_RESOURCE_COORDINATE * pResourceRegionStartCoordinates,
                                               const D3D12_TILE_REGION_SIZE * pResourceRegionSizes,
                                               ID3D12Heap * pHeap,
                                               UINT NumRanges,
                                               const D3D12_TILE_RANGE_FLAGS * pRangeFlags,
                                               const UINT * pHeapRangeStartOffsets,
                                               const UINT * pRangeTileCounts,
                                               D3D12_TILE_MAPPING_FLAGS Flags)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_UpdateTileMappings(ring, NPT_CMD_FLAG_REPLY, object_id, pResource, NumResourceRegions, pResourceRegionStartCoordinates, pResourceRegionSizes, pHeap, NumRanges, pRangeFlags, pHeapRangeStartOffsets, pRangeTileCounts, Flags, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        npt_ring_free_command_reply(ring, &submit);
    }
}

/*
 * ID3D12CommandQueue::CopyTileMappings
 */

struct npt_command_ID3D12CommandQueue_CopyTileMappings {
    void *_self;
    ID3D12Resource * pDstResource;
    const D3D12_TILED_RESOURCE_COORDINATE * pDstRegionStartCoordinate;
    ID3D12Resource * pSrcResource;
    const D3D12_TILED_RESOURCE_COORDINATE * pSrcRegionStartCoordinate;
    const D3D12_TILE_REGION_SIZE * pRegionSize;
    D3D12_TILE_MAPPING_FLAGS Flags;
};

static inline size_t
npt_sizeof_ID3D12CommandQueue_CopyTileMappings(const ID3D12Resource * pDstResource,const D3D12_TILED_RESOURCE_COORDINATE * pDstRegionStartCoordinate,const ID3D12Resource * pSrcResource,const D3D12_TILED_RESOURCE_COORDINATE * pSrcRegionStartCoordinate,const D3D12_TILE_REGION_SIZE * pRegionSize,const D3D12_TILE_MAPPING_FLAGS Flags)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += sizeof(uint64_t);
    cmd_size += npt_sizeof_simple_pointer(pDstRegionStartCoordinate);
    if (pDstRegionStartCoordinate)
        cmd_size += npt_sizeof_D3D12_TILED_RESOURCE_COORDINATE(pDstRegionStartCoordinate, max_mode);
    cmd_size += sizeof(uint64_t);
    cmd_size += npt_sizeof_simple_pointer(pSrcRegionStartCoordinate);
    if (pSrcRegionStartCoordinate)
        cmd_size += npt_sizeof_D3D12_TILED_RESOURCE_COORDINATE(pSrcRegionStartCoordinate, max_mode);
    cmd_size += npt_sizeof_simple_pointer(pRegionSize);
    if (pRegionSize)
        cmd_size += npt_sizeof_D3D12_TILE_REGION_SIZE(pRegionSize, max_mode);
    cmd_size += npt_sizeof_D3D12_TILE_MAPPING_FLAGS(&Flags, max_mode);
    return cmd_size;
}

static inline void
npt_encode_ID3D12CommandQueue_CopyTileMappings(struct npt_cs_encoder *enc,
                                               uint32_t cmd_flags,
                                               npt_object_id object_id,
                                               ID3D12Resource * pDstResource,
                                               const D3D12_TILED_RESOURCE_COORDINATE * pDstRegionStartCoordinate,
                                               ID3D12Resource * pSrcResource,
                                               const D3D12_TILED_RESOURCE_COORDINATE * pSrcRegionStartCoordinate,
                                               const D3D12_TILE_REGION_SIZE * pRegionSize,
                                               D3D12_TILE_MAPPING_FLAGS Flags)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12CommandQueue_CopyTileMappings(pDstResource,pDstRegionStartCoordinate,pSrcResource,pSrcRegionStartCoordinate,pRegionSize,Flags);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_CopyTileMappings),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_com_handle(enc, npt_object_get_id(pDstResource));
    if (npt_encode_simple_pointer(enc, pDstRegionStartCoordinate))
        npt_encode_D3D12_TILED_RESOURCE_COORDINATE(enc, pDstRegionStartCoordinate);
    npt_encode_com_handle(enc, npt_object_get_id(pSrcResource));
    if (npt_encode_simple_pointer(enc, pSrcRegionStartCoordinate))
        npt_encode_D3D12_TILED_RESOURCE_COORDINATE(enc, pSrcRegionStartCoordinate);
    if (npt_encode_simple_pointer(enc, pRegionSize))
        npt_encode_D3D12_TILE_REGION_SIZE(enc, pRegionSize);
    npt_encode_D3D12_TILE_MAPPING_FLAGS(enc, &Flags);
}

static inline size_t
npt_sizeof_ID3D12CommandQueue_CopyTileMappings_reply(const ID3D12Resource * pDstResource,const D3D12_TILED_RESOURCE_COORDINATE * pDstRegionStartCoordinate,const ID3D12Resource * pSrcResource,const D3D12_TILED_RESOURCE_COORDINATE * pSrcRegionStartCoordinate,const D3D12_TILE_REGION_SIZE * pRegionSize,const D3D12_TILE_MAPPING_FLAGS Flags)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip pDstResource (input only) */
/* skip pDstRegionStartCoordinate (input only) */
/* skip pSrcResource (input only) */
/* skip pSrcRegionStartCoordinate (input only) */
/* skip pRegionSize (input only) */
/* skip Flags (input only) */
    return cmd_size;
}

static inline void
npt_submit_ID3D12CommandQueue_CopyTileMappings(struct npt_ring *ring,
                                               uint32_t cmd_flags,
                                               npt_object_id object_id,
                                               ID3D12Resource * pDstResource,
                                               const D3D12_TILED_RESOURCE_COORDINATE * pDstRegionStartCoordinate,
                                               ID3D12Resource * pSrcResource,
                                               const D3D12_TILED_RESOURCE_COORDINATE * pSrcRegionStartCoordinate,
                                               const D3D12_TILE_REGION_SIZE * pRegionSize,
                                               D3D12_TILE_MAPPING_FLAGS Flags,
                                               struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12CommandQueue_CopyTileMappings(pDstResource,pDstRegionStartCoordinate,pSrcResource,pSrcRegionStartCoordinate,pRegionSize,Flags);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12CommandQueue_CopyTileMappings_reply(pDstResource,pDstRegionStartCoordinate,pSrcResource,pSrcRegionStartCoordinate,pRegionSize,Flags)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12CommandQueue_CopyTileMappings(enc, cmd_flags, object_id, pDstResource, pDstRegionStartCoordinate, pSrcResource, pSrcRegionStartCoordinate, pRegionSize, Flags);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12CommandQueue_CopyTileMappings(struct npt_ring *ring,
                                              npt_object_id object_id,
                                              ID3D12Resource * pDstResource,
                                              const D3D12_TILED_RESOURCE_COORDINATE * pDstRegionStartCoordinate,
                                              ID3D12Resource * pSrcResource,
                                              const D3D12_TILED_RESOURCE_COORDINATE * pSrcRegionStartCoordinate,
                                              const D3D12_TILE_REGION_SIZE * pRegionSize,
                                              D3D12_TILE_MAPPING_FLAGS Flags)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_CopyTileMappings(ring, 0, object_id, pDstResource, pDstRegionStartCoordinate, pSrcResource, pSrcRegionStartCoordinate, pRegionSize, Flags, &submit);
}

static inline void
npt_call_ID3D12CommandQueue_CopyTileMappings(struct npt_ring *ring,
                                             npt_object_id object_id,
                                             ID3D12Resource * pDstResource,
                                             const D3D12_TILED_RESOURCE_COORDINATE * pDstRegionStartCoordinate,
                                             ID3D12Resource * pSrcResource,
                                             const D3D12_TILED_RESOURCE_COORDINATE * pSrcRegionStartCoordinate,
                                             const D3D12_TILE_REGION_SIZE * pRegionSize,
                                             D3D12_TILE_MAPPING_FLAGS Flags)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_CopyTileMappings(ring, NPT_CMD_FLAG_REPLY, object_id, pDstResource, pDstRegionStartCoordinate, pSrcResource, pSrcRegionStartCoordinate, pRegionSize, Flags, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        npt_ring_free_command_reply(ring, &submit);
    }
}

/*
 * ID3D12CommandQueue::ExecuteCommandLists
 */

struct npt_command_ID3D12CommandQueue_ExecuteCommandLists {
    void *_self;
    UINT NumCommandLists;
    ID3D12CommandList ** ppCommandLists;
};

static inline size_t
npt_sizeof_ID3D12CommandQueue_ExecuteCommandLists(const UINT NumCommandLists,ID3D12CommandList ** ppCommandLists)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_UINT(&NumCommandLists, max_mode);
    cmd_size += npt_sizeof_array_count(NumCommandLists);
    cmd_size += sizeof(uint64_t) * NumCommandLists;
    return cmd_size;
}

static inline void
npt_encode_ID3D12CommandQueue_ExecuteCommandLists(struct npt_cs_encoder *enc,
                                                  uint32_t cmd_flags,
                                                  npt_object_id object_id,
                                                  UINT NumCommandLists,
                                                  ID3D12CommandList ** ppCommandLists)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12CommandQueue_ExecuteCommandLists(NumCommandLists,ppCommandLists);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_ExecuteCommandLists),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_UINT(enc, &NumCommandLists);
    if (ppCommandLists) {
        npt_encode_array_count(enc, NumCommandLists);
        for (uint32_t _i = 0; _i < (uint32_t)NumCommandLists; _i++)
            npt_encode_com_handle(enc, npt_object_get_id(ppCommandLists[_i]));
    } else {
        npt_encode_array_count(enc, 0);
    }
}

static inline size_t
npt_sizeof_ID3D12CommandQueue_ExecuteCommandLists_reply(const UINT NumCommandLists,ID3D12CommandList ** ppCommandLists)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip NumCommandLists (input only) */
/* skip ppCommandLists (input only) */
    return cmd_size;
}

static inline void
npt_submit_ID3D12CommandQueue_ExecuteCommandLists(struct npt_ring *ring,
                                                  uint32_t cmd_flags,
                                                  npt_object_id object_id,
                                                  UINT NumCommandLists,
                                                  ID3D12CommandList ** ppCommandLists,
                                                  struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12CommandQueue_ExecuteCommandLists(NumCommandLists,ppCommandLists);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12CommandQueue_ExecuteCommandLists_reply(NumCommandLists,ppCommandLists)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12CommandQueue_ExecuteCommandLists(enc, cmd_flags, object_id, NumCommandLists, ppCommandLists);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12CommandQueue_ExecuteCommandLists(struct npt_ring *ring,
                                                 npt_object_id object_id,
                                                 UINT NumCommandLists,
                                                 ID3D12CommandList ** ppCommandLists)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_ExecuteCommandLists(ring, 0, object_id, NumCommandLists, ppCommandLists, &submit);
}

static inline void
npt_call_ID3D12CommandQueue_ExecuteCommandLists(struct npt_ring *ring,
                                                npt_object_id object_id,
                                                UINT NumCommandLists,
                                                ID3D12CommandList ** ppCommandLists)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_ExecuteCommandLists(ring, NPT_CMD_FLAG_REPLY, object_id, NumCommandLists, ppCommandLists, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        npt_ring_free_command_reply(ring, &submit);
    }
}

/*
 * ID3D12CommandQueue::SetMarker
 */

struct npt_command_ID3D12CommandQueue_SetMarker {
    void *_self;
    UINT Metadata;
    const void * pData;
    UINT Size;
};

static inline size_t
npt_sizeof_ID3D12CommandQueue_SetMarker(const UINT Metadata,const void * pData,const UINT Size)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_UINT(&Metadata, max_mode);
    if (pData) {
        cmd_size += npt_sizeof_array_count(Size);
        cmd_size += npt_sizeof_blob_array(pData, Size);
    } else {
        cmd_size += npt_sizeof_array_count(0);
    }
    cmd_size += npt_sizeof_UINT(&Size, max_mode);
    return cmd_size;
}

static inline void
npt_encode_ID3D12CommandQueue_SetMarker(struct npt_cs_encoder *enc,
                                        uint32_t cmd_flags,
                                        npt_object_id object_id,
                                        UINT Metadata,
                                        const void * pData,
                                        UINT Size)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12CommandQueue_SetMarker(Metadata,pData,Size);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_SetMarker),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_UINT(enc, &Metadata);
    if (pData) {
        npt_encode_array_count(enc, Size);
        npt_encode_blob_array(enc, pData, Size);
    } else {
        npt_encode_array_count(enc, 0);
    }
    npt_encode_UINT(enc, &Size);
}

static inline size_t
npt_sizeof_ID3D12CommandQueue_SetMarker_reply(const UINT Metadata,const void * pData,const UINT Size)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip Metadata (input only) */
/* skip pData (input only) */
/* skip Size (input only) */
    return cmd_size;
}

static inline void
npt_submit_ID3D12CommandQueue_SetMarker(struct npt_ring *ring,
                                        uint32_t cmd_flags,
                                        npt_object_id object_id,
                                        UINT Metadata,
                                        const void * pData,
                                        UINT Size,
                                        struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12CommandQueue_SetMarker(Metadata,pData,Size);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12CommandQueue_SetMarker_reply(Metadata,pData,Size)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12CommandQueue_SetMarker(enc, cmd_flags, object_id, Metadata, pData, Size);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12CommandQueue_SetMarker(struct npt_ring *ring,
                                       npt_object_id object_id,
                                       UINT Metadata,
                                       const void * pData,
                                       UINT Size)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_SetMarker(ring, 0, object_id, Metadata, pData, Size, &submit);
}

static inline void
npt_call_ID3D12CommandQueue_SetMarker(struct npt_ring *ring,
                                      npt_object_id object_id,
                                      UINT Metadata,
                                      const void * pData,
                                      UINT Size)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_SetMarker(ring, NPT_CMD_FLAG_REPLY, object_id, Metadata, pData, Size, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        npt_ring_free_command_reply(ring, &submit);
    }
}

/*
 * ID3D12CommandQueue::BeginEvent
 */

struct npt_command_ID3D12CommandQueue_BeginEvent {
    void *_self;
    UINT Metadata;
    const void * pData;
    UINT Size;
};

static inline size_t
npt_sizeof_ID3D12CommandQueue_BeginEvent(const UINT Metadata,const void * pData,const UINT Size)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += npt_sizeof_UINT(&Metadata, max_mode);
    if (pData) {
        cmd_size += npt_sizeof_array_count(Size);
        cmd_size += npt_sizeof_blob_array(pData, Size);
    } else {
        cmd_size += npt_sizeof_array_count(0);
    }
    cmd_size += npt_sizeof_UINT(&Size, max_mode);
    return cmd_size;
}

static inline void
npt_encode_ID3D12CommandQueue_BeginEvent(struct npt_cs_encoder *enc,
                                         uint32_t cmd_flags,
                                         npt_object_id object_id,
                                         UINT Metadata,
                                         const void * pData,
                                         UINT Size)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12CommandQueue_BeginEvent(Metadata,pData,Size);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_BeginEvent),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_UINT(enc, &Metadata);
    if (pData) {
        npt_encode_array_count(enc, Size);
        npt_encode_blob_array(enc, pData, Size);
    } else {
        npt_encode_array_count(enc, 0);
    }
    npt_encode_UINT(enc, &Size);
}

static inline size_t
npt_sizeof_ID3D12CommandQueue_BeginEvent_reply(const UINT Metadata,const void * pData,const UINT Size)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip Metadata (input only) */
/* skip pData (input only) */
/* skip Size (input only) */
    return cmd_size;
}

static inline void
npt_submit_ID3D12CommandQueue_BeginEvent(struct npt_ring *ring,
                                         uint32_t cmd_flags,
                                         npt_object_id object_id,
                                         UINT Metadata,
                                         const void * pData,
                                         UINT Size,
                                         struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12CommandQueue_BeginEvent(Metadata,pData,Size);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12CommandQueue_BeginEvent_reply(Metadata,pData,Size)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12CommandQueue_BeginEvent(enc, cmd_flags, object_id, Metadata, pData, Size);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12CommandQueue_BeginEvent(struct npt_ring *ring,
                                        npt_object_id object_id,
                                        UINT Metadata,
                                        const void * pData,
                                        UINT Size)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_BeginEvent(ring, 0, object_id, Metadata, pData, Size, &submit);
}

static inline void
npt_call_ID3D12CommandQueue_BeginEvent(struct npt_ring *ring,
                                       npt_object_id object_id,
                                       UINT Metadata,
                                       const void * pData,
                                       UINT Size)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_BeginEvent(ring, NPT_CMD_FLAG_REPLY, object_id, Metadata, pData, Size, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        npt_ring_free_command_reply(ring, &submit);
    }
}

/*
 * ID3D12CommandQueue::EndEvent
 */

struct npt_command_ID3D12CommandQueue_EndEvent {
    void *_self;
};

static inline size_t
npt_sizeof_ID3D12CommandQueue_EndEvent(void)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    return cmd_size;
}

static inline void
npt_encode_ID3D12CommandQueue_EndEvent(struct npt_cs_encoder *enc,
                                       uint32_t cmd_flags,
                                       npt_object_id object_id)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12CommandQueue_EndEvent();
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_EndEvent),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
}

static inline size_t
npt_sizeof_ID3D12CommandQueue_EndEvent_reply(void)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
    return cmd_size;
}

static inline void
npt_submit_ID3D12CommandQueue_EndEvent(struct npt_ring *ring,
                                       uint32_t cmd_flags,
                                       npt_object_id object_id,
                                       struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12CommandQueue_EndEvent();
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12CommandQueue_EndEvent_reply()
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12CommandQueue_EndEvent(enc, cmd_flags, object_id);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12CommandQueue_EndEvent(struct npt_ring *ring,
                                      npt_object_id object_id)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_EndEvent(ring, 0, object_id, &submit);
}

static inline void
npt_call_ID3D12CommandQueue_EndEvent(struct npt_ring *ring,
                                     npt_object_id object_id)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_EndEvent(ring, NPT_CMD_FLAG_REPLY, object_id, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        npt_ring_free_command_reply(ring, &submit);
    }
}

/*
 * ID3D12CommandQueue::Signal
 */

struct npt_command_ID3D12CommandQueue_Signal {
    void *_self;
    ID3D12Fence * pFence;
    UINT64 Value;
    HRESULT ret;
};

static inline size_t
npt_sizeof_ID3D12CommandQueue_Signal(const ID3D12Fence * pFence,const UINT64 Value)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += sizeof(uint64_t);
    cmd_size += npt_sizeof_UINT64(&Value, max_mode);
    return cmd_size;
}

static inline void
npt_encode_ID3D12CommandQueue_Signal(struct npt_cs_encoder *enc,
                                     uint32_t cmd_flags,
                                     npt_object_id object_id,
                                     ID3D12Fence * pFence,
                                     UINT64 Value)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12CommandQueue_Signal(pFence,Value);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_Signal),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_com_handle(enc, npt_object_get_id(pFence));
    npt_encode_UINT64(enc, &Value);
}

static inline size_t
npt_sizeof_ID3D12CommandQueue_Signal_reply(const ID3D12Fence * pFence,const UINT64 Value)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip pFence (input only) */
/* skip Value (input only) */
    return cmd_size;
}

static inline void
npt_decode_ID3D12CommandQueue_Signal_reply(struct npt_cs_decoder *dec,
                                           HRESULT *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                                  NPT_METHOD_ID3D12CommandQueue_Signal))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D12CommandQueue_Signal reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                       NPT_METHOD_ID3D12CommandQueue_Signal));
        if (ret) *ret = (HRESULT)0x887A0005 /* DXGI_ERROR_DEVICE_REMOVED */;
        return;
    }
    if (ret) *ret = (HRESULT)_reply.cmd_return;
}

static inline void
npt_submit_ID3D12CommandQueue_Signal(struct npt_ring *ring,
                                     uint32_t cmd_flags,
                                     npt_object_id object_id,
                                     ID3D12Fence * pFence,
                                     UINT64 Value,
                                     struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12CommandQueue_Signal(pFence,Value);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12CommandQueue_Signal_reply(pFence,Value)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12CommandQueue_Signal(enc, cmd_flags, object_id, pFence, Value);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12CommandQueue_Signal(struct npt_ring *ring,
                                    npt_object_id object_id,
                                    ID3D12Fence * pFence,
                                    UINT64 Value)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_Signal(ring, 0, object_id, pFence, Value, &submit);
}

static inline HRESULT
npt_call_ID3D12CommandQueue_Signal(struct npt_ring *ring,
                                   npt_object_id object_id,
                                   ID3D12Fence * pFence,
                                   UINT64 Value)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_Signal(ring, NPT_CMD_FLAG_REPLY, object_id, pFence, Value, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        HRESULT _ret;
        npt_decode_ID3D12CommandQueue_Signal_reply(dec, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (HRESULT)0x8007000E /* E_OUTOFMEMORY */;
    }
}

/*
 * ID3D12CommandQueue::Wait
 */

struct npt_command_ID3D12CommandQueue_Wait {
    void *_self;
    ID3D12Fence * pFence;
    UINT64 Value;
    HRESULT ret;
};

static inline size_t
npt_sizeof_ID3D12CommandQueue_Wait(const ID3D12Fence * pFence,const UINT64 Value)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    cmd_size += sizeof(uint64_t);
    cmd_size += npt_sizeof_UINT64(&Value, max_mode);
    return cmd_size;
}

static inline void
npt_encode_ID3D12CommandQueue_Wait(struct npt_cs_encoder *enc,
                                   uint32_t cmd_flags,
                                   npt_object_id object_id,
                                   ID3D12Fence * pFence,
                                   UINT64 Value)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12CommandQueue_Wait(pFence,Value);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_Wait),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
    npt_encode_com_handle(enc, npt_object_get_id(pFence));
    npt_encode_UINT64(enc, &Value);
}

static inline size_t
npt_sizeof_ID3D12CommandQueue_Wait_reply(const ID3D12Fence * pFence,const UINT64 Value)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
/* skip pFence (input only) */
/* skip Value (input only) */
    return cmd_size;
}

static inline void
npt_decode_ID3D12CommandQueue_Wait_reply(struct npt_cs_decoder *dec,
                                         HRESULT *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                                  NPT_METHOD_ID3D12CommandQueue_Wait))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D12CommandQueue_Wait reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                       NPT_METHOD_ID3D12CommandQueue_Wait));
        if (ret) *ret = (HRESULT)0x887A0005 /* DXGI_ERROR_DEVICE_REMOVED */;
        return;
    }
    if (ret) *ret = (HRESULT)_reply.cmd_return;
}

static inline void
npt_submit_ID3D12CommandQueue_Wait(struct npt_ring *ring,
                                   uint32_t cmd_flags,
                                   npt_object_id object_id,
                                   ID3D12Fence * pFence,
                                   UINT64 Value,
                                   struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12CommandQueue_Wait(pFence,Value);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12CommandQueue_Wait_reply(pFence,Value)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12CommandQueue_Wait(enc, cmd_flags, object_id, pFence, Value);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12CommandQueue_Wait(struct npt_ring *ring,
                                  npt_object_id object_id,
                                  ID3D12Fence * pFence,
                                  UINT64 Value)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_Wait(ring, 0, object_id, pFence, Value, &submit);
}

static inline HRESULT
npt_call_ID3D12CommandQueue_Wait(struct npt_ring *ring,
                                 npt_object_id object_id,
                                 ID3D12Fence * pFence,
                                 UINT64 Value)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_Wait(ring, NPT_CMD_FLAG_REPLY, object_id, pFence, Value, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        HRESULT _ret;
        npt_decode_ID3D12CommandQueue_Wait_reply(dec, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (HRESULT)0x8007000E /* E_OUTOFMEMORY */;
    }
}

/*
 * ID3D12CommandQueue::GetTimestampFrequency
 */

struct npt_command_ID3D12CommandQueue_GetTimestampFrequency {
    void *_self;
    UINT64 * pFrequency;
    HRESULT ret;
};

static inline size_t
npt_sizeof_ID3D12CommandQueue_GetTimestampFrequency(const UINT64 * pFrequency)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
/* skip pFrequency (output only) */
    return cmd_size;
}

static inline void
npt_encode_ID3D12CommandQueue_GetTimestampFrequency(struct npt_cs_encoder *enc,
                                                    uint32_t cmd_flags,
                                                    npt_object_id object_id,
                                                    UINT64 * pFrequency)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12CommandQueue_GetTimestampFrequency(pFrequency);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_GetTimestampFrequency),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
/* skip pFrequency (output only) */
}

static inline size_t
npt_sizeof_ID3D12CommandQueue_GetTimestampFrequency_reply(const UINT64 * pFrequency)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
    cmd_size += npt_sizeof_simple_pointer((const void *)1);
    cmd_size += npt_sizeof_UINT64(&(const UINT64){0}, 1);
    return cmd_size;
}

static inline void
npt_decode_ID3D12CommandQueue_GetTimestampFrequency_reply(struct npt_cs_decoder *dec,
                                                          UINT64 * pFrequency,
                                                          HRESULT *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                                  NPT_METHOD_ID3D12CommandQueue_GetTimestampFrequency))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D12CommandQueue_GetTimestampFrequency reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                       NPT_METHOD_ID3D12CommandQueue_GetTimestampFrequency));
        if (ret) *ret = (HRESULT)0x887A0005 /* DXGI_ERROR_DEVICE_REMOVED */;
        return;
    }
    if (ret) *ret = (HRESULT)_reply.cmd_return;
    if (npt_decode_simple_pointer(dec)) {
        if (pFrequency)
            npt_decode_UINT64(dec, (UINT64 *)pFrequency);
    }
}

static inline void
npt_submit_ID3D12CommandQueue_GetTimestampFrequency(struct npt_ring *ring,
                                                    uint32_t cmd_flags,
                                                    npt_object_id object_id,
                                                    UINT64 * pFrequency,
                                                    struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12CommandQueue_GetTimestampFrequency(pFrequency);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12CommandQueue_GetTimestampFrequency_reply(pFrequency)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12CommandQueue_GetTimestampFrequency(enc, cmd_flags, object_id, pFrequency);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12CommandQueue_GetTimestampFrequency(struct npt_ring *ring,
                                                   npt_object_id object_id,
                                                   UINT64 * pFrequency)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_GetTimestampFrequency(ring, 0, object_id, pFrequency, &submit);
}

static inline HRESULT
npt_call_ID3D12CommandQueue_GetTimestampFrequency(struct npt_ring *ring,
                                                  npt_object_id object_id,
                                                  UINT64 * pFrequency)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_GetTimestampFrequency(ring, NPT_CMD_FLAG_REPLY, object_id, pFrequency, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        HRESULT _ret;
        npt_decode_ID3D12CommandQueue_GetTimestampFrequency_reply(dec, pFrequency, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (HRESULT)0x8007000E /* E_OUTOFMEMORY */;
    }
}

/*
 * ID3D12CommandQueue::GetClockCalibration
 */

struct npt_command_ID3D12CommandQueue_GetClockCalibration {
    void *_self;
    UINT64 * pGpuTimestamp;
    UINT64 * pCpuTimestamp;
    HRESULT ret;
};

static inline size_t
npt_sizeof_ID3D12CommandQueue_GetClockCalibration(const UINT64 * pGpuTimestamp,const UINT64 * pCpuTimestamp)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
/* skip pGpuTimestamp (output only) */
/* skip pCpuTimestamp (output only) */
    return cmd_size;
}

static inline void
npt_encode_ID3D12CommandQueue_GetClockCalibration(struct npt_cs_encoder *enc,
                                                  uint32_t cmd_flags,
                                                  npt_object_id object_id,
                                                  UINT64 * pGpuTimestamp,
                                                  UINT64 * pCpuTimestamp)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12CommandQueue_GetClockCalibration(pGpuTimestamp,pCpuTimestamp);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_GetClockCalibration),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
/* skip pGpuTimestamp (output only) */
/* skip pCpuTimestamp (output only) */
}

static inline size_t
npt_sizeof_ID3D12CommandQueue_GetClockCalibration_reply(const UINT64 * pGpuTimestamp,const UINT64 * pCpuTimestamp)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
    cmd_size += npt_sizeof_simple_pointer((const void *)1);
    cmd_size += npt_sizeof_UINT64(&(const UINT64){0}, 1);
    cmd_size += npt_sizeof_simple_pointer((const void *)1);
    cmd_size += npt_sizeof_UINT64(&(const UINT64){0}, 1);
    return cmd_size;
}

static inline void
npt_decode_ID3D12CommandQueue_GetClockCalibration_reply(struct npt_cs_decoder *dec,
                                                        UINT64 * pGpuTimestamp,
                                                        UINT64 * pCpuTimestamp,
                                                        HRESULT *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                                  NPT_METHOD_ID3D12CommandQueue_GetClockCalibration))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D12CommandQueue_GetClockCalibration reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                       NPT_METHOD_ID3D12CommandQueue_GetClockCalibration));
        if (ret) *ret = (HRESULT)0x887A0005 /* DXGI_ERROR_DEVICE_REMOVED */;
        return;
    }
    if (ret) *ret = (HRESULT)_reply.cmd_return;
    if (npt_decode_simple_pointer(dec)) {
        if (pGpuTimestamp)
            npt_decode_UINT64(dec, (UINT64 *)pGpuTimestamp);
    }
    if (npt_decode_simple_pointer(dec)) {
        if (pCpuTimestamp)
            npt_decode_UINT64(dec, (UINT64 *)pCpuTimestamp);
    }
}

static inline void
npt_submit_ID3D12CommandQueue_GetClockCalibration(struct npt_ring *ring,
                                                  uint32_t cmd_flags,
                                                  npt_object_id object_id,
                                                  UINT64 * pGpuTimestamp,
                                                  UINT64 * pCpuTimestamp,
                                                  struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12CommandQueue_GetClockCalibration(pGpuTimestamp,pCpuTimestamp);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12CommandQueue_GetClockCalibration_reply(pGpuTimestamp,pCpuTimestamp)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12CommandQueue_GetClockCalibration(enc, cmd_flags, object_id, pGpuTimestamp, pCpuTimestamp);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12CommandQueue_GetClockCalibration(struct npt_ring *ring,
                                                 npt_object_id object_id,
                                                 UINT64 * pGpuTimestamp,
                                                 UINT64 * pCpuTimestamp)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_GetClockCalibration(ring, 0, object_id, pGpuTimestamp, pCpuTimestamp, &submit);
}

static inline HRESULT
npt_call_ID3D12CommandQueue_GetClockCalibration(struct npt_ring *ring,
                                                npt_object_id object_id,
                                                UINT64 * pGpuTimestamp,
                                                UINT64 * pCpuTimestamp)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_GetClockCalibration(ring, NPT_CMD_FLAG_REPLY, object_id, pGpuTimestamp, pCpuTimestamp, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        HRESULT _ret;
        npt_decode_ID3D12CommandQueue_GetClockCalibration_reply(dec, pGpuTimestamp, pCpuTimestamp, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (HRESULT)0x8007000E /* E_OUTOFMEMORY */;
    }
}

/*
 * ID3D12CommandQueue::GetDesc
 */

struct npt_command_ID3D12CommandQueue_GetDesc {
    void *_self;
    D3D12_COMMAND_QUEUE_DESC ret;
};

static inline size_t
npt_sizeof_ID3D12CommandQueue_GetDesc(void)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
    return cmd_size;
}

static inline void
npt_encode_ID3D12CommandQueue_GetDesc(struct npt_cs_encoder *enc,
                                      uint32_t cmd_flags,
                                      npt_object_id object_id)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_ID3D12CommandQueue_GetDesc();
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_GetDesc),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
}

static inline size_t
npt_sizeof_ID3D12CommandQueue_GetDesc_reply(void)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
    cmd_size += npt_sizeof_D3D12_COMMAND_QUEUE_DESC(&(const D3D12_COMMAND_QUEUE_DESC){0}, 1);
    return cmd_size;
}

static inline void
npt_decode_ID3D12CommandQueue_GetDesc_reply(struct npt_cs_decoder *dec,
                                            D3D12_COMMAND_QUEUE_DESC *ret)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                                  NPT_METHOD_ID3D12CommandQueue_GetDesc))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("ID3D12CommandQueue_GetDesc reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                       NPT_METHOD_ID3D12CommandQueue_GetDesc));
        if (ret) memset(ret, 0, sizeof(*ret));
        return;
    }
    if (ret) npt_decode_D3D12_COMMAND_QUEUE_DESC(dec, ret);
}

static inline void
npt_submit_ID3D12CommandQueue_GetDesc(struct npt_ring *ring,
                                      uint32_t cmd_flags,
                                      npt_object_id object_id,
                                      struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_ID3D12CommandQueue_GetDesc();
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_ID3D12CommandQueue_GetDesc_reply()
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_ID3D12CommandQueue_GetDesc(enc, cmd_flags, object_id);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_ID3D12CommandQueue_GetDesc(struct npt_ring *ring,
                                     npt_object_id object_id)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_GetDesc(ring, 0, object_id, &submit);
}

static inline D3D12_COMMAND_QUEUE_DESC
npt_call_ID3D12CommandQueue_GetDesc(struct npt_ring *ring,
                                    npt_object_id object_id)
{
    struct npt_ring_submit_command submit;
    npt_submit_ID3D12CommandQueue_GetDesc(ring, NPT_CMD_FLAG_REPLY, object_id, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
    if (dec) {
        D3D12_COMMAND_QUEUE_DESC _ret;
        npt_decode_ID3D12CommandQueue_GetDesc_reply(dec, &_ret);
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return (D3D12_COMMAND_QUEUE_DESC){0};
    }
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_GUEST_ID3D12COMMANDQUEUE_H */
