/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Client-side COM declarations for idxgifactory: per-interface vtable
 * structs, default thunk prototypes, default vtable populators, and default
 * constructors.
 *
 * The thunk bodies, populators, and constructors live in the matching .c
 * file.  This split keeps the headers small and prevents N copies of the
 * thunk code from landing in every TU that pulls in this family.
 */

#ifndef NPT_PROTOCOL_CLIENT_IDXGIFACTORY_H
#define NPT_PROTOCOL_CLIENT_IDXGIFACTORY_H

#include "npt_protocol_guest_idxgifactory.h"
#include "npt_protocol_client_idxgiobject.h"

/* Forward-declare struct npt_device so the client_create prototypes don't
 * trigger the "declared inside parameter list" warning.  The full
 * definition lives in the consumer's npt_device.h, which the .c file pulls
 * in via npt_com.h. */
struct npt_device;

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"



/* ================================================================== */
/* IDXGIFactory                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * IDXGIFactoryVtbl, by construction.
 */
struct npt_idxgifactory_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: IDXGIObject::SetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateData)(void *self, const GUID * Name, UINT DataSize, const void * pData);
    /* slot 4: IDXGIObject::SetPrivateDataInterface */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateDataInterface)(void *self, const GUID * Name, const IUnknown * pUnknown);
    /* slot 5: IDXGIObject::GetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *GetPrivateData)(void *self, const GUID * Name, UINT * pDataSize, void * pData);
    /* slot 6: IDXGIObject::GetParent */
    HRESULT (NPT_STDMETHODCALLTYPE *GetParent)(void *self, const IID * riid, void ** ppParent);
    /* slot 7: IDXGIFactory::EnumAdapters */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapters)(void *self, UINT Adapter, IDXGIAdapter ** ppAdapter);
    /* slot 8: IDXGIFactory::MakeWindowAssociation */
    HRESULT (NPT_STDMETHODCALLTYPE *MakeWindowAssociation)(void *self, HWND WindowHandle, UINT Flags);
    /* slot 9: IDXGIFactory::GetWindowAssociation */
    HRESULT (NPT_STDMETHODCALLTYPE *GetWindowAssociation)(void *self, HWND * pWindowHandle);
    /* slot 10: IDXGIFactory::CreateSwapChain */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChain)(void *self, IUnknown * pDevice, DXGI_SWAP_CHAIN_DESC * pDesc, IDXGISwapChain ** ppSwapChain);
    /* slot 11: IDXGIFactory::CreateSoftwareAdapter */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSoftwareAdapter)(void *self, HMODULE Module, IDXGIAdapter ** ppAdapter);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory_default_EnumAdapters(void *self, UINT Adapter, IDXGIAdapter ** ppAdapter);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory_default_MakeWindowAssociation(void *self, HWND WindowHandle, UINT Flags);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory_default_GetWindowAssociation(void *self, HWND * pWindowHandle);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory_default_CreateSwapChain(void *self, IUnknown * pDevice, DXGI_SWAP_CHAIN_DESC * pDesc, IDXGISwapChain ** ppSwapChain);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory_default_CreateSoftwareAdapter(void *self, HMODULE Module, IDXGIAdapter ** ppAdapter);

/* Default IUnknown thunks for IDXGIFactory.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgifactory_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgifactory_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_idxgifactory_fill_default_vtbl(struct npt_idxgifactory_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_idxgifactory_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_idxgifactory_client_vtbl npt_idxgifactory_default_vtbl_storage;
extern void
npt_idxgifactory_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_idxgifactory_client_create(struct npt_device *dev, uint64_t host_id);


/* ================================================================== */
/* IDXGIFactory1                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * IDXGIFactory1Vtbl, by construction.
 */
struct npt_idxgifactory1_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: IDXGIObject::SetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateData)(void *self, const GUID * Name, UINT DataSize, const void * pData);
    /* slot 4: IDXGIObject::SetPrivateDataInterface */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateDataInterface)(void *self, const GUID * Name, const IUnknown * pUnknown);
    /* slot 5: IDXGIObject::GetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *GetPrivateData)(void *self, const GUID * Name, UINT * pDataSize, void * pData);
    /* slot 6: IDXGIObject::GetParent */
    HRESULT (NPT_STDMETHODCALLTYPE *GetParent)(void *self, const IID * riid, void ** ppParent);
    /* slot 7: IDXGIFactory::EnumAdapters */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapters)(void *self, UINT Adapter, IDXGIAdapter ** ppAdapter);
    /* slot 8: IDXGIFactory::MakeWindowAssociation */
    HRESULT (NPT_STDMETHODCALLTYPE *MakeWindowAssociation)(void *self, HWND WindowHandle, UINT Flags);
    /* slot 9: IDXGIFactory::GetWindowAssociation */
    HRESULT (NPT_STDMETHODCALLTYPE *GetWindowAssociation)(void *self, HWND * pWindowHandle);
    /* slot 10: IDXGIFactory::CreateSwapChain */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChain)(void *self, IUnknown * pDevice, DXGI_SWAP_CHAIN_DESC * pDesc, IDXGISwapChain ** ppSwapChain);
    /* slot 11: IDXGIFactory::CreateSoftwareAdapter */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSoftwareAdapter)(void *self, HMODULE Module, IDXGIAdapter ** ppAdapter);
    /* slot 12: IDXGIFactory1::EnumAdapters1 */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapters1)(void *self, UINT Adapter, IDXGIAdapter1 ** ppAdapter);
    /* slot 13: IDXGIFactory1::IsCurrent */
    BOOL (NPT_STDMETHODCALLTYPE *IsCurrent)(void *self);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory1_default_EnumAdapters1(void *self, UINT Adapter, IDXGIAdapter1 ** ppAdapter);
extern BOOL NPT_STDMETHODCALLTYPE
npt_idxgifactory1_default_IsCurrent(void *self);

/* Default IUnknown thunks for IDXGIFactory1.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory1_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgifactory1_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgifactory1_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_idxgifactory1_fill_default_vtbl(struct npt_idxgifactory1_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_idxgifactory1_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_idxgifactory1_client_vtbl npt_idxgifactory1_default_vtbl_storage;
extern void
npt_idxgifactory1_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_idxgifactory1_client_create(struct npt_device *dev, uint64_t host_id);


/* ================================================================== */
/* IDXGIFactory2                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * IDXGIFactory2Vtbl, by construction.
 */
struct npt_idxgifactory2_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: IDXGIObject::SetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateData)(void *self, const GUID * Name, UINT DataSize, const void * pData);
    /* slot 4: IDXGIObject::SetPrivateDataInterface */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateDataInterface)(void *self, const GUID * Name, const IUnknown * pUnknown);
    /* slot 5: IDXGIObject::GetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *GetPrivateData)(void *self, const GUID * Name, UINT * pDataSize, void * pData);
    /* slot 6: IDXGIObject::GetParent */
    HRESULT (NPT_STDMETHODCALLTYPE *GetParent)(void *self, const IID * riid, void ** ppParent);
    /* slot 7: IDXGIFactory::EnumAdapters */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapters)(void *self, UINT Adapter, IDXGIAdapter ** ppAdapter);
    /* slot 8: IDXGIFactory::MakeWindowAssociation */
    HRESULT (NPT_STDMETHODCALLTYPE *MakeWindowAssociation)(void *self, HWND WindowHandle, UINT Flags);
    /* slot 9: IDXGIFactory::GetWindowAssociation */
    HRESULT (NPT_STDMETHODCALLTYPE *GetWindowAssociation)(void *self, HWND * pWindowHandle);
    /* slot 10: IDXGIFactory::CreateSwapChain */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChain)(void *self, IUnknown * pDevice, DXGI_SWAP_CHAIN_DESC * pDesc, IDXGISwapChain ** ppSwapChain);
    /* slot 11: IDXGIFactory::CreateSoftwareAdapter */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSoftwareAdapter)(void *self, HMODULE Module, IDXGIAdapter ** ppAdapter);
    /* slot 12: IDXGIFactory1::EnumAdapters1 */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapters1)(void *self, UINT Adapter, IDXGIAdapter1 ** ppAdapter);
    /* slot 13: IDXGIFactory1::IsCurrent */
    BOOL (NPT_STDMETHODCALLTYPE *IsCurrent)(void *self);
    /* slot 14: IDXGIFactory2::IsWindowedStereoEnabled */
    BOOL (NPT_STDMETHODCALLTYPE *IsWindowedStereoEnabled)(void *self);
    /* slot 15: IDXGIFactory2::CreateSwapChainForHwnd */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChainForHwnd)(void *self, IUnknown * pDevice, HWND hWnd, const DXGI_SWAP_CHAIN_DESC1 * pDesc, const DXGI_SWAP_CHAIN_FULLSCREEN_DESC * pFullscreenDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);
    /* slot 16: IDXGIFactory2::CreateSwapChainForCoreWindow */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChainForCoreWindow)(void *self, IUnknown * pDevice, IUnknown * pWindow, const DXGI_SWAP_CHAIN_DESC1 * pDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);
    /* slot 17: IDXGIFactory2::GetSharedResourceAdapterLuid */
    HRESULT (NPT_STDMETHODCALLTYPE *GetSharedResourceAdapterLuid)(void *self, HANDLE hResource, LUID * pLuid);
    /* slot 18: IDXGIFactory2::RegisterStereoStatusWindow */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterStereoStatusWindow)(void *self, HWND WindowHandle, UINT wMsg, DWORD * pdwCookie);
    /* slot 19: IDXGIFactory2::RegisterStereoStatusEvent */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterStereoStatusEvent)(void *self, HANDLE hEvent, DWORD * pdwCookie);
    /* slot 20: IDXGIFactory2::UnregisterStereoStatus */
    void (NPT_STDMETHODCALLTYPE *UnregisterStereoStatus)(void *self, DWORD dwCookie);
    /* slot 21: IDXGIFactory2::RegisterOcclusionStatusWindow */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterOcclusionStatusWindow)(void *self, HWND WindowHandle, UINT wMsg, DWORD * pdwCookie);
    /* slot 22: IDXGIFactory2::RegisterOcclusionStatusEvent */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterOcclusionStatusEvent)(void *self, HANDLE hEvent, DWORD * pdwCookie);
    /* slot 23: IDXGIFactory2::UnregisterOcclusionStatus */
    void (NPT_STDMETHODCALLTYPE *UnregisterOcclusionStatus)(void *self, DWORD dwCookie);
    /* slot 24: IDXGIFactory2::CreateSwapChainForComposition */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChainForComposition)(void *self, IUnknown * pDevice, const DXGI_SWAP_CHAIN_DESC1 * pDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern BOOL NPT_STDMETHODCALLTYPE
npt_idxgifactory2_default_IsWindowedStereoEnabled(void *self);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory2_default_CreateSwapChainForHwnd(void *self, IUnknown * pDevice, HWND hWnd, const DXGI_SWAP_CHAIN_DESC1 * pDesc, const DXGI_SWAP_CHAIN_FULLSCREEN_DESC * pFullscreenDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory2_default_CreateSwapChainForCoreWindow(void *self, IUnknown * pDevice, IUnknown * pWindow, const DXGI_SWAP_CHAIN_DESC1 * pDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory2_default_GetSharedResourceAdapterLuid(void *self, HANDLE hResource, LUID * pLuid);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory2_default_RegisterStereoStatusWindow(void *self, HWND WindowHandle, UINT wMsg, DWORD * pdwCookie);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory2_default_RegisterStereoStatusEvent(void *self, HANDLE hEvent, DWORD * pdwCookie);
extern void NPT_STDMETHODCALLTYPE
npt_idxgifactory2_default_UnregisterStereoStatus(void *self, DWORD dwCookie);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory2_default_RegisterOcclusionStatusWindow(void *self, HWND WindowHandle, UINT wMsg, DWORD * pdwCookie);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory2_default_RegisterOcclusionStatusEvent(void *self, HANDLE hEvent, DWORD * pdwCookie);
extern void NPT_STDMETHODCALLTYPE
npt_idxgifactory2_default_UnregisterOcclusionStatus(void *self, DWORD dwCookie);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory2_default_CreateSwapChainForComposition(void *self, IUnknown * pDevice, const DXGI_SWAP_CHAIN_DESC1 * pDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);

/* Default IUnknown thunks for IDXGIFactory2.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory2_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgifactory2_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgifactory2_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_idxgifactory2_fill_default_vtbl(struct npt_idxgifactory2_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_idxgifactory2_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_idxgifactory2_client_vtbl npt_idxgifactory2_default_vtbl_storage;
extern void
npt_idxgifactory2_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_idxgifactory2_client_create(struct npt_device *dev, uint64_t host_id);


/* ================================================================== */
/* IDXGIFactory3                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * IDXGIFactory3Vtbl, by construction.
 */
struct npt_idxgifactory3_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: IDXGIObject::SetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateData)(void *self, const GUID * Name, UINT DataSize, const void * pData);
    /* slot 4: IDXGIObject::SetPrivateDataInterface */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateDataInterface)(void *self, const GUID * Name, const IUnknown * pUnknown);
    /* slot 5: IDXGIObject::GetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *GetPrivateData)(void *self, const GUID * Name, UINT * pDataSize, void * pData);
    /* slot 6: IDXGIObject::GetParent */
    HRESULT (NPT_STDMETHODCALLTYPE *GetParent)(void *self, const IID * riid, void ** ppParent);
    /* slot 7: IDXGIFactory::EnumAdapters */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapters)(void *self, UINT Adapter, IDXGIAdapter ** ppAdapter);
    /* slot 8: IDXGIFactory::MakeWindowAssociation */
    HRESULT (NPT_STDMETHODCALLTYPE *MakeWindowAssociation)(void *self, HWND WindowHandle, UINT Flags);
    /* slot 9: IDXGIFactory::GetWindowAssociation */
    HRESULT (NPT_STDMETHODCALLTYPE *GetWindowAssociation)(void *self, HWND * pWindowHandle);
    /* slot 10: IDXGIFactory::CreateSwapChain */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChain)(void *self, IUnknown * pDevice, DXGI_SWAP_CHAIN_DESC * pDesc, IDXGISwapChain ** ppSwapChain);
    /* slot 11: IDXGIFactory::CreateSoftwareAdapter */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSoftwareAdapter)(void *self, HMODULE Module, IDXGIAdapter ** ppAdapter);
    /* slot 12: IDXGIFactory1::EnumAdapters1 */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapters1)(void *self, UINT Adapter, IDXGIAdapter1 ** ppAdapter);
    /* slot 13: IDXGIFactory1::IsCurrent */
    BOOL (NPT_STDMETHODCALLTYPE *IsCurrent)(void *self);
    /* slot 14: IDXGIFactory2::IsWindowedStereoEnabled */
    BOOL (NPT_STDMETHODCALLTYPE *IsWindowedStereoEnabled)(void *self);
    /* slot 15: IDXGIFactory2::CreateSwapChainForHwnd */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChainForHwnd)(void *self, IUnknown * pDevice, HWND hWnd, const DXGI_SWAP_CHAIN_DESC1 * pDesc, const DXGI_SWAP_CHAIN_FULLSCREEN_DESC * pFullscreenDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);
    /* slot 16: IDXGIFactory2::CreateSwapChainForCoreWindow */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChainForCoreWindow)(void *self, IUnknown * pDevice, IUnknown * pWindow, const DXGI_SWAP_CHAIN_DESC1 * pDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);
    /* slot 17: IDXGIFactory2::GetSharedResourceAdapterLuid */
    HRESULT (NPT_STDMETHODCALLTYPE *GetSharedResourceAdapterLuid)(void *self, HANDLE hResource, LUID * pLuid);
    /* slot 18: IDXGIFactory2::RegisterStereoStatusWindow */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterStereoStatusWindow)(void *self, HWND WindowHandle, UINT wMsg, DWORD * pdwCookie);
    /* slot 19: IDXGIFactory2::RegisterStereoStatusEvent */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterStereoStatusEvent)(void *self, HANDLE hEvent, DWORD * pdwCookie);
    /* slot 20: IDXGIFactory2::UnregisterStereoStatus */
    void (NPT_STDMETHODCALLTYPE *UnregisterStereoStatus)(void *self, DWORD dwCookie);
    /* slot 21: IDXGIFactory2::RegisterOcclusionStatusWindow */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterOcclusionStatusWindow)(void *self, HWND WindowHandle, UINT wMsg, DWORD * pdwCookie);
    /* slot 22: IDXGIFactory2::RegisterOcclusionStatusEvent */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterOcclusionStatusEvent)(void *self, HANDLE hEvent, DWORD * pdwCookie);
    /* slot 23: IDXGIFactory2::UnregisterOcclusionStatus */
    void (NPT_STDMETHODCALLTYPE *UnregisterOcclusionStatus)(void *self, DWORD dwCookie);
    /* slot 24: IDXGIFactory2::CreateSwapChainForComposition */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChainForComposition)(void *self, IUnknown * pDevice, const DXGI_SWAP_CHAIN_DESC1 * pDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);
    /* slot 25: IDXGIFactory3::GetCreationFlags */
    UINT (NPT_STDMETHODCALLTYPE *GetCreationFlags)(void *self);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern UINT NPT_STDMETHODCALLTYPE
npt_idxgifactory3_default_GetCreationFlags(void *self);

/* Default IUnknown thunks for IDXGIFactory3.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory3_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgifactory3_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgifactory3_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_idxgifactory3_fill_default_vtbl(struct npt_idxgifactory3_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_idxgifactory3_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_idxgifactory3_client_vtbl npt_idxgifactory3_default_vtbl_storage;
extern void
npt_idxgifactory3_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_idxgifactory3_client_create(struct npt_device *dev, uint64_t host_id);


/* ================================================================== */
/* IDXGIFactory4                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * IDXGIFactory4Vtbl, by construction.
 */
struct npt_idxgifactory4_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: IDXGIObject::SetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateData)(void *self, const GUID * Name, UINT DataSize, const void * pData);
    /* slot 4: IDXGIObject::SetPrivateDataInterface */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateDataInterface)(void *self, const GUID * Name, const IUnknown * pUnknown);
    /* slot 5: IDXGIObject::GetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *GetPrivateData)(void *self, const GUID * Name, UINT * pDataSize, void * pData);
    /* slot 6: IDXGIObject::GetParent */
    HRESULT (NPT_STDMETHODCALLTYPE *GetParent)(void *self, const IID * riid, void ** ppParent);
    /* slot 7: IDXGIFactory::EnumAdapters */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapters)(void *self, UINT Adapter, IDXGIAdapter ** ppAdapter);
    /* slot 8: IDXGIFactory::MakeWindowAssociation */
    HRESULT (NPT_STDMETHODCALLTYPE *MakeWindowAssociation)(void *self, HWND WindowHandle, UINT Flags);
    /* slot 9: IDXGIFactory::GetWindowAssociation */
    HRESULT (NPT_STDMETHODCALLTYPE *GetWindowAssociation)(void *self, HWND * pWindowHandle);
    /* slot 10: IDXGIFactory::CreateSwapChain */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChain)(void *self, IUnknown * pDevice, DXGI_SWAP_CHAIN_DESC * pDesc, IDXGISwapChain ** ppSwapChain);
    /* slot 11: IDXGIFactory::CreateSoftwareAdapter */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSoftwareAdapter)(void *self, HMODULE Module, IDXGIAdapter ** ppAdapter);
    /* slot 12: IDXGIFactory1::EnumAdapters1 */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapters1)(void *self, UINT Adapter, IDXGIAdapter1 ** ppAdapter);
    /* slot 13: IDXGIFactory1::IsCurrent */
    BOOL (NPT_STDMETHODCALLTYPE *IsCurrent)(void *self);
    /* slot 14: IDXGIFactory2::IsWindowedStereoEnabled */
    BOOL (NPT_STDMETHODCALLTYPE *IsWindowedStereoEnabled)(void *self);
    /* slot 15: IDXGIFactory2::CreateSwapChainForHwnd */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChainForHwnd)(void *self, IUnknown * pDevice, HWND hWnd, const DXGI_SWAP_CHAIN_DESC1 * pDesc, const DXGI_SWAP_CHAIN_FULLSCREEN_DESC * pFullscreenDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);
    /* slot 16: IDXGIFactory2::CreateSwapChainForCoreWindow */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChainForCoreWindow)(void *self, IUnknown * pDevice, IUnknown * pWindow, const DXGI_SWAP_CHAIN_DESC1 * pDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);
    /* slot 17: IDXGIFactory2::GetSharedResourceAdapterLuid */
    HRESULT (NPT_STDMETHODCALLTYPE *GetSharedResourceAdapterLuid)(void *self, HANDLE hResource, LUID * pLuid);
    /* slot 18: IDXGIFactory2::RegisterStereoStatusWindow */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterStereoStatusWindow)(void *self, HWND WindowHandle, UINT wMsg, DWORD * pdwCookie);
    /* slot 19: IDXGIFactory2::RegisterStereoStatusEvent */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterStereoStatusEvent)(void *self, HANDLE hEvent, DWORD * pdwCookie);
    /* slot 20: IDXGIFactory2::UnregisterStereoStatus */
    void (NPT_STDMETHODCALLTYPE *UnregisterStereoStatus)(void *self, DWORD dwCookie);
    /* slot 21: IDXGIFactory2::RegisterOcclusionStatusWindow */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterOcclusionStatusWindow)(void *self, HWND WindowHandle, UINT wMsg, DWORD * pdwCookie);
    /* slot 22: IDXGIFactory2::RegisterOcclusionStatusEvent */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterOcclusionStatusEvent)(void *self, HANDLE hEvent, DWORD * pdwCookie);
    /* slot 23: IDXGIFactory2::UnregisterOcclusionStatus */
    void (NPT_STDMETHODCALLTYPE *UnregisterOcclusionStatus)(void *self, DWORD dwCookie);
    /* slot 24: IDXGIFactory2::CreateSwapChainForComposition */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChainForComposition)(void *self, IUnknown * pDevice, const DXGI_SWAP_CHAIN_DESC1 * pDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);
    /* slot 25: IDXGIFactory3::GetCreationFlags */
    UINT (NPT_STDMETHODCALLTYPE *GetCreationFlags)(void *self);
    /* slot 26: IDXGIFactory4::EnumAdapterByLuid */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapterByLuid)(void *self, LUID AdapterLuid, const IID * riid, void ** ppvAdapter);
    /* slot 27: IDXGIFactory4::EnumWarpAdapter */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumWarpAdapter)(void *self, const IID * riid, void ** ppvAdapter);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory4_default_EnumAdapterByLuid(void *self, LUID AdapterLuid, const IID * riid, void ** ppvAdapter);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory4_default_EnumWarpAdapter(void *self, const IID * riid, void ** ppvAdapter);

/* Default IUnknown thunks for IDXGIFactory4.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory4_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgifactory4_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgifactory4_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_idxgifactory4_fill_default_vtbl(struct npt_idxgifactory4_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_idxgifactory4_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_idxgifactory4_client_vtbl npt_idxgifactory4_default_vtbl_storage;
extern void
npt_idxgifactory4_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_idxgifactory4_client_create(struct npt_device *dev, uint64_t host_id);


/* ================================================================== */
/* IDXGIFactory5                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * IDXGIFactory5Vtbl, by construction.
 */
struct npt_idxgifactory5_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: IDXGIObject::SetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateData)(void *self, const GUID * Name, UINT DataSize, const void * pData);
    /* slot 4: IDXGIObject::SetPrivateDataInterface */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateDataInterface)(void *self, const GUID * Name, const IUnknown * pUnknown);
    /* slot 5: IDXGIObject::GetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *GetPrivateData)(void *self, const GUID * Name, UINT * pDataSize, void * pData);
    /* slot 6: IDXGIObject::GetParent */
    HRESULT (NPT_STDMETHODCALLTYPE *GetParent)(void *self, const IID * riid, void ** ppParent);
    /* slot 7: IDXGIFactory::EnumAdapters */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapters)(void *self, UINT Adapter, IDXGIAdapter ** ppAdapter);
    /* slot 8: IDXGIFactory::MakeWindowAssociation */
    HRESULT (NPT_STDMETHODCALLTYPE *MakeWindowAssociation)(void *self, HWND WindowHandle, UINT Flags);
    /* slot 9: IDXGIFactory::GetWindowAssociation */
    HRESULT (NPT_STDMETHODCALLTYPE *GetWindowAssociation)(void *self, HWND * pWindowHandle);
    /* slot 10: IDXGIFactory::CreateSwapChain */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChain)(void *self, IUnknown * pDevice, DXGI_SWAP_CHAIN_DESC * pDesc, IDXGISwapChain ** ppSwapChain);
    /* slot 11: IDXGIFactory::CreateSoftwareAdapter */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSoftwareAdapter)(void *self, HMODULE Module, IDXGIAdapter ** ppAdapter);
    /* slot 12: IDXGIFactory1::EnumAdapters1 */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapters1)(void *self, UINT Adapter, IDXGIAdapter1 ** ppAdapter);
    /* slot 13: IDXGIFactory1::IsCurrent */
    BOOL (NPT_STDMETHODCALLTYPE *IsCurrent)(void *self);
    /* slot 14: IDXGIFactory2::IsWindowedStereoEnabled */
    BOOL (NPT_STDMETHODCALLTYPE *IsWindowedStereoEnabled)(void *self);
    /* slot 15: IDXGIFactory2::CreateSwapChainForHwnd */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChainForHwnd)(void *self, IUnknown * pDevice, HWND hWnd, const DXGI_SWAP_CHAIN_DESC1 * pDesc, const DXGI_SWAP_CHAIN_FULLSCREEN_DESC * pFullscreenDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);
    /* slot 16: IDXGIFactory2::CreateSwapChainForCoreWindow */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChainForCoreWindow)(void *self, IUnknown * pDevice, IUnknown * pWindow, const DXGI_SWAP_CHAIN_DESC1 * pDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);
    /* slot 17: IDXGIFactory2::GetSharedResourceAdapterLuid */
    HRESULT (NPT_STDMETHODCALLTYPE *GetSharedResourceAdapterLuid)(void *self, HANDLE hResource, LUID * pLuid);
    /* slot 18: IDXGIFactory2::RegisterStereoStatusWindow */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterStereoStatusWindow)(void *self, HWND WindowHandle, UINT wMsg, DWORD * pdwCookie);
    /* slot 19: IDXGIFactory2::RegisterStereoStatusEvent */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterStereoStatusEvent)(void *self, HANDLE hEvent, DWORD * pdwCookie);
    /* slot 20: IDXGIFactory2::UnregisterStereoStatus */
    void (NPT_STDMETHODCALLTYPE *UnregisterStereoStatus)(void *self, DWORD dwCookie);
    /* slot 21: IDXGIFactory2::RegisterOcclusionStatusWindow */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterOcclusionStatusWindow)(void *self, HWND WindowHandle, UINT wMsg, DWORD * pdwCookie);
    /* slot 22: IDXGIFactory2::RegisterOcclusionStatusEvent */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterOcclusionStatusEvent)(void *self, HANDLE hEvent, DWORD * pdwCookie);
    /* slot 23: IDXGIFactory2::UnregisterOcclusionStatus */
    void (NPT_STDMETHODCALLTYPE *UnregisterOcclusionStatus)(void *self, DWORD dwCookie);
    /* slot 24: IDXGIFactory2::CreateSwapChainForComposition */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChainForComposition)(void *self, IUnknown * pDevice, const DXGI_SWAP_CHAIN_DESC1 * pDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);
    /* slot 25: IDXGIFactory3::GetCreationFlags */
    UINT (NPT_STDMETHODCALLTYPE *GetCreationFlags)(void *self);
    /* slot 26: IDXGIFactory4::EnumAdapterByLuid */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapterByLuid)(void *self, LUID AdapterLuid, const IID * riid, void ** ppvAdapter);
    /* slot 27: IDXGIFactory4::EnumWarpAdapter */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumWarpAdapter)(void *self, const IID * riid, void ** ppvAdapter);
    /* slot 28: IDXGIFactory5::CheckFeatureSupport */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckFeatureSupport)(void *self, DXGI_FEATURE Feature, void * pFeatureSupportData, UINT FeatureSupportDataSize);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory5_default_CheckFeatureSupport(void *self, DXGI_FEATURE Feature, void * pFeatureSupportData, UINT FeatureSupportDataSize);

/* Default IUnknown thunks for IDXGIFactory5.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory5_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgifactory5_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgifactory5_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_idxgifactory5_fill_default_vtbl(struct npt_idxgifactory5_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_idxgifactory5_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_idxgifactory5_client_vtbl npt_idxgifactory5_default_vtbl_storage;
extern void
npt_idxgifactory5_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_idxgifactory5_client_create(struct npt_device *dev, uint64_t host_id);


/* ================================================================== */
/* IDXGIFactory6                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * IDXGIFactory6Vtbl, by construction.
 */
struct npt_idxgifactory6_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: IDXGIObject::SetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateData)(void *self, const GUID * Name, UINT DataSize, const void * pData);
    /* slot 4: IDXGIObject::SetPrivateDataInterface */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateDataInterface)(void *self, const GUID * Name, const IUnknown * pUnknown);
    /* slot 5: IDXGIObject::GetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *GetPrivateData)(void *self, const GUID * Name, UINT * pDataSize, void * pData);
    /* slot 6: IDXGIObject::GetParent */
    HRESULT (NPT_STDMETHODCALLTYPE *GetParent)(void *self, const IID * riid, void ** ppParent);
    /* slot 7: IDXGIFactory::EnumAdapters */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapters)(void *self, UINT Adapter, IDXGIAdapter ** ppAdapter);
    /* slot 8: IDXGIFactory::MakeWindowAssociation */
    HRESULT (NPT_STDMETHODCALLTYPE *MakeWindowAssociation)(void *self, HWND WindowHandle, UINT Flags);
    /* slot 9: IDXGIFactory::GetWindowAssociation */
    HRESULT (NPT_STDMETHODCALLTYPE *GetWindowAssociation)(void *self, HWND * pWindowHandle);
    /* slot 10: IDXGIFactory::CreateSwapChain */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChain)(void *self, IUnknown * pDevice, DXGI_SWAP_CHAIN_DESC * pDesc, IDXGISwapChain ** ppSwapChain);
    /* slot 11: IDXGIFactory::CreateSoftwareAdapter */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSoftwareAdapter)(void *self, HMODULE Module, IDXGIAdapter ** ppAdapter);
    /* slot 12: IDXGIFactory1::EnumAdapters1 */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapters1)(void *self, UINT Adapter, IDXGIAdapter1 ** ppAdapter);
    /* slot 13: IDXGIFactory1::IsCurrent */
    BOOL (NPT_STDMETHODCALLTYPE *IsCurrent)(void *self);
    /* slot 14: IDXGIFactory2::IsWindowedStereoEnabled */
    BOOL (NPT_STDMETHODCALLTYPE *IsWindowedStereoEnabled)(void *self);
    /* slot 15: IDXGIFactory2::CreateSwapChainForHwnd */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChainForHwnd)(void *self, IUnknown * pDevice, HWND hWnd, const DXGI_SWAP_CHAIN_DESC1 * pDesc, const DXGI_SWAP_CHAIN_FULLSCREEN_DESC * pFullscreenDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);
    /* slot 16: IDXGIFactory2::CreateSwapChainForCoreWindow */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChainForCoreWindow)(void *self, IUnknown * pDevice, IUnknown * pWindow, const DXGI_SWAP_CHAIN_DESC1 * pDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);
    /* slot 17: IDXGIFactory2::GetSharedResourceAdapterLuid */
    HRESULT (NPT_STDMETHODCALLTYPE *GetSharedResourceAdapterLuid)(void *self, HANDLE hResource, LUID * pLuid);
    /* slot 18: IDXGIFactory2::RegisterStereoStatusWindow */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterStereoStatusWindow)(void *self, HWND WindowHandle, UINT wMsg, DWORD * pdwCookie);
    /* slot 19: IDXGIFactory2::RegisterStereoStatusEvent */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterStereoStatusEvent)(void *self, HANDLE hEvent, DWORD * pdwCookie);
    /* slot 20: IDXGIFactory2::UnregisterStereoStatus */
    void (NPT_STDMETHODCALLTYPE *UnregisterStereoStatus)(void *self, DWORD dwCookie);
    /* slot 21: IDXGIFactory2::RegisterOcclusionStatusWindow */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterOcclusionStatusWindow)(void *self, HWND WindowHandle, UINT wMsg, DWORD * pdwCookie);
    /* slot 22: IDXGIFactory2::RegisterOcclusionStatusEvent */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterOcclusionStatusEvent)(void *self, HANDLE hEvent, DWORD * pdwCookie);
    /* slot 23: IDXGIFactory2::UnregisterOcclusionStatus */
    void (NPT_STDMETHODCALLTYPE *UnregisterOcclusionStatus)(void *self, DWORD dwCookie);
    /* slot 24: IDXGIFactory2::CreateSwapChainForComposition */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChainForComposition)(void *self, IUnknown * pDevice, const DXGI_SWAP_CHAIN_DESC1 * pDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);
    /* slot 25: IDXGIFactory3::GetCreationFlags */
    UINT (NPT_STDMETHODCALLTYPE *GetCreationFlags)(void *self);
    /* slot 26: IDXGIFactory4::EnumAdapterByLuid */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapterByLuid)(void *self, LUID AdapterLuid, const IID * riid, void ** ppvAdapter);
    /* slot 27: IDXGIFactory4::EnumWarpAdapter */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumWarpAdapter)(void *self, const IID * riid, void ** ppvAdapter);
    /* slot 28: IDXGIFactory5::CheckFeatureSupport */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckFeatureSupport)(void *self, DXGI_FEATURE Feature, void * pFeatureSupportData, UINT FeatureSupportDataSize);
    /* slot 29: IDXGIFactory6::EnumAdapterByGpuPreference */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapterByGpuPreference)(void *self, UINT Adapter, DXGI_GPU_PREFERENCE GpuPreference, const IID * riid, void ** ppvAdapter);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory6_default_EnumAdapterByGpuPreference(void *self, UINT Adapter, DXGI_GPU_PREFERENCE GpuPreference, const IID * riid, void ** ppvAdapter);

/* Default IUnknown thunks for IDXGIFactory6.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory6_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgifactory6_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgifactory6_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_idxgifactory6_fill_default_vtbl(struct npt_idxgifactory6_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_idxgifactory6_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_idxgifactory6_client_vtbl npt_idxgifactory6_default_vtbl_storage;
extern void
npt_idxgifactory6_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_idxgifactory6_client_create(struct npt_device *dev, uint64_t host_id);


/* ================================================================== */
/* IDXGIFactory7                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * IDXGIFactory7Vtbl, by construction.
 */
struct npt_idxgifactory7_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: IDXGIObject::SetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateData)(void *self, const GUID * Name, UINT DataSize, const void * pData);
    /* slot 4: IDXGIObject::SetPrivateDataInterface */
    HRESULT (NPT_STDMETHODCALLTYPE *SetPrivateDataInterface)(void *self, const GUID * Name, const IUnknown * pUnknown);
    /* slot 5: IDXGIObject::GetPrivateData */
    HRESULT (NPT_STDMETHODCALLTYPE *GetPrivateData)(void *self, const GUID * Name, UINT * pDataSize, void * pData);
    /* slot 6: IDXGIObject::GetParent */
    HRESULT (NPT_STDMETHODCALLTYPE *GetParent)(void *self, const IID * riid, void ** ppParent);
    /* slot 7: IDXGIFactory::EnumAdapters */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapters)(void *self, UINT Adapter, IDXGIAdapter ** ppAdapter);
    /* slot 8: IDXGIFactory::MakeWindowAssociation */
    HRESULT (NPT_STDMETHODCALLTYPE *MakeWindowAssociation)(void *self, HWND WindowHandle, UINT Flags);
    /* slot 9: IDXGIFactory::GetWindowAssociation */
    HRESULT (NPT_STDMETHODCALLTYPE *GetWindowAssociation)(void *self, HWND * pWindowHandle);
    /* slot 10: IDXGIFactory::CreateSwapChain */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChain)(void *self, IUnknown * pDevice, DXGI_SWAP_CHAIN_DESC * pDesc, IDXGISwapChain ** ppSwapChain);
    /* slot 11: IDXGIFactory::CreateSoftwareAdapter */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSoftwareAdapter)(void *self, HMODULE Module, IDXGIAdapter ** ppAdapter);
    /* slot 12: IDXGIFactory1::EnumAdapters1 */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapters1)(void *self, UINT Adapter, IDXGIAdapter1 ** ppAdapter);
    /* slot 13: IDXGIFactory1::IsCurrent */
    BOOL (NPT_STDMETHODCALLTYPE *IsCurrent)(void *self);
    /* slot 14: IDXGIFactory2::IsWindowedStereoEnabled */
    BOOL (NPT_STDMETHODCALLTYPE *IsWindowedStereoEnabled)(void *self);
    /* slot 15: IDXGIFactory2::CreateSwapChainForHwnd */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChainForHwnd)(void *self, IUnknown * pDevice, HWND hWnd, const DXGI_SWAP_CHAIN_DESC1 * pDesc, const DXGI_SWAP_CHAIN_FULLSCREEN_DESC * pFullscreenDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);
    /* slot 16: IDXGIFactory2::CreateSwapChainForCoreWindow */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChainForCoreWindow)(void *self, IUnknown * pDevice, IUnknown * pWindow, const DXGI_SWAP_CHAIN_DESC1 * pDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);
    /* slot 17: IDXGIFactory2::GetSharedResourceAdapterLuid */
    HRESULT (NPT_STDMETHODCALLTYPE *GetSharedResourceAdapterLuid)(void *self, HANDLE hResource, LUID * pLuid);
    /* slot 18: IDXGIFactory2::RegisterStereoStatusWindow */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterStereoStatusWindow)(void *self, HWND WindowHandle, UINT wMsg, DWORD * pdwCookie);
    /* slot 19: IDXGIFactory2::RegisterStereoStatusEvent */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterStereoStatusEvent)(void *self, HANDLE hEvent, DWORD * pdwCookie);
    /* slot 20: IDXGIFactory2::UnregisterStereoStatus */
    void (NPT_STDMETHODCALLTYPE *UnregisterStereoStatus)(void *self, DWORD dwCookie);
    /* slot 21: IDXGIFactory2::RegisterOcclusionStatusWindow */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterOcclusionStatusWindow)(void *self, HWND WindowHandle, UINT wMsg, DWORD * pdwCookie);
    /* slot 22: IDXGIFactory2::RegisterOcclusionStatusEvent */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterOcclusionStatusEvent)(void *self, HANDLE hEvent, DWORD * pdwCookie);
    /* slot 23: IDXGIFactory2::UnregisterOcclusionStatus */
    void (NPT_STDMETHODCALLTYPE *UnregisterOcclusionStatus)(void *self, DWORD dwCookie);
    /* slot 24: IDXGIFactory2::CreateSwapChainForComposition */
    HRESULT (NPT_STDMETHODCALLTYPE *CreateSwapChainForComposition)(void *self, IUnknown * pDevice, const DXGI_SWAP_CHAIN_DESC1 * pDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 ** ppSwapChain);
    /* slot 25: IDXGIFactory3::GetCreationFlags */
    UINT (NPT_STDMETHODCALLTYPE *GetCreationFlags)(void *self);
    /* slot 26: IDXGIFactory4::EnumAdapterByLuid */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapterByLuid)(void *self, LUID AdapterLuid, const IID * riid, void ** ppvAdapter);
    /* slot 27: IDXGIFactory4::EnumWarpAdapter */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumWarpAdapter)(void *self, const IID * riid, void ** ppvAdapter);
    /* slot 28: IDXGIFactory5::CheckFeatureSupport */
    HRESULT (NPT_STDMETHODCALLTYPE *CheckFeatureSupport)(void *self, DXGI_FEATURE Feature, void * pFeatureSupportData, UINT FeatureSupportDataSize);
    /* slot 29: IDXGIFactory6::EnumAdapterByGpuPreference */
    HRESULT (NPT_STDMETHODCALLTYPE *EnumAdapterByGpuPreference)(void *self, UINT Adapter, DXGI_GPU_PREFERENCE GpuPreference, const IID * riid, void ** ppvAdapter);
    /* slot 30: IDXGIFactory7::RegisterAdaptersChangedEvent */
    HRESULT (NPT_STDMETHODCALLTYPE *RegisterAdaptersChangedEvent)(void *self, HANDLE hEvent, DWORD * pdwCookie);
    /* slot 31: IDXGIFactory7::UnregisterAdaptersChangedEvent */
    HRESULT (NPT_STDMETHODCALLTYPE *UnregisterAdaptersChangedEvent)(void *self, DWORD dwCookie);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory7_default_RegisterAdaptersChangedEvent(void *self, HANDLE hEvent, DWORD * pdwCookie);
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory7_default_UnregisterAdaptersChangedEvent(void *self, DWORD dwCookie);

/* Default IUnknown thunks for IDXGIFactory7.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_idxgifactory7_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgifactory7_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_idxgifactory7_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_idxgifactory7_fill_default_vtbl(struct npt_idxgifactory7_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_idxgifactory7_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_idxgifactory7_client_vtbl npt_idxgifactory7_default_vtbl_storage;
extern void
npt_idxgifactory7_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_idxgifactory7_client_create(struct npt_device *dev, uint64_t host_id);


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_CLIENT_IDXGIFACTORY_H */
