/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Client-side COM declarations for id3d12versionedrootsignaturedeserializer: per-interface vtable
 * structs, default thunk prototypes, default vtable populators, and default
 * constructors.
 *
 * The thunk bodies, populators, and constructors live in the matching .c
 * file.  This split keeps the headers small and prevents N copies of the
 * thunk code from landing in every TU that pulls in this family.
 */

#ifndef NPT_PROTOCOL_CLIENT_ID3D12VERSIONEDROOTSIGNATUREDESERIALIZER_H
#define NPT_PROTOCOL_CLIENT_ID3D12VERSIONEDROOTSIGNATUREDESERIALIZER_H

#include "npt_protocol_guest_id3d12versionedrootsignaturedeserializer.h"

/* Forward-declare struct npt_device so the client_create prototypes don't
 * trigger the "declared inside parameter list" warning.  The full
 * definition lives in the consumer's npt_device.h, which the .c file pulls
 * in via npt_com.h. */
struct npt_device;

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"



/* ================================================================== */
/* ID3D12VersionedRootSignatureDeserializer                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * ID3D12VersionedRootSignatureDeserializerVtbl, by construction.
 */
struct npt_id3d12versionedrootsignaturedeserializer_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
    /* slot 3: ID3D12VersionedRootSignatureDeserializer::GetRootSignatureDescAtVersion */
    HRESULT (NPT_STDMETHODCALLTYPE *GetRootSignatureDescAtVersion)(void *self, D3D_ROOT_SIGNATURE_VERSION convertToVersion, const D3D12_VERSIONED_ROOT_SIGNATURE_DESC ** ppDesc);
    /* slot 4: ID3D12VersionedRootSignatureDeserializer::GetUnconvertedRootSignatureDesc */
    D3D12_VERSIONED_ROOT_SIGNATURE_DESC * (NPT_STDMETHODCALLTYPE *GetUnconvertedRootSignatureDesc)(void *self, D3D12_VERSIONED_ROOT_SIGNATURE_DESC *_ret_out);
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d12versionedrootsignaturedeserializer_default_GetRootSignatureDescAtVersion(void *self, D3D_ROOT_SIGNATURE_VERSION convertToVersion, const D3D12_VERSIONED_ROOT_SIGNATURE_DESC ** ppDesc);
extern D3D12_VERSIONED_ROOT_SIGNATURE_DESC * NPT_STDMETHODCALLTYPE
npt_id3d12versionedrootsignaturedeserializer_default_GetUnconvertedRootSignatureDesc(void *self, D3D12_VERSIONED_ROOT_SIGNATURE_DESC *_ret_out);

/* Default IUnknown thunks for ID3D12VersionedRootSignatureDeserializer.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_id3d12versionedrootsignaturedeserializer_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_id3d12versionedrootsignaturedeserializer_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_id3d12versionedrootsignaturedeserializer_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_id3d12versionedrootsignaturedeserializer_fill_default_vtbl(struct npt_id3d12versionedrootsignaturedeserializer_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_id3d12versionedrootsignaturedeserializer_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_id3d12versionedrootsignaturedeserializer_client_vtbl npt_id3d12versionedrootsignaturedeserializer_default_vtbl_storage;
extern void
npt_id3d12versionedrootsignaturedeserializer_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_id3d12versionedrootsignaturedeserializer_client_create(struct npt_device *dev, uint64_t host_id);


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_CLIENT_ID3D12VERSIONEDROOTSIGNATUREDESERIALIZER_H */
